-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\user\Desktop\SHREYASHREE\files\systolic_cnn\matlab\codegen\conv3x3x3_4filters_stream\hdlsrc\conv3x3x3_4filters_stream_fixpt.vhd
-- Created: 2026-09-18 10:57:09
-- 
-- Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- output                        ce_out        1
-- valid                         ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: conv3x3x3_4filters_stream_fixpt
-- Source Path: conv3x3x3_4filters_stream_fixpt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.conv3x3x3_4filters_stream_fixpt_pkg.ALL;

ENTITY conv3x3x3_4filters_stream_fixpt IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        pixel                             :   IN    vector_of_std_logic_vector8(0 TO 2);  -- ufix8 [3]
        filter0                           :   IN    matrix3d_of_std_logic_vector3(0 TO 2, 0 TO 2, 0 TO 2);  -- sfix3 [3x3x3]
        filter1                           :   IN    matrix3d_of_std_logic_vector3(0 TO 2, 0 TO 2, 0 TO 2);  -- sfix3 [3x3x3]
        filter2                           :   IN    matrix3d_of_std_logic_vector3(0 TO 2, 0 TO 2, 0 TO 2);  -- sfix3 [3x3x3]
        filter3                           :   IN    matrix3d_of_std_logic_vector3(0 TO 2, 0 TO 2, 0 TO 2);  -- sfix3 [3x3x3]
        reset_1                           :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        output                            :   OUT   vector_of_std_logic_vector13(0 TO 3);  -- sfix13 [4]
        valid                             :   OUT   std_logic
        );
END conv3x3x3_4filters_stream_fixpt;


ARCHITECTURE rtl OF conv3x3x3_4filters_stream_fixpt IS

  -- Component Declarations
  COMPONENT SimpleDualPortRAM_generic
    GENERIC( AddrWidth                    : integer;
             DataWidth                    : integer
             );
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          wr_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          wr_en                           :   IN    std_logic;
          rd_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          dout                            :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SimpleDualPortRAM_generic
    USE ENTITY work.SimpleDualPortRAM_generic(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL reduced_reg                      : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL reset_2                          : std_logic;
  SIGNAL col                              : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL col_1                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL col_2                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL tmp                              : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL s                                : std_logic;
  SIGNAL tmp_1                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL tmp_2                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL row                              : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL row_1                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL tmp_3                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL s_1                              : std_logic;
  SIGNAL tmp_4                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL tmp_5                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL tmp_6                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL s_2                              : std_logic;
  SIGNAL delayMatch_reg                   : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL s_3                              : std_logic;
  SIGNAL tmp_7                            : matrix3d_of_unsigned8(0 TO 2, 0 TO 2, 0 TO 2);  -- ufix8 [3x3x3]
  SIGNAL c187_tmp                         : vector_of_unsigned8(0 TO 26);  -- ufix8 [27]
  SIGNAL stateControl_1                   : std_logic;
  SIGNAL delayMatch_reg_1                 : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL stateControl_2                   : std_logic;
  SIGNAL enb_gated                        : std_logic;
  SIGNAL stateControl_4                   : std_logic;
  SIGNAL delayMatch_reg_2                 : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL stateControl_5                   : std_logic;
  SIGNAL enb_gated_1                      : std_logic;
  SIGNAL stateControl_7                   : std_logic;
  SIGNAL delayMatch_reg_3                 : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL stateControl_8                   : std_logic;
  SIGNAL enb_gated_2                      : std_logic;
  SIGNAL tmp_8                            : vector_of_signed32(0 TO 2);  -- int32 [3]
  SIGNAL tmp_9                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_10                           : vector_of_signed32(0 TO 2);  -- int32 [3]
  SIGNAL tmp_11                           : vector_of_signed32(0 TO 2);  -- int32 [3]
  SIGNAL tmp_12                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_13                           : vector_of_signed32(0 TO 2);  -- int32 [3]
  SIGNAL pixel_unsigned                   : vector_of_unsigned8(0 TO 2);  -- ufix8 [3]
  SIGNAL s_4                              : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL s_5                              : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL a1                               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL s_6                              : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL a1_1                             : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL tmp_14                           : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL tmp_15                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL indexLogic_fixptsig              : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL s_7                              : std_logic;
  SIGNAL sel                              : std_logic;
  SIGNAL sel_2                            : std_logic;
  SIGNAL tmp_16                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL indexLogic_fixptsig_1            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL line1                            : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL line1_unsigned                   : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL tmp_17                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL indexLogic_fixptsig_2            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL indexLogic_fixptsig_3            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL s_8                              : std_logic;
  SIGNAL sel_1                            : std_logic;
  SIGNAL sel_2_1                          : std_logic;
  SIGNAL tmp_18                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL indexLogic_fixptsig_4            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL sel_2_2                          : std_logic;
  SIGNAL indexLogic_fixptsig_5            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL line2                            : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL line2_unsigned                   : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL s_9                              : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL top_r                            : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL s_10                             : std_logic;
  SIGNAL sel_3                            : std_logic;
  SIGNAL sel_2_3                          : std_logic;
  SIGNAL y                                : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL delayMatch_reg_4                 : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL sel_2_4                          : std_logic;
  SIGNAL s_11                             : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL top_g                            : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL s_12                             : std_logic;
  SIGNAL sel_4                            : std_logic;
  SIGNAL sel_2_5                          : std_logic;
  SIGNAL delayMatch_reg_5                 : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL sel_2_6                          : std_logic;
  SIGNAL y_1                              : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL top_b                            : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL s_13                             : std_logic;
  SIGNAL sel_5                            : std_logic;
  SIGNAL sel_2_7                          : std_logic;
  SIGNAL delayMatch_reg_6                 : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL sel_2_8                          : std_logic;
  SIGNAL s_14                             : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL middle_r                         : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL middle_r_1                       : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL s_15                             : std_logic;
  SIGNAL sel_6                            : std_logic;
  SIGNAL sel_2_9                          : std_logic;
  SIGNAL delayMatch_reg_7                 : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL sel_2_10                         : std_logic;
  SIGNAL y_2                              : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL s_16                             : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL middle_g                         : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL middle_g_1                       : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL s_17                             : std_logic;
  SIGNAL sel_7                            : std_logic;
  SIGNAL sel_2_11                         : std_logic;
  SIGNAL delayMatch_reg_8                 : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL sel_2_12                         : std_logic;
  SIGNAL y_3                              : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL middle_b                         : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL middle_b_1                       : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL s_18                             : std_logic;
  SIGNAL sel_8                            : std_logic;
  SIGNAL sel_2_13                         : std_logic;
  SIGNAL delayMatch_reg_9                 : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL sel_2_14                         : std_logic;
  SIGNAL tmp_19                           : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL delayMatch_reg_10                : vector_of_unsigned8(0 TO 1);  -- ufix8 [2]
  SIGNAL tmp_20                           : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL s_19                             : std_logic;
  SIGNAL sel_9                            : std_logic;
  SIGNAL sel_2_15                         : std_logic;
  SIGNAL delayMatch_reg_11                : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL sel_2_16                         : std_logic;
  SIGNAL tmp_21                           : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL delayMatch_reg_12                : vector_of_unsigned8(0 TO 1);  -- ufix8 [2]
  SIGNAL tmp_22                           : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL s_20                             : std_logic;
  SIGNAL sel_10                           : std_logic;
  SIGNAL sel_2_17                         : std_logic;
  SIGNAL delayMatch_reg_13                : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL sel_2_18                         : std_logic;
  SIGNAL tmp_23                           : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL delayMatch_reg_14                : vector_of_unsigned8(0 TO 1);  -- ufix8 [2]
  SIGNAL tmp_24                           : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL s_21                             : std_logic;
  SIGNAL sel_11                           : std_logic;
  SIGNAL sel_2_19                         : std_logic;
  SIGNAL delayMatch_reg_15                : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL sel_2_20                         : std_logic;
  SIGNAL window                           : matrix3d_of_unsigned8(0 TO 2, 0 TO 2, 0 TO 2);  -- ufix8 [3x3x3]
  SIGNAL tmp_25                           : matrix3d_of_unsigned8(0 TO 2, 0 DOWNTO 0, 0 TO 2);  -- ufix8 [3x1x3]
  SIGNAL window_1                         : matrix3d_of_unsigned8(0 TO 2, 0 TO 2, 0 TO 2);  -- ufix8 [3x3x3]
  SIGNAL tmp_26                           : matrix3d_of_unsigned8(0 TO 2, 0 DOWNTO 0, 0 TO 2);  -- ufix8 [3x1x3]
  SIGNAL tmp_27                           : matrix3d_of_unsigned8(0 TO 2, 0 TO 2, 0 TO 2);  -- ufix8 [3x3x3]
  SIGNAL selector_out                     : matrix_of_unsigned8(0 TO 2, 0 TO 2);  -- ufix8 [3x3]
  SIGNAL c220_selector_out                : vector_of_unsigned8(0 TO 8);  -- ufix8 [9]
  SIGNAL c220                             : vector_of_unsigned8(0 TO 8);  -- ufix8 [9]
  SIGNAL s_22                             : matrix_of_unsigned8(0 TO 2, 0 TO 2);  -- ufix8 [3x3]
  SIGNAL selector_out_1                   : matrix_of_unsigned8(0 TO 2, 0 TO 2);  -- ufix8 [3x3]
  SIGNAL c219_selector_out                : vector_of_unsigned8(0 TO 8);  -- ufix8 [9]
  SIGNAL c219                             : vector_of_unsigned8(0 TO 8);  -- ufix8 [9]
  SIGNAL s_23                             : matrix_of_unsigned8(0 TO 2, 0 TO 2);  -- ufix8 [3x3]
  SIGNAL window_2                         : matrix3d_of_unsigned8(0 TO 2, 0 TO 2, 0 TO 2);  -- ufix8 [3x3x3]
  SIGNAL c187_window                      : vector_of_unsigned8(0 TO 26);  -- ufix8 [27]
  SIGNAL c187_tmp_1                       : vector_of_unsigned8(0 TO 26);  -- ufix8 [27]
  SIGNAL selector_out_2                   : matrix_of_unsigned8(0 TO 2, 0 TO 2);  -- ufix8 [3x3]
  SIGNAL c218_selector_out                : vector_of_unsigned8(0 TO 8);  -- ufix8 [9]
  SIGNAL c218                             : vector_of_unsigned8(0 TO 8);  -- ufix8 [9]
  SIGNAL s_24                             : matrix_of_unsigned8(0 TO 2, 0 TO 2);  -- ufix8 [3x3]
  SIGNAL window_3                         : matrix3d_of_unsigned8(0 TO 2, 0 TO 2, 0 TO 2);  -- ufix8 [3x3x3]
  SIGNAL window_4                         : matrix3d_of_unsigned8(0 TO 2, 0 TO 2, 0 TO 2);  -- ufix8 [3x3x3]
  SIGNAL window_5                         : matrix3d_of_unsigned8(0 TO 2, 0 TO 2, 0 TO 2);  -- ufix8 [3x3x3]
  SIGNAL window_6                         : matrix3d_of_unsigned8(0 TO 2, 0 TO 2, 0 TO 2);  -- ufix8 [3x3x3]
  SIGNAL window_7                         : matrix3d_of_unsigned8(0 TO 2, 0 TO 2, 0 TO 2);  -- ufix8 [3x3x3]
  SIGNAL window_8                         : matrix3d_of_unsigned8(0 TO 2, 0 TO 2, 0 TO 2);  -- ufix8 [3x3x3]
  SIGNAL window_9                         : matrix3d_of_unsigned8(0 TO 2, 0 TO 2, 0 TO 2);  -- ufix8 [3x3x3]
  SIGNAL window_10                        : matrix3d_of_unsigned8(0 TO 2, 0 TO 2, 0 TO 2);  -- ufix8 [3x3x3]
  SIGNAL window_11                        : matrix3d_of_unsigned8(0 TO 2, 0 TO 2, 0 TO 2);  -- ufix8 [3x3x3]
  SIGNAL filter0_signed                   : matrix3d_of_signed3(0 TO 2, 0 TO 2, 0 TO 2);  -- sfix3 [3x3x3]
  SIGNAL selector_out_3                   : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL c517_selector_out                : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL selector_out_4                   : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL c518_selector_out                : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL selector_out_5                   : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL c519_selector_out                : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL delayMatch_reg_16                : vector_of_signed3(0 TO 17);  -- sfix3 [18]
  SIGNAL c517                             : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL s_25                             : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL delayMatch_reg_17                : vector_of_signed3(0 TO 17);  -- sfix3 [18]
  SIGNAL c518                             : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL s_26                             : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL delayMatch_reg_18                : vector_of_signed3(0 TO 17);  -- sfix3 [18]
  SIGNAL c519                             : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL s_27                             : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL filter0_1                        : matrix3d_of_signed3(0 TO 2, 0 TO 2, 0 TO 2);  -- sfix3 [3x3x3]
  SIGNAL acc_2                            : signed(12 DOWNTO 0);  -- sfix13
  SIGNAL sel_12                           : std_logic;
  SIGNAL s_28                             : std_logic;
  SIGNAL sel_2_21                         : std_logic;
  SIGNAL sel_13                           : std_logic;
  SIGNAL sel_2_22                         : std_logic;
  SIGNAL delayMatch_reg_19                : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL sel_2_23                         : std_logic;
  SIGNAL output_1                         : vector_of_signed13(0 TO 3);  -- sfix13 [4]
  SIGNAL filter1_signed                   : matrix3d_of_signed3(0 TO 2, 0 TO 2, 0 TO 2);  -- sfix3 [3x3x3]
  SIGNAL selector_out_6                   : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL c530_selector_out                : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL selector_out_7                   : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL c531_selector_out                : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL selector_out_8                   : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL c532_selector_out                : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL delayMatch_reg_20                : vector_of_signed3(0 TO 17);  -- sfix3 [18]
  SIGNAL c530                             : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL s_29                             : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL delayMatch_reg_21                : vector_of_signed3(0 TO 17);  -- sfix3 [18]
  SIGNAL c531                             : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL s_30                             : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL delayMatch_reg_22                : vector_of_signed3(0 TO 17);  -- sfix3 [18]
  SIGNAL c532                             : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL s_31                             : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL filter1_1                        : matrix3d_of_signed3(0 TO 2, 0 TO 2, 0 TO 2);  -- sfix3 [3x3x3]
  SIGNAL acc_3                            : signed(12 DOWNTO 0);  -- sfix13
  SIGNAL sel_14                           : std_logic;
  SIGNAL s_32                             : std_logic;
  SIGNAL sel_2_24                         : std_logic;
  SIGNAL sel_15                           : std_logic;
  SIGNAL sel_2_25                         : std_logic;
  SIGNAL delayMatch_reg_23                : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL sel_2_26                         : std_logic;
  SIGNAL filter2_signed                   : matrix3d_of_signed3(0 TO 2, 0 TO 2, 0 TO 2);  -- sfix3 [3x3x3]
  SIGNAL selector_out_9                   : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL c543_selector_out                : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL selector_out_10                  : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL c544_selector_out                : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL selector_out_11                  : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL c545_selector_out                : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL delayMatch_reg_24                : vector_of_signed3(0 TO 17);  -- sfix3 [18]
  SIGNAL c543                             : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL s_33                             : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL delayMatch_reg_25                : vector_of_signed3(0 TO 17);  -- sfix3 [18]
  SIGNAL c544                             : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL s_34                             : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL delayMatch_reg_26                : vector_of_signed3(0 TO 17);  -- sfix3 [18]
  SIGNAL c545                             : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL s_35                             : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL filter2_1                        : matrix3d_of_signed3(0 TO 2, 0 TO 2, 0 TO 2);  -- sfix3 [3x3x3]
  SIGNAL output_2                         : vector_of_signed13(0 TO 3);  -- sfix13 [4]
  SIGNAL acc_4                            : signed(12 DOWNTO 0);  -- sfix13
  SIGNAL sel_16                           : std_logic;
  SIGNAL s_36                             : std_logic;
  SIGNAL sel_2_27                         : std_logic;
  SIGNAL sel_17                           : std_logic;
  SIGNAL sel_2_28                         : std_logic;
  SIGNAL filter3_signed                   : matrix3d_of_signed3(0 TO 2, 0 TO 2, 0 TO 2);  -- sfix3 [3x3x3]
  SIGNAL selector_out_12                  : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL c556_selector_out                : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL selector_out_13                  : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL c557_selector_out                : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL selector_out_14                  : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL c558_selector_out                : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL delayMatch_reg_27                : vector_of_signed3(0 TO 17);  -- sfix3 [18]
  SIGNAL c556                             : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL s_37                             : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL delayMatch_reg_28                : vector_of_signed3(0 TO 17);  -- sfix3 [18]
  SIGNAL c557                             : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL s_38                             : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL delayMatch_reg_29                : vector_of_signed3(0 TO 17);  -- sfix3 [18]
  SIGNAL c558                             : vector_of_signed3(0 TO 8);  -- sfix3 [9]
  SIGNAL s_39                             : matrix_of_signed3(0 TO 2, 0 TO 2);  -- sfix3 [3x3]
  SIGNAL filter3_1                        : matrix3d_of_signed3(0 TO 2, 0 TO 2, 0 TO 2);  -- sfix3 [3x3x3]
  SIGNAL delayMatch_reg_30                : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL sel_2_29                         : std_logic;
  SIGNAL output_3                         : vector_of_signed13(0 TO 3);  -- sfix13 [4]
  SIGNAL acc_5                            : signed(12 DOWNTO 0);  -- sfix13
  SIGNAL sel_18                           : std_logic;
  SIGNAL s_40                             : std_logic;
  SIGNAL sel_2_30                         : std_logic;
  SIGNAL sel_19                           : std_logic;
  SIGNAL sel_2_31                         : std_logic;
  SIGNAL delayMatch_reg_31                : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL sel_2_32                         : std_logic;
  SIGNAL output_4                         : vector_of_signed13(0 TO 3);  -- sfix13 [4]
  SIGNAL tmp_28                           : vector_of_signed13(0 TO 3);  -- sfix13 [4]
  SIGNAL tmp_29                           : vector_of_signed13(0 TO 3);  -- sfix13 [4]
  SIGNAL valid_1                          : std_logic;
  SIGNAL valid_2                          : std_logic;
  SIGNAL tmp_30                           : std_logic;
  SIGNAL tmp_31                           : std_logic;
  SIGNAL delayMatch_reg_32                : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL tmp_32                           : std_logic;

BEGIN
  u_line1_ram_generic : SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 5,
                 DataWidth => 24
                 )
    PORT MAP( clk => clk,
              enb => clk_enable,
              wr_din => std_logic_vector(tmp_14),
              wr_addr => std_logic_vector(indexLogic_fixptsig),
              wr_en => sel_2,
              rd_addr => std_logic_vector(indexLogic_fixptsig_1),
              dout => line1
              );

  u_line2_ram : SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 5,
                 DataWidth => 24
                 )
    PORT MAP( clk => clk,
              enb => clk_enable,
              wr_din => line1,
              wr_addr => std_logic_vector(indexLogic_fixptsig_3),
              wr_en => sel_2_2,
              rd_addr => std_logic_vector(indexLogic_fixptsig_5),
              dout => line2
              );

  enb <= clk_enable;

  reduced_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      reduced_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        reduced_reg(0) <= reset_1;
        reduced_reg(1) <= reduced_reg(0);
      END IF;
    END IF;
  END PROCESS reduced_process;

  reset_2 <= reduced_reg(1);

  col <= to_unsigned(16#00#, 5);

  col_1 <= to_unsigned(16#00#, 5);

  tmp <= col_2 + to_unsigned(16#01#, 5);

  
  tmp_1 <= tmp WHEN s = '0' ELSE
      col;

  
  tmp_2 <= tmp_1 WHEN reset_1 = '0' ELSE
      col_1;

  col_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      col_2 <= to_unsigned(16#00#, 5);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        col_2 <= tmp_2;
      END IF;
    END IF;
  END PROCESS col_reg_process;


  
  s <= '1' WHEN col_2 = to_unsigned(16#1F#, 5) ELSE
      '0';

  row <= to_unsigned(16#00#, 5);

  tmp_3 <= row_1 + to_unsigned(16#01#, 5);

  
  s_1 <= '1' WHEN row_1 < to_unsigned(16#1F#, 5) ELSE
      '0';

  
  tmp_4 <= row_1 WHEN s_1 = '0' ELSE
      tmp_3;

  
  tmp_5 <= row_1 WHEN s = '0' ELSE
      tmp_4;

  
  tmp_6 <= tmp_5 WHEN reset_1 = '0' ELSE
      row;

  row_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      row_1 <= to_unsigned(16#00#, 5);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        row_1 <= tmp_6;
      END IF;
    END IF;
  END PROCESS row_reg_process;


  
  s_2 <= '1' WHEN (row_1 >= to_unsigned(16#02#, 5)) AND (col_2 >= to_unsigned(16#02#, 5)) ELSE
      '0';

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg(0) <= s_2;
        delayMatch_reg(1) <= delayMatch_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  s_3 <= delayMatch_reg(1);

  tmp_7 <= (OTHERS => (OTHERS => (OTHERS => to_unsigned(16#00#, 8))));

  c187_tmp_gen2: FOR d2 IN 0 TO 2 GENERATE
    c187_tmp_gen1: FOR d1 IN 0 TO 2 GENERATE
      c187_tmp_gen: FOR d0 IN 0 TO 2 GENERATE
        c187_tmp(d0 + (d1 * 3) + (d2 * 3 * 3)) <= tmp_7(d0, d1, d2);
      END GENERATE;
    END GENERATE;
  END GENERATE;

  stateControl_1 <= '1';

  delayMatch_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_1 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_1(0) <= stateControl_1;
        delayMatch_reg_1(1) <= delayMatch_reg_1(0);
      END IF;
    END IF;
  END PROCESS delayMatch_1_process;

  stateControl_2 <= delayMatch_reg_1(1);

  enb_gated <= stateControl_2 AND clk_enable;

  stateControl_4 <= '1';

  delayMatch_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_2 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_2(0) <= stateControl_4;
        delayMatch_reg_2(1) <= delayMatch_reg_2(0);
      END IF;
    END IF;
  END PROCESS delayMatch_2_process;

  stateControl_5 <= delayMatch_reg_2(1);

  enb_gated_1 <= stateControl_5 AND clk_enable;

  stateControl_7 <= '1';

  delayMatch_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_3 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_3(0) <= stateControl_7;
        delayMatch_reg_3(1) <= delayMatch_reg_3(0);
      END IF;
    END IF;
  END PROCESS delayMatch_3_process;

  stateControl_8 <= delayMatch_reg_3(1);

  enb_gated_2 <= stateControl_8 AND clk_enable;


  tmp_8_gen: FOR t_0 IN 0 TO 2 GENERATE
    tmp_8(t_0) <= to_signed(t_0, 32);
  END GENERATE tmp_8_gen;


  tmp_9 <= to_signed(16#00000001#, 32);


  tmp_10_gen: FOR t_01 IN 0 TO 2 GENERATE
    tmp_10(t_01) <= to_signed(t_01, 32);
  END GENERATE tmp_10_gen;



  tmp_11_gen: FOR t_02 IN 0 TO 2 GENERATE
    tmp_11(t_02) <= to_signed(t_02, 32);
  END GENERATE tmp_11_gen;


  tmp_12 <= to_signed(16#00000000#, 32);


  tmp_13_gen: FOR t_03 IN 0 TO 2 GENERATE
    tmp_13(t_03) <= to_signed(t_03, 32);
  END GENERATE tmp_13_gen;


  outputgen13: FOR k IN 0 TO 2 GENERATE
    pixel_unsigned(k) <= unsigned(pixel(k));
  END GENERATE;

  s_4 <= pixel_unsigned(0);

  s_5 <= pixel_unsigned(1);

  a1 <= resize(s_5, 32);

  s_6 <= pixel_unsigned(2);

  a1_1 <= resize(s_6, 32);

  tmp_14 <= resize((resize(s_4, 32) + (a1 sll 8)) + (a1_1 sll 16), 24);

  tmp_15 <= signed(resize(col_2, 32));

  indexLogic_fixptsig <= unsigned(tmp_15(4 DOWNTO 0));

  s_7 <= '1';

  sel <= '0';

  
  sel_2 <= s_7 WHEN reset_1 = '0' ELSE
      sel;

  tmp_16 <= signed(resize(col_2, 32));

  indexLogic_fixptsig_1 <= unsigned(tmp_16(4 DOWNTO 0));

  line1_unsigned <= unsigned(line1);

  tmp_17 <= signed(resize(col_2, 32));

  indexLogic_fixptsig_2 <= unsigned(tmp_17(4 DOWNTO 0));

  delayMatch_4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      indexLogic_fixptsig_3 <= to_unsigned(16#00#, 5);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        indexLogic_fixptsig_3 <= indexLogic_fixptsig_2;
      END IF;
    END IF;
  END PROCESS delayMatch_4_process;


  s_8 <= '1';

  sel_1 <= '0';

  
  sel_2_1 <= s_8 WHEN reset_1 = '0' ELSE
      sel_1;

  tmp_18 <= signed(resize(col_2, 32));

  indexLogic_fixptsig_4 <= unsigned(tmp_18(4 DOWNTO 0));

  delayMatch_5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sel_2_2 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        sel_2_2 <= sel_2_1;
      END IF;
    END IF;
  END PROCESS delayMatch_5_process;


  delayMatch_6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      indexLogic_fixptsig_5 <= to_unsigned(16#00#, 5);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        indexLogic_fixptsig_5 <= indexLogic_fixptsig_4;
      END IF;
    END IF;
  END PROCESS delayMatch_6_process;


  line2_unsigned <= unsigned(line2);

  s_9 <= to_unsigned(16#0000FF#, 24);

  top_r <= resize(line2_unsigned AND s_9, 8);

  s_10 <= '1';

  sel_3 <= '0';

  
  sel_2_3 <= s_10 WHEN reset_1 = '0' ELSE
      sel_3;

  y <= SHIFT_RIGHT(line2_unsigned, 8);

  delayMatch_7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_4 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_4(0) <= sel_2_3;
        delayMatch_reg_4(1) <= delayMatch_reg_4(0);
      END IF;
    END IF;
  END PROCESS delayMatch_7_process;

  sel_2_4 <= delayMatch_reg_4(1);

  s_11 <= to_unsigned(16#0000FF#, 24);

  top_g <= resize(y AND s_11, 8);

  s_12 <= '1';

  sel_4 <= '0';

  
  sel_2_5 <= s_12 WHEN reset_1 = '0' ELSE
      sel_4;

  delayMatch_8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_5 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_5(0) <= sel_2_5;
        delayMatch_reg_5(1) <= delayMatch_reg_5(0);
      END IF;
    END IF;
  END PROCESS delayMatch_8_process;

  sel_2_6 <= delayMatch_reg_5(1);

  y_1 <= SHIFT_RIGHT(line2_unsigned, 16);

  top_b <= y_1(7 DOWNTO 0);

  s_13 <= '1';

  sel_5 <= '0';

  
  sel_2_7 <= s_13 WHEN reset_1 = '0' ELSE
      sel_5;

  delayMatch_9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_6 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_6(0) <= sel_2_7;
        delayMatch_reg_6(1) <= delayMatch_reg_6(0);
      END IF;
    END IF;
  END PROCESS delayMatch_9_process;

  sel_2_8 <= delayMatch_reg_6(1);

  s_14 <= to_unsigned(16#0000FF#, 24);

  middle_r <= resize(line1_unsigned AND s_14, 8);

  delayMatch_10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      middle_r_1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        middle_r_1 <= middle_r;
      END IF;
    END IF;
  END PROCESS delayMatch_10_process;


  s_15 <= '1';

  sel_6 <= '0';

  
  sel_2_9 <= s_15 WHEN reset_1 = '0' ELSE
      sel_6;

  delayMatch_11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_7 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_7(0) <= sel_2_9;
        delayMatch_reg_7(1) <= delayMatch_reg_7(0);
      END IF;
    END IF;
  END PROCESS delayMatch_11_process;

  sel_2_10 <= delayMatch_reg_7(1);

  y_2 <= SHIFT_RIGHT(line1_unsigned, 8);

  s_16 <= to_unsigned(16#0000FF#, 24);

  middle_g <= resize(y_2 AND s_16, 8);

  delayMatch_12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      middle_g_1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        middle_g_1 <= middle_g;
      END IF;
    END IF;
  END PROCESS delayMatch_12_process;


  s_17 <= '1';

  sel_7 <= '0';

  
  sel_2_11 <= s_17 WHEN reset_1 = '0' ELSE
      sel_7;

  delayMatch_13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_8 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_8(0) <= sel_2_11;
        delayMatch_reg_8(1) <= delayMatch_reg_8(0);
      END IF;
    END IF;
  END PROCESS delayMatch_13_process;

  sel_2_12 <= delayMatch_reg_8(1);

  y_3 <= SHIFT_RIGHT(line1_unsigned, 16);

  middle_b <= y_3(7 DOWNTO 0);

  delayMatch_14_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      middle_b_1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        middle_b_1 <= middle_b;
      END IF;
    END IF;
  END PROCESS delayMatch_14_process;


  s_18 <= '1';

  sel_8 <= '0';

  
  sel_2_13 <= s_18 WHEN reset_1 = '0' ELSE
      sel_8;

  delayMatch_15_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_9 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_9(0) <= sel_2_13;
        delayMatch_reg_9(1) <= delayMatch_reg_9(0);
      END IF;
    END IF;
  END PROCESS delayMatch_15_process;

  sel_2_14 <= delayMatch_reg_9(1);

  tmp_19 <= pixel_unsigned(0);

  delayMatch_16_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_10 <= (OTHERS => to_unsigned(16#00#, 8));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_10(0) <= tmp_19;
        delayMatch_reg_10(1) <= delayMatch_reg_10(0);
      END IF;
    END IF;
  END PROCESS delayMatch_16_process;

  tmp_20 <= delayMatch_reg_10(1);

  s_19 <= '1';

  sel_9 <= '0';

  
  sel_2_15 <= s_19 WHEN reset_1 = '0' ELSE
      sel_9;

  delayMatch_17_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_11 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_11(0) <= sel_2_15;
        delayMatch_reg_11(1) <= delayMatch_reg_11(0);
      END IF;
    END IF;
  END PROCESS delayMatch_17_process;

  sel_2_16 <= delayMatch_reg_11(1);

  tmp_21 <= pixel_unsigned(1);

  delayMatch_18_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_12 <= (OTHERS => to_unsigned(16#00#, 8));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_12(0) <= tmp_21;
        delayMatch_reg_12(1) <= delayMatch_reg_12(0);
      END IF;
    END IF;
  END PROCESS delayMatch_18_process;

  tmp_22 <= delayMatch_reg_12(1);

  s_20 <= '1';

  sel_10 <= '0';

  
  sel_2_17 <= s_20 WHEN reset_1 = '0' ELSE
      sel_10;

  delayMatch_19_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_13 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_13(0) <= sel_2_17;
        delayMatch_reg_13(1) <= delayMatch_reg_13(0);
      END IF;
    END IF;
  END PROCESS delayMatch_19_process;

  sel_2_18 <= delayMatch_reg_13(1);

  tmp_23 <= pixel_unsigned(2);

  delayMatch_20_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_14 <= (OTHERS => to_unsigned(16#00#, 8));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_14(0) <= tmp_23;
        delayMatch_reg_14(1) <= delayMatch_reg_14(0);
      END IF;
    END IF;
  END PROCESS delayMatch_20_process;

  tmp_24 <= delayMatch_reg_14(1);

  s_21 <= '1';

  sel_11 <= '0';

  
  sel_2_19 <= s_21 WHEN reset_1 = '0' ELSE
      sel_11;

  delayMatch_21_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_15 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_15(0) <= sel_2_19;
        delayMatch_reg_15(1) <= delayMatch_reg_15(0);
      END IF;
    END IF;
  END PROCESS delayMatch_21_process;

  sel_2_20 <= delayMatch_reg_15(1);


  tmp_25_gen: FOR t_1 IN 0 TO 2 GENERATE
    tmp_25_gen_1: FOR t_04 IN 0 TO 2 GENERATE
      tmp_25(t_04, 0, t_1) <= window(t_04, 2, t_1);
    END GENERATE tmp_25_gen_1;
  END GENERATE tmp_25_gen;


  p105tmp_output : PROCESS (tmp_10, tmp_8, tmp_9, window_1)
    VARIABLE t_2 : signed(31 DOWNTO 0);
    VARIABLE t_3 : signed(31 DOWNTO 0);
  BEGIN
    t_2 := to_signed(16#00000000#, 32);
    t_3 := to_signed(16#00000000#, 32);

    FOR t_11 IN 0 TO 2 LOOP
      FOR t_05 IN 0 TO 2 LOOP
        t_2 := tmp_8(t_05);
        t_3 := tmp_10(t_11);
        tmp_26(t_05, 0, t_11) <= window_1(to_integer(t_2), to_integer(tmp_9), to_integer(t_3));
      END LOOP;
    END LOOP;

  END PROCESS p105tmp_output;



  selector_out_gen: FOR t_12 IN 0 TO 2 GENERATE
    selector_out_gen_1: FOR t_06 IN 0 TO 2 GENERATE
      selector_out(t_06, t_12) <= tmp_27(t_06, t_12, 2);
    END GENERATE selector_out_gen_1;
  END GENERATE selector_out_gen;


  c220_selector_out_gen1: FOR d1 IN 0 TO 2 GENERATE
    c220_selector_out_gen: FOR d0 IN 0 TO 2 GENERATE
      c220_selector_out(d0 + (d1 * 3)) <= selector_out(d0, d1);
    END GENERATE;
  END GENERATE;

  window_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      c220 <= (OTHERS => to_unsigned(16#00#, 8));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated_2 = '1' THEN
        c220 <= c220_selector_out;
      END IF;
    END IF;
  END PROCESS window_reg_process;


  s_22_gen1: FOR d1 IN 0 TO 2 GENERATE
    s_22_gen: FOR d0 IN 0 TO 2 GENERATE
      s_22(d0, d1) <= c220(d0 + (d1 * 3));
    END GENERATE;
  END GENERATE;


  selector_out_1_gen: FOR t_13 IN 0 TO 2 GENERATE
    selector_out_1_gen_1: FOR t_07 IN 0 TO 2 GENERATE
      selector_out_1(t_07, t_13) <= tmp_27(t_07, t_13, 1);
    END GENERATE selector_out_1_gen_1;
  END GENERATE selector_out_1_gen;


  c219_selector_out_gen1: FOR d1 IN 0 TO 2 GENERATE
    c219_selector_out_gen: FOR d0 IN 0 TO 2 GENERATE
      c219_selector_out(d0 + (d1 * 3)) <= selector_out_1(d0, d1);
    END GENERATE;
  END GENERATE;

  window_reg_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      c219 <= (OTHERS => to_unsigned(16#00#, 8));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated_1 = '1' THEN
        c219 <= c219_selector_out;
      END IF;
    END IF;
  END PROCESS window_reg_1_process;


  s_23_gen1: FOR d1 IN 0 TO 2 GENERATE
    s_23_gen: FOR d0 IN 0 TO 2 GENERATE
      s_23(d0, d1) <= c219(d0 + (d1 * 3));
    END GENERATE;
  END GENERATE;

  c187_window_gen2: FOR d2 IN 0 TO 2 GENERATE
    c187_window_gen1: FOR d1 IN 0 TO 2 GENERATE
      c187_window_gen: FOR d0 IN 0 TO 2 GENERATE
        c187_window(d0 + (d1 * 3) + (d2 * 3 * 3)) <= window_2(d0, d1, d2);
      END GENERATE;
    END GENERATE;
  END GENERATE;

  
  c187_tmp_1 <= c187_window WHEN reset_2 = '0' ELSE
      c187_tmp;

  tmp_27_gen2: FOR d2 IN 0 TO 2 GENERATE
    tmp_27_gen1: FOR d1 IN 0 TO 2 GENERATE
      tmp_27_gen: FOR d0 IN 0 TO 2 GENERATE
        tmp_27(d0, d1, d2) <= c187_tmp_1(d0 + (d1 * 3) + (d2 * 3 * 3));
      END GENERATE;
    END GENERATE;
  END GENERATE;


  selector_out_2_gen: FOR t_14 IN 0 TO 2 GENERATE
    selector_out_2_gen_1: FOR t_08 IN 0 TO 2 GENERATE
      selector_out_2(t_08, t_14) <= tmp_27(t_08, t_14, 0);
    END GENERATE selector_out_2_gen_1;
  END GENERATE selector_out_2_gen;


  c218_selector_out_gen1: FOR d1 IN 0 TO 2 GENERATE
    c218_selector_out_gen: FOR d0 IN 0 TO 2 GENERATE
      c218_selector_out(d0 + (d1 * 3)) <= selector_out_2(d0, d1);
    END GENERATE;
  END GENERATE;

  window_reg_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      c218 <= (OTHERS => to_unsigned(16#00#, 8));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated = '1' THEN
        c218 <= c218_selector_out;
      END IF;
    END IF;
  END PROCESS window_reg_2_process;


  s_24_gen1: FOR d1 IN 0 TO 2 GENERATE
    s_24_gen: FOR d0 IN 0 TO 2 GENERATE
      s_24(d0, d1) <= c218(d0 + (d1 * 3));
    END GENERATE;
  END GENERATE;

  window_1_gen1: FOR idx1 IN 0 TO 2 GENERATE
    window_1_gen: FOR idx IN 0 TO 2 GENERATE
      window_1(idx, idx1, 0) <= s_24(idx, idx1);
    END GENERATE;
  END GENERATE;
  window_1_gen3: FOR idx1 IN 0 TO 2 GENERATE
    window_1_gen2: FOR idx IN 0 TO 2 GENERATE
      window_1(idx, idx1, 1) <= s_23(idx, idx1);
    END GENERATE;
  END GENERATE;
  window_1_gen5: FOR idx1 IN 0 TO 2 GENERATE
    window_1_gen4: FOR idx IN 0 TO 2 GENERATE
      window_1(idx, idx1, 2) <= s_22(idx, idx1);
    END GENERATE;
  END GENERATE;

  p109window_output : PROCESS (tmp_11, tmp_12, tmp_13, tmp_26, window_1)
    VARIABLE t_21 : signed(31 DOWNTO 0);
    VARIABLE t_31 : signed(31 DOWNTO 0);
  BEGIN
    t_21 := to_signed(16#00000000#, 32);
    t_31 := to_signed(16#00000000#, 32);
    window <= window_1;

    FOR t_15 IN 0 TO 2 LOOP
      FOR t_09 IN 0 TO 2 LOOP
        t_21 := tmp_11(t_09);
        t_31 := tmp_13(t_15);
        window(to_integer(t_21), to_integer(tmp_12), to_integer(t_31)) <= tmp_26(t_09, 0, t_15);
      END LOOP;
    END LOOP;

  END PROCESS p109window_output;


  p111window_output : PROCESS (tmp_25, window)
  BEGIN
    window_3 <= window;

    FOR t_16 IN 0 TO 2 LOOP
      FOR t_010 IN 0 TO 2 LOOP
        window_3(t_010, 1, t_16) <= tmp_25(t_010, 0, t_16);
      END LOOP;
    END LOOP;

  END PROCESS p111window_output;


  p149window_output : PROCESS (sel_2_4, top_r, window_3)
  BEGIN
    window_4 <= window_3;
    IF sel_2_4 = '1' THEN 
      window_4(0, 2, 0) <= top_r;
    END IF;
  END PROCESS p149window_output;


  p62window_output : PROCESS (sel_2_6, top_g, window_4)
  BEGIN
    window_5 <= window_4;
    IF sel_2_6 = '1' THEN 
      window_5(0, 2, 1) <= top_g;
    END IF;
  END PROCESS p62window_output;


  p58window_output : PROCESS (sel_2_8, top_b, window_5)
  BEGIN
    window_6 <= window_5;
    IF sel_2_8 = '1' THEN 
      window_6(0, 2, 2) <= top_b;
    END IF;
  END PROCESS p58window_output;


  p54window_output : PROCESS (middle_r_1, sel_2_10, window_6)
  BEGIN
    window_7 <= window_6;
    IF sel_2_10 = '1' THEN 
      window_7(1, 2, 0) <= middle_r_1;
    END IF;
  END PROCESS p54window_output;


  p50window_output : PROCESS (middle_g_1, sel_2_12, window_7)
  BEGIN
    window_8 <= window_7;
    IF sel_2_12 = '1' THEN 
      window_8(1, 2, 1) <= middle_g_1;
    END IF;
  END PROCESS p50window_output;


  p46window_output : PROCESS (middle_b_1, sel_2_14, window_8)
  BEGIN
    window_9 <= window_8;
    IF sel_2_14 = '1' THEN 
      window_9(1, 2, 2) <= middle_b_1;
    END IF;
  END PROCESS p46window_output;


  p42window_output : PROCESS (sel_2_16, tmp_20, window_9)
  BEGIN
    window_10 <= window_9;
    IF sel_2_16 = '1' THEN 
      window_10(2, 2, 0) <= tmp_20;
    END IF;
  END PROCESS p42window_output;


  p38window_output : PROCESS (sel_2_18, tmp_22, window_10)
  BEGIN
    window_11 <= window_10;
    IF sel_2_18 = '1' THEN 
      window_11(2, 2, 1) <= tmp_22;
    END IF;
  END PROCESS p38window_output;


  p34window_output : PROCESS (sel_2_20, tmp_24, window_11)
  BEGIN
    window_2 <= window_11;
    IF sel_2_20 = '1' THEN 
      window_2(2, 2, 2) <= tmp_24;
    END IF;
  END PROCESS p34window_output;


  outputgen10: FOR k IN 0 TO 2 GENERATE
    outputgen11: FOR k1 IN 0 TO 2 GENERATE
      outputgen12: FOR k2 IN 0 TO 2 GENERATE
        filter0_signed(k, k1, k2) <= signed(filter0(k, k1, k2));
      END GENERATE;
    END GENERATE;
  END GENERATE;


  selector_out_3_gen: FOR t_17 IN 0 TO 2 GENERATE
    selector_out_3_gen_1: FOR t_011 IN 0 TO 2 GENERATE
      selector_out_3(t_011, t_17) <= filter0_signed(t_011, t_17, 0);
    END GENERATE selector_out_3_gen_1;
  END GENERATE selector_out_3_gen;


  c517_selector_out_gen1: FOR d1 IN 0 TO 2 GENERATE
    c517_selector_out_gen: FOR d0 IN 0 TO 2 GENERATE
      c517_selector_out(d0 + (d1 * 3)) <= selector_out_3(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_4_gen: FOR t_18 IN 0 TO 2 GENERATE
    selector_out_4_gen_1: FOR t_012 IN 0 TO 2 GENERATE
      selector_out_4(t_012, t_18) <= filter0_signed(t_012, t_18, 1);
    END GENERATE selector_out_4_gen_1;
  END GENERATE selector_out_4_gen;


  c518_selector_out_gen1: FOR d1 IN 0 TO 2 GENERATE
    c518_selector_out_gen: FOR d0 IN 0 TO 2 GENERATE
      c518_selector_out(d0 + (d1 * 3)) <= selector_out_4(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_5_gen: FOR t_19 IN 0 TO 2 GENERATE
    selector_out_5_gen_1: FOR t_013 IN 0 TO 2 GENERATE
      selector_out_5(t_013, t_19) <= filter0_signed(t_013, t_19, 2);
    END GENERATE selector_out_5_gen_1;
  END GENERATE selector_out_5_gen;


  c519_selector_out_gen1: FOR d1 IN 0 TO 2 GENERATE
    c519_selector_out_gen: FOR d0 IN 0 TO 2 GENERATE
      c519_selector_out(d0 + (d1 * 3)) <= selector_out_5(d0, d1);
    END GENERATE;
  END GENERATE;

  delayMatch_22_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_16 <= (OTHERS => to_signed(16#0#, 3));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_16(0 TO 8) <= c517_selector_out(0 TO 8);
        delayMatch_reg_16(9 TO 17) <= delayMatch_reg_16(0 TO 8);
      END IF;
    END IF;
  END PROCESS delayMatch_22_process;

  c517(0 TO 8) <= delayMatch_reg_16(9 TO 17);

  s_25_gen1: FOR d1 IN 0 TO 2 GENERATE
    s_25_gen: FOR d0 IN 0 TO 2 GENERATE
      s_25(d0, d1) <= c517(d0 + (d1 * 3));
    END GENERATE;
  END GENERATE;

  delayMatch_23_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_17 <= (OTHERS => to_signed(16#0#, 3));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_17(0 TO 8) <= c518_selector_out(0 TO 8);
        delayMatch_reg_17(9 TO 17) <= delayMatch_reg_17(0 TO 8);
      END IF;
    END IF;
  END PROCESS delayMatch_23_process;

  c518(0 TO 8) <= delayMatch_reg_17(9 TO 17);

  s_26_gen1: FOR d1 IN 0 TO 2 GENERATE
    s_26_gen: FOR d0 IN 0 TO 2 GENERATE
      s_26(d0, d1) <= c518(d0 + (d1 * 3));
    END GENERATE;
  END GENERATE;

  delayMatch_24_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_18 <= (OTHERS => to_signed(16#0#, 3));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_18(0 TO 8) <= c519_selector_out(0 TO 8);
        delayMatch_reg_18(9 TO 17) <= delayMatch_reg_18(0 TO 8);
      END IF;
    END IF;
  END PROCESS delayMatch_24_process;

  c519(0 TO 8) <= delayMatch_reg_18(9 TO 17);

  s_27_gen1: FOR d1 IN 0 TO 2 GENERATE
    s_27_gen: FOR d0 IN 0 TO 2 GENERATE
      s_27(d0, d1) <= c519(d0 + (d1 * 3));
    END GENERATE;
  END GENERATE;

  filter0_1_gen1: FOR idx1 IN 0 TO 2 GENERATE
    filter0_1_gen: FOR idx IN 0 TO 2 GENERATE
      filter0_1(idx, idx1, 0) <= s_25(idx, idx1);
    END GENERATE;
  END GENERATE;
  filter0_1_gen3: FOR idx1 IN 0 TO 2 GENERATE
    filter0_1_gen2: FOR idx IN 0 TO 2 GENERATE
      filter0_1(idx, idx1, 1) <= s_26(idx, idx1);
    END GENERATE;
  END GENERATE;
  filter0_1_gen5: FOR idx1 IN 0 TO 2 GENERATE
    filter0_1_gen4: FOR idx IN 0 TO 2 GENERATE
      filter0_1(idx, idx1, 2) <= s_27(idx, idx1);
    END GENERATE;
  END GENERATE;

  p33_output : PROCESS (filter0_1, window_2)
    VARIABLE acc : signed(12 DOWNTO 0);
    VARIABLE acc_0 : signed(12 DOWNTO 0);
    VARIABLE acc_1 : signed(12 DOWNTO 0);
    VARIABLE cast : signed(8 DOWNTO 0);
    VARIABLE mul_temp : signed(11 DOWNTO 0);
    VARIABLE add_cast : signed(10 DOWNTO 0);
  BEGIN
    acc_0 := to_signed(16#0000#, 13);
    acc_1 := to_signed(16#0000#, 13);
    mul_temp := to_signed(16#000#, 12);
    cast := to_signed(16#000#, 9);
    add_cast := to_signed(16#000#, 11);
    acc := to_signed(16#0000#, 13);

    FOR kr IN 0 TO 2 LOOP
      acc_0 := acc;

      FOR kc IN 0 TO 2 LOOP
        acc_1 := acc_0;

        FOR ch IN 0 TO 2 LOOP
          cast := signed(resize(window_2(kr, kc, ch), 9));
          mul_temp := cast * filter0_1(kr, kc, ch);
          add_cast := mul_temp(10 DOWNTO 0);
          acc_1 := acc_1 + resize(add_cast, 13);
        END LOOP;

        acc_0 := acc_1;
      END LOOP;

      acc := acc_0;
    END LOOP;

    acc_2 <= acc;
  END PROCESS p33_output;


  sel_12 <= '0';

  s_28 <= '1';

  
  sel_2_21 <= sel_12 WHEN s_2 = '0' ELSE
      s_28;

  sel_13 <= '0';

  
  sel_2_22 <= sel_2_21 WHEN reset_1 = '0' ELSE
      sel_13;

  delayMatch_25_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_19 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_19(0) <= sel_2_22;
        delayMatch_reg_19(1) <= delayMatch_reg_19(0);
      END IF;
    END IF;
  END PROCESS delayMatch_25_process;

  sel_2_23 <= delayMatch_reg_19(1);

  -- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  --                                                                          %
  --          Generated by MATLAB 25.1 and Fixed-Point Designer 25.1          %
  --                                                                          %
  -- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  p23output_output : PROCESS (acc_2, sel_2_23)
  BEGIN
    output_1 <= (OTHERS => to_signed(16#0000#, 13));
    IF sel_2_23 = '1' THEN 
      output_1(0) <= acc_2;
    END IF;
  END PROCESS p23output_output;


  outputgen7: FOR k IN 0 TO 2 GENERATE
    outputgen8: FOR k1 IN 0 TO 2 GENERATE
      outputgen9: FOR k2 IN 0 TO 2 GENERATE
        filter1_signed(k, k1, k2) <= signed(filter1(k, k1, k2));
      END GENERATE;
    END GENERATE;
  END GENERATE;


  selector_out_6_gen: FOR t_110 IN 0 TO 2 GENERATE
    selector_out_6_gen_1: FOR t_014 IN 0 TO 2 GENERATE
      selector_out_6(t_014, t_110) <= filter1_signed(t_014, t_110, 0);
    END GENERATE selector_out_6_gen_1;
  END GENERATE selector_out_6_gen;


  c530_selector_out_gen1: FOR d1 IN 0 TO 2 GENERATE
    c530_selector_out_gen: FOR d0 IN 0 TO 2 GENERATE
      c530_selector_out(d0 + (d1 * 3)) <= selector_out_6(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_7_gen: FOR t_111 IN 0 TO 2 GENERATE
    selector_out_7_gen_1: FOR t_015 IN 0 TO 2 GENERATE
      selector_out_7(t_015, t_111) <= filter1_signed(t_015, t_111, 1);
    END GENERATE selector_out_7_gen_1;
  END GENERATE selector_out_7_gen;


  c531_selector_out_gen1: FOR d1 IN 0 TO 2 GENERATE
    c531_selector_out_gen: FOR d0 IN 0 TO 2 GENERATE
      c531_selector_out(d0 + (d1 * 3)) <= selector_out_7(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_8_gen: FOR t_112 IN 0 TO 2 GENERATE
    selector_out_8_gen_1: FOR t_016 IN 0 TO 2 GENERATE
      selector_out_8(t_016, t_112) <= filter1_signed(t_016, t_112, 2);
    END GENERATE selector_out_8_gen_1;
  END GENERATE selector_out_8_gen;


  c532_selector_out_gen1: FOR d1 IN 0 TO 2 GENERATE
    c532_selector_out_gen: FOR d0 IN 0 TO 2 GENERATE
      c532_selector_out(d0 + (d1 * 3)) <= selector_out_8(d0, d1);
    END GENERATE;
  END GENERATE;

  delayMatch_26_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_20 <= (OTHERS => to_signed(16#0#, 3));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_20(0 TO 8) <= c530_selector_out(0 TO 8);
        delayMatch_reg_20(9 TO 17) <= delayMatch_reg_20(0 TO 8);
      END IF;
    END IF;
  END PROCESS delayMatch_26_process;

  c530(0 TO 8) <= delayMatch_reg_20(9 TO 17);

  s_29_gen1: FOR d1 IN 0 TO 2 GENERATE
    s_29_gen: FOR d0 IN 0 TO 2 GENERATE
      s_29(d0, d1) <= c530(d0 + (d1 * 3));
    END GENERATE;
  END GENERATE;

  delayMatch_27_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_21 <= (OTHERS => to_signed(16#0#, 3));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_21(0 TO 8) <= c531_selector_out(0 TO 8);
        delayMatch_reg_21(9 TO 17) <= delayMatch_reg_21(0 TO 8);
      END IF;
    END IF;
  END PROCESS delayMatch_27_process;

  c531(0 TO 8) <= delayMatch_reg_21(9 TO 17);

  s_30_gen1: FOR d1 IN 0 TO 2 GENERATE
    s_30_gen: FOR d0 IN 0 TO 2 GENERATE
      s_30(d0, d1) <= c531(d0 + (d1 * 3));
    END GENERATE;
  END GENERATE;

  delayMatch_28_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_22 <= (OTHERS => to_signed(16#0#, 3));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_22(0 TO 8) <= c532_selector_out(0 TO 8);
        delayMatch_reg_22(9 TO 17) <= delayMatch_reg_22(0 TO 8);
      END IF;
    END IF;
  END PROCESS delayMatch_28_process;

  c532(0 TO 8) <= delayMatch_reg_22(9 TO 17);

  s_31_gen1: FOR d1 IN 0 TO 2 GENERATE
    s_31_gen: FOR d0 IN 0 TO 2 GENERATE
      s_31(d0, d1) <= c532(d0 + (d1 * 3));
    END GENERATE;
  END GENERATE;

  filter1_1_gen1: FOR idx1 IN 0 TO 2 GENERATE
    filter1_1_gen: FOR idx IN 0 TO 2 GENERATE
      filter1_1(idx, idx1, 0) <= s_29(idx, idx1);
    END GENERATE;
  END GENERATE;
  filter1_1_gen3: FOR idx1 IN 0 TO 2 GENERATE
    filter1_1_gen2: FOR idx IN 0 TO 2 GENERATE
      filter1_1(idx, idx1, 1) <= s_30(idx, idx1);
    END GENERATE;
  END GENERATE;
  filter1_1_gen5: FOR idx1 IN 0 TO 2 GENERATE
    filter1_1_gen4: FOR idx IN 0 TO 2 GENERATE
      filter1_1(idx, idx1, 2) <= s_31(idx, idx1);
    END GENERATE;
  END GENERATE;

  p27_output : PROCESS (filter1_1, window_2)
    VARIABLE acc1 : signed(12 DOWNTO 0);
    VARIABLE acc_01 : signed(12 DOWNTO 0);
    VARIABLE acc_11 : signed(12 DOWNTO 0);
    VARIABLE cast1 : signed(8 DOWNTO 0);
    VARIABLE mul_temp1 : signed(11 DOWNTO 0);
    VARIABLE add_cast1 : signed(10 DOWNTO 0);
  BEGIN
    acc_01 := to_signed(16#0000#, 13);
    acc_11 := to_signed(16#0000#, 13);
    mul_temp1 := to_signed(16#000#, 12);
    cast1 := to_signed(16#000#, 9);
    add_cast1 := to_signed(16#000#, 11);
    acc1 := to_signed(16#0000#, 13);

    FOR kr1 IN 0 TO 2 LOOP
      acc_01 := acc1;

      FOR kc1 IN 0 TO 2 LOOP
        acc_11 := acc_01;

        FOR ch1 IN 0 TO 2 LOOP
          cast1 := signed(resize(window_2(kr1, kc1, ch1), 9));
          mul_temp1 := cast1 * filter1_1(kr1, kc1, ch1);
          add_cast1 := mul_temp1(10 DOWNTO 0);
          acc_11 := acc_11 + resize(add_cast1, 13);
        END LOOP;

        acc_01 := acc_11;
      END LOOP;

      acc1 := acc_01;
    END LOOP;

    acc_3 <= acc1;
  END PROCESS p27_output;


  sel_14 <= '0';

  s_32 <= '1';

  
  sel_2_24 <= sel_14 WHEN s_2 = '0' ELSE
      s_32;

  sel_15 <= '0';

  
  sel_2_25 <= sel_2_24 WHEN reset_1 = '0' ELSE
      sel_15;

  delayMatch_29_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_23 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_23(0) <= sel_2_25;
        delayMatch_reg_23(1) <= delayMatch_reg_23(0);
      END IF;
    END IF;
  END PROCESS delayMatch_29_process;

  sel_2_26 <= delayMatch_reg_23(1);

  outputgen4: FOR k IN 0 TO 2 GENERATE
    outputgen5: FOR k1 IN 0 TO 2 GENERATE
      outputgen6: FOR k2 IN 0 TO 2 GENERATE
        filter2_signed(k, k1, k2) <= signed(filter2(k, k1, k2));
      END GENERATE;
    END GENERATE;
  END GENERATE;


  selector_out_9_gen: FOR t_113 IN 0 TO 2 GENERATE
    selector_out_9_gen_1: FOR t_017 IN 0 TO 2 GENERATE
      selector_out_9(t_017, t_113) <= filter2_signed(t_017, t_113, 0);
    END GENERATE selector_out_9_gen_1;
  END GENERATE selector_out_9_gen;


  c543_selector_out_gen1: FOR d1 IN 0 TO 2 GENERATE
    c543_selector_out_gen: FOR d0 IN 0 TO 2 GENERATE
      c543_selector_out(d0 + (d1 * 3)) <= selector_out_9(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_10_gen: FOR t_114 IN 0 TO 2 GENERATE
    selector_out_10_gen_1: FOR t_018 IN 0 TO 2 GENERATE
      selector_out_10(t_018, t_114) <= filter2_signed(t_018, t_114, 1);
    END GENERATE selector_out_10_gen_1;
  END GENERATE selector_out_10_gen;


  c544_selector_out_gen1: FOR d1 IN 0 TO 2 GENERATE
    c544_selector_out_gen: FOR d0 IN 0 TO 2 GENERATE
      c544_selector_out(d0 + (d1 * 3)) <= selector_out_10(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_11_gen: FOR t_115 IN 0 TO 2 GENERATE
    selector_out_11_gen_1: FOR t_019 IN 0 TO 2 GENERATE
      selector_out_11(t_019, t_115) <= filter2_signed(t_019, t_115, 2);
    END GENERATE selector_out_11_gen_1;
  END GENERATE selector_out_11_gen;


  c545_selector_out_gen1: FOR d1 IN 0 TO 2 GENERATE
    c545_selector_out_gen: FOR d0 IN 0 TO 2 GENERATE
      c545_selector_out(d0 + (d1 * 3)) <= selector_out_11(d0, d1);
    END GENERATE;
  END GENERATE;

  delayMatch_30_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_24 <= (OTHERS => to_signed(16#0#, 3));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_24(0 TO 8) <= c543_selector_out(0 TO 8);
        delayMatch_reg_24(9 TO 17) <= delayMatch_reg_24(0 TO 8);
      END IF;
    END IF;
  END PROCESS delayMatch_30_process;

  c543(0 TO 8) <= delayMatch_reg_24(9 TO 17);

  s_33_gen1: FOR d1 IN 0 TO 2 GENERATE
    s_33_gen: FOR d0 IN 0 TO 2 GENERATE
      s_33(d0, d1) <= c543(d0 + (d1 * 3));
    END GENERATE;
  END GENERATE;

  delayMatch_31_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_25 <= (OTHERS => to_signed(16#0#, 3));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_25(0 TO 8) <= c544_selector_out(0 TO 8);
        delayMatch_reg_25(9 TO 17) <= delayMatch_reg_25(0 TO 8);
      END IF;
    END IF;
  END PROCESS delayMatch_31_process;

  c544(0 TO 8) <= delayMatch_reg_25(9 TO 17);

  s_34_gen1: FOR d1 IN 0 TO 2 GENERATE
    s_34_gen: FOR d0 IN 0 TO 2 GENERATE
      s_34(d0, d1) <= c544(d0 + (d1 * 3));
    END GENERATE;
  END GENERATE;

  delayMatch_32_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_26 <= (OTHERS => to_signed(16#0#, 3));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_26(0 TO 8) <= c545_selector_out(0 TO 8);
        delayMatch_reg_26(9 TO 17) <= delayMatch_reg_26(0 TO 8);
      END IF;
    END IF;
  END PROCESS delayMatch_32_process;

  c545(0 TO 8) <= delayMatch_reg_26(9 TO 17);

  s_35_gen1: FOR d1 IN 0 TO 2 GENERATE
    s_35_gen: FOR d0 IN 0 TO 2 GENERATE
      s_35(d0, d1) <= c545(d0 + (d1 * 3));
    END GENERATE;
  END GENERATE;

  filter2_1_gen1: FOR idx1 IN 0 TO 2 GENERATE
    filter2_1_gen: FOR idx IN 0 TO 2 GENERATE
      filter2_1(idx, idx1, 0) <= s_33(idx, idx1);
    END GENERATE;
  END GENERATE;
  filter2_1_gen3: FOR idx1 IN 0 TO 2 GENERATE
    filter2_1_gen2: FOR idx IN 0 TO 2 GENERATE
      filter2_1(idx, idx1, 1) <= s_34(idx, idx1);
    END GENERATE;
  END GENERATE;
  filter2_1_gen5: FOR idx1 IN 0 TO 2 GENERATE
    filter2_1_gen4: FOR idx IN 0 TO 2 GENERATE
      filter2_1(idx, idx1, 2) <= s_35(idx, idx1);
    END GENERATE;
  END GENERATE;

  p20output_output : PROCESS (acc_3, output_1, sel_2_26)
  BEGIN
    output_2 <= output_1;
    IF sel_2_26 = '1' THEN 
      output_2(1) <= acc_3;
    END IF;
  END PROCESS p20output_output;


  p31_output : PROCESS (filter2_1, window_2)
    VARIABLE acc2 : signed(12 DOWNTO 0);
    VARIABLE acc_02 : signed(12 DOWNTO 0);
    VARIABLE acc_12 : signed(12 DOWNTO 0);
    VARIABLE cast2 : signed(8 DOWNTO 0);
    VARIABLE mul_temp2 : signed(11 DOWNTO 0);
    VARIABLE add_cast2 : signed(10 DOWNTO 0);
  BEGIN
    acc_02 := to_signed(16#0000#, 13);
    acc_12 := to_signed(16#0000#, 13);
    mul_temp2 := to_signed(16#000#, 12);
    cast2 := to_signed(16#000#, 9);
    add_cast2 := to_signed(16#000#, 11);
    acc2 := to_signed(16#0000#, 13);

    FOR kr2 IN 0 TO 2 LOOP
      acc_02 := acc2;

      FOR kc2 IN 0 TO 2 LOOP
        acc_12 := acc_02;

        FOR ch2 IN 0 TO 2 LOOP
          cast2 := signed(resize(window_2(kr2, kc2, ch2), 9));
          mul_temp2 := cast2 * filter2_1(kr2, kc2, ch2);
          add_cast2 := mul_temp2(10 DOWNTO 0);
          acc_12 := acc_12 + resize(add_cast2, 13);
        END LOOP;

        acc_02 := acc_12;
      END LOOP;

      acc2 := acc_02;
    END LOOP;

    acc_4 <= acc2;
  END PROCESS p31_output;


  sel_16 <= '0';

  s_36 <= '1';

  
  sel_2_27 <= sel_16 WHEN s_2 = '0' ELSE
      s_36;

  sel_17 <= '0';

  
  sel_2_28 <= sel_2_27 WHEN reset_1 = '0' ELSE
      sel_17;

  outputgen1: FOR k IN 0 TO 2 GENERATE
    outputgen2: FOR k1 IN 0 TO 2 GENERATE
      outputgen3: FOR k2 IN 0 TO 2 GENERATE
        filter3_signed(k, k1, k2) <= signed(filter3(k, k1, k2));
      END GENERATE;
    END GENERATE;
  END GENERATE;


  selector_out_12_gen: FOR t_116 IN 0 TO 2 GENERATE
    selector_out_12_gen_1: FOR t_020 IN 0 TO 2 GENERATE
      selector_out_12(t_020, t_116) <= filter3_signed(t_020, t_116, 0);
    END GENERATE selector_out_12_gen_1;
  END GENERATE selector_out_12_gen;


  c556_selector_out_gen1: FOR d1 IN 0 TO 2 GENERATE
    c556_selector_out_gen: FOR d0 IN 0 TO 2 GENERATE
      c556_selector_out(d0 + (d1 * 3)) <= selector_out_12(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_13_gen: FOR t_117 IN 0 TO 2 GENERATE
    selector_out_13_gen_1: FOR t_021 IN 0 TO 2 GENERATE
      selector_out_13(t_021, t_117) <= filter3_signed(t_021, t_117, 1);
    END GENERATE selector_out_13_gen_1;
  END GENERATE selector_out_13_gen;


  c557_selector_out_gen1: FOR d1 IN 0 TO 2 GENERATE
    c557_selector_out_gen: FOR d0 IN 0 TO 2 GENERATE
      c557_selector_out(d0 + (d1 * 3)) <= selector_out_13(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_14_gen: FOR t_118 IN 0 TO 2 GENERATE
    selector_out_14_gen_1: FOR t_022 IN 0 TO 2 GENERATE
      selector_out_14(t_022, t_118) <= filter3_signed(t_022, t_118, 2);
    END GENERATE selector_out_14_gen_1;
  END GENERATE selector_out_14_gen;


  c558_selector_out_gen1: FOR d1 IN 0 TO 2 GENERATE
    c558_selector_out_gen: FOR d0 IN 0 TO 2 GENERATE
      c558_selector_out(d0 + (d1 * 3)) <= selector_out_14(d0, d1);
    END GENERATE;
  END GENERATE;

  delayMatch_33_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_27 <= (OTHERS => to_signed(16#0#, 3));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_27(0 TO 8) <= c556_selector_out(0 TO 8);
        delayMatch_reg_27(9 TO 17) <= delayMatch_reg_27(0 TO 8);
      END IF;
    END IF;
  END PROCESS delayMatch_33_process;

  c556(0 TO 8) <= delayMatch_reg_27(9 TO 17);

  s_37_gen1: FOR d1 IN 0 TO 2 GENERATE
    s_37_gen: FOR d0 IN 0 TO 2 GENERATE
      s_37(d0, d1) <= c556(d0 + (d1 * 3));
    END GENERATE;
  END GENERATE;

  delayMatch_34_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_28 <= (OTHERS => to_signed(16#0#, 3));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_28(0 TO 8) <= c557_selector_out(0 TO 8);
        delayMatch_reg_28(9 TO 17) <= delayMatch_reg_28(0 TO 8);
      END IF;
    END IF;
  END PROCESS delayMatch_34_process;

  c557(0 TO 8) <= delayMatch_reg_28(9 TO 17);

  s_38_gen1: FOR d1 IN 0 TO 2 GENERATE
    s_38_gen: FOR d0 IN 0 TO 2 GENERATE
      s_38(d0, d1) <= c557(d0 + (d1 * 3));
    END GENERATE;
  END GENERATE;

  delayMatch_35_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_29 <= (OTHERS => to_signed(16#0#, 3));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_29(0 TO 8) <= c558_selector_out(0 TO 8);
        delayMatch_reg_29(9 TO 17) <= delayMatch_reg_29(0 TO 8);
      END IF;
    END IF;
  END PROCESS delayMatch_35_process;

  c558(0 TO 8) <= delayMatch_reg_29(9 TO 17);

  s_39_gen1: FOR d1 IN 0 TO 2 GENERATE
    s_39_gen: FOR d0 IN 0 TO 2 GENERATE
      s_39(d0, d1) <= c558(d0 + (d1 * 3));
    END GENERATE;
  END GENERATE;

  filter3_1_gen1: FOR idx1 IN 0 TO 2 GENERATE
    filter3_1_gen: FOR idx IN 0 TO 2 GENERATE
      filter3_1(idx, idx1, 0) <= s_37(idx, idx1);
    END GENERATE;
  END GENERATE;
  filter3_1_gen3: FOR idx1 IN 0 TO 2 GENERATE
    filter3_1_gen2: FOR idx IN 0 TO 2 GENERATE
      filter3_1(idx, idx1, 1) <= s_38(idx, idx1);
    END GENERATE;
  END GENERATE;
  filter3_1_gen5: FOR idx1 IN 0 TO 2 GENERATE
    filter3_1_gen4: FOR idx IN 0 TO 2 GENERATE
      filter3_1(idx, idx1, 2) <= s_39(idx, idx1);
    END GENERATE;
  END GENERATE;

  delayMatch_36_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_30 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_30(0) <= sel_2_28;
        delayMatch_reg_30(1) <= delayMatch_reg_30(0);
      END IF;
    END IF;
  END PROCESS delayMatch_36_process;

  sel_2_29 <= delayMatch_reg_30(1);

  p17output_output : PROCESS (acc_4, output_2, sel_2_29)
  BEGIN
    output_3 <= output_2;
    IF sel_2_29 = '1' THEN 
      output_3(2) <= acc_4;
    END IF;
  END PROCESS p17output_output;


  p29_output : PROCESS (filter3_1, window_2)
    VARIABLE acc3 : signed(12 DOWNTO 0);
    VARIABLE acc_03 : signed(12 DOWNTO 0);
    VARIABLE acc_13 : signed(12 DOWNTO 0);
    VARIABLE cast3 : signed(8 DOWNTO 0);
    VARIABLE mul_temp3 : signed(11 DOWNTO 0);
    VARIABLE add_cast3 : signed(10 DOWNTO 0);
  BEGIN
    acc_03 := to_signed(16#0000#, 13);
    acc_13 := to_signed(16#0000#, 13);
    mul_temp3 := to_signed(16#000#, 12);
    cast3 := to_signed(16#000#, 9);
    add_cast3 := to_signed(16#000#, 11);
    acc3 := to_signed(16#0000#, 13);

    FOR kr3 IN 0 TO 2 LOOP
      acc_03 := acc3;

      FOR kc3 IN 0 TO 2 LOOP
        acc_13 := acc_03;

        FOR ch3 IN 0 TO 2 LOOP
          cast3 := signed(resize(window_2(kr3, kc3, ch3), 9));
          mul_temp3 := cast3 * filter3_1(kr3, kc3, ch3);
          add_cast3 := mul_temp3(10 DOWNTO 0);
          acc_13 := acc_13 + resize(add_cast3, 13);
        END LOOP;

        acc_03 := acc_13;
      END LOOP;

      acc3 := acc_03;
    END LOOP;

    acc_5 <= acc3;
  END PROCESS p29_output;


  sel_18 <= '0';

  s_40 <= '1';

  
  sel_2_30 <= sel_18 WHEN s_2 = '0' ELSE
      s_40;

  sel_19 <= '0';

  
  sel_2_31 <= sel_2_30 WHEN reset_1 = '0' ELSE
      sel_19;

  delayMatch_37_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_31 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_31(0) <= sel_2_31;
        delayMatch_reg_31(1) <= delayMatch_reg_31(0);
      END IF;
    END IF;
  END PROCESS delayMatch_37_process;

  sel_2_32 <= delayMatch_reg_31(1);

  p14output_output : PROCESS (acc_5, output_3, sel_2_32)
  BEGIN
    output_4 <= output_3;
    IF sel_2_32 = '1' THEN 
      output_4(3) <= acc_5;
    END IF;
  END PROCESS p14output_output;


  
  tmp_28 <= output_1 WHEN s_3 = '0' ELSE
      output_4;

  
  tmp_29 <= tmp_28 WHEN reset_2 = '0' ELSE
      output_1;

  outputgen: FOR k IN 0 TO 3 GENERATE
    output(k) <= std_logic_vector(tmp_29(k));
  END GENERATE;

  valid_1 <= '0';

  valid_2 <= '1';

  
  tmp_30 <= valid_1 WHEN s_2 = '0' ELSE
      valid_2;

  
  tmp_31 <= tmp_30 WHEN reset_1 = '0' ELSE
      valid_1;

  delayMatch_38_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg_32 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg_32(0) <= tmp_31;
        delayMatch_reg_32(1) <= delayMatch_reg_32(0);
      END IF;
    END IF;
  END PROCESS delayMatch_38_process;

  tmp_32 <= delayMatch_reg_32(1);

  ce_out <= clk_enable;

  valid <= tmp_32;

END rtl;

