// -------------------------------------------------------------
// 
// File Name: C:\Users\user\Desktop\SHREYASHREE\files\systolic_cnn\matlab\codegen\conv3x3x3_4filters\hdlsrc\conv3x3x3_4filters_fixpt.sv
// Created: 2026-09-17 22:13:16
// 
// Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// -------------------------------------------------------------


import conv3x3x3_4filters_fixpt_pkg::* ;

// -------------------------------------------------------------
// 
// Module: conv3x3x3_4filters_fixpt
// Source Path: conv3x3x3_4filters_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module conv3x3x3_4filters_fixpt
          (  input vector_of_unsigned_logic_8 image_window[0:2] [0:2] [0:2]  /* ufix8 [3x3x3] */,
             input vector_of_signed_logic_3 filter0[0:2] [0:2] [0:2]  /* sfix3 [3x3x3] */,
             input vector_of_signed_logic_3 filter1[0:2] [0:2] [0:2]  /* sfix3 [3x3x3] */,
             input vector_of_signed_logic_3 filter2[0:2] [0:2] [0:2]  /* sfix3 [3x3x3] */,
             input vector_of_signed_logic_3 filter3[0:2] [0:2] [0:2]  /* sfix3 [3x3x3] */,
             output vector_of_signed_logic_13 output_rsvd[0:3]  /* sfix13 [4] */);


  vector_of_signed_logic_13 output_rsvd_1 [0:3];  /* sfix13 [4] */
  logic signed [31:0] conv3x3x3_4filters_fixpt_kr;  /* int32 */
  logic signed [31:0] conv3x3x3_4filters_fixpt_kc;  /* int32 */
  logic signed [31:0] conv3x3x3_4filters_fixpt_ch;  /* int32 */
  logic signed [31:0] conv3x3x3_4filters_fixpt_kr_0;  /* int32 */
  logic signed [31:0] conv3x3x3_4filters_fixpt_kc_0;  /* int32 */
  logic signed [31:0] conv3x3x3_4filters_fixpt_ch_0;  /* int32 */
  logic signed [12:0] conv3x3x3_4filters_fixpt_acc;  /* sfix13 */
  logic signed [12:0] conv3x3x3_4filters_fixpt_acc_0;  /* sfix13 */
  logic signed [12:0] conv3x3x3_4filters_fixpt_acc_1;  /* sfix13 */
  logic signed [12:0] conv3x3x3_4filters_fixpt_acc_2;  /* sfix13 */
  logic signed [10:0] conv3x3x3_4filters_fixpt_add_cast;  /* sfix11 */
  logic signed [10:0] conv3x3x3_4filters_fixpt_add_cast_0;  /* sfix11 */
  logic signed [10:0] conv3x3x3_4filters_fixpt_add_cast_1;  /* sfix11 */
  logic signed [10:0] conv3x3x3_4filters_fixpt_add_cast_2;  /* sfix11 */
  vector_of_signed_logic_9 conv3x3x3_4filters_fixpt_t_0 [0:2] [0:2];  /* sfix9 [3x3] */
  vector_of_signed_logic_12 conv3x3x3_4filters_fixpt_mul_temp [0:2] [0:2];  /* sfix12 [3x3] */
  vector_of_signed_logic_13 conv3x3x3_4filters_fixpt_t_1 [0:2] [0:2];  /* sfix13 [3x3] */
  vector_of_signed_logic_9 conv3x3x3_4filters_fixpt_t_2 [0:2] [0:2];  /* sfix9 [3x3] */
  vector_of_signed_logic_12 conv3x3x3_4filters_fixpt_mul_temp_0 [0:2] [0:2];  /* sfix12 [3x3] */
  vector_of_signed_logic_13 conv3x3x3_4filters_fixpt_t_3 [0:2] [0:2];  /* sfix13 [3x3] */
  vector_of_signed_logic_9 conv3x3x3_4filters_fixpt_t_4 [0:2] [0:2];  /* sfix9 [3x3] */
  vector_of_signed_logic_12 conv3x3x3_4filters_fixpt_mul_temp_1 [0:2] [0:2];  /* sfix12 [3x3] */
  vector_of_signed_logic_13 conv3x3x3_4filters_fixpt_t_5 [0:2] [0:2];  /* sfix13 [3x3] */
  vector_of_signed_logic_9 conv3x3x3_4filters_fixpt_t_6 [0:2] [0:2];  /* sfix9 [3x3] */
  vector_of_signed_logic_12 conv3x3x3_4filters_fixpt_mul_temp_2 [0:2] [0:2];  /* sfix12 [3x3] */
  vector_of_signed_logic_13 conv3x3x3_4filters_fixpt_t_7 [0:2] [0:2];  /* sfix13 [3x3] */


  always_comb begin
    conv3x3x3_4filters_fixpt_add_cast = 11'sb00000000000;
    conv3x3x3_4filters_fixpt_add_cast_0 = 11'sb00000000000;
    conv3x3x3_4filters_fixpt_add_cast_1 = 11'sb00000000000;
    conv3x3x3_4filters_fixpt_add_cast_2 = 11'sb00000000000;
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    //                                                                          %
    //          Generated by MATLAB 25.1 and Fixed-Point Designer 25.1          %
    //                                                                          %
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    conv3x3x3_4filters_fixpt_acc = 13'sb0000000000000;

    for(conv3x3x3_4filters_fixpt_kr = 32'sd0; conv3x3x3_4filters_fixpt_kr <= 32'sd2; conv3x3x3_4filters_fixpt_kr = conv3x3x3_4filters_fixpt_kr + 32'sd1) begin
      for(conv3x3x3_4filters_fixpt_kc = 32'sd0; conv3x3x3_4filters_fixpt_kc <= 32'sd2; conv3x3x3_4filters_fixpt_kc = conv3x3x3_4filters_fixpt_kc + 32'sd1) begin
        for(conv3x3x3_4filters_fixpt_ch = 32'sd0; conv3x3x3_4filters_fixpt_ch <= 32'sd2; conv3x3x3_4filters_fixpt_ch = conv3x3x3_4filters_fixpt_ch + 32'sd1) begin
          conv3x3x3_4filters_fixpt_t_0[conv3x3x3_4filters_fixpt_kc][conv3x3x3_4filters_fixpt_ch] = {1'b0, image_window[conv3x3x3_4filters_fixpt_kr][conv3x3x3_4filters_fixpt_kc][conv3x3x3_4filters_fixpt_ch]};
          conv3x3x3_4filters_fixpt_mul_temp[conv3x3x3_4filters_fixpt_kc][conv3x3x3_4filters_fixpt_ch] = conv3x3x3_4filters_fixpt_t_0[conv3x3x3_4filters_fixpt_kc][conv3x3x3_4filters_fixpt_ch] * filter0[conv3x3x3_4filters_fixpt_kr][conv3x3x3_4filters_fixpt_kc][conv3x3x3_4filters_fixpt_ch];
          conv3x3x3_4filters_fixpt_add_cast = conv3x3x3_4filters_fixpt_mul_temp[conv3x3x3_4filters_fixpt_kc][conv3x3x3_4filters_fixpt_ch][10:0];
          conv3x3x3_4filters_fixpt_t_1[conv3x3x3_4filters_fixpt_kc][conv3x3x3_4filters_fixpt_ch] = {{2{conv3x3x3_4filters_fixpt_add_cast[10]}}, conv3x3x3_4filters_fixpt_add_cast};
          conv3x3x3_4filters_fixpt_acc = conv3x3x3_4filters_fixpt_acc + conv3x3x3_4filters_fixpt_t_1[conv3x3x3_4filters_fixpt_kc][conv3x3x3_4filters_fixpt_ch];
        end
      end
    end

    output_rsvd_1[0] = conv3x3x3_4filters_fixpt_acc;
    conv3x3x3_4filters_fixpt_acc_0 = 13'sb0000000000000;
    conv3x3x3_4filters_fixpt_acc_1 = 13'sb0000000000000;
    conv3x3x3_4filters_fixpt_acc_2 = 13'sb0000000000000;

    for(conv3x3x3_4filters_fixpt_kr_0 = 32'sd0; conv3x3x3_4filters_fixpt_kr_0 <= 32'sd2; conv3x3x3_4filters_fixpt_kr_0 = conv3x3x3_4filters_fixpt_kr_0 + 32'sd1) begin
      for(conv3x3x3_4filters_fixpt_kc_0 = 32'sd0; conv3x3x3_4filters_fixpt_kc_0 <= 32'sd2; conv3x3x3_4filters_fixpt_kc_0 = conv3x3x3_4filters_fixpt_kc_0 + 32'sd1) begin
        for(conv3x3x3_4filters_fixpt_ch_0 = 32'sd0; conv3x3x3_4filters_fixpt_ch_0 <= 32'sd2; conv3x3x3_4filters_fixpt_ch_0 = conv3x3x3_4filters_fixpt_ch_0 + 32'sd1) begin
          conv3x3x3_4filters_fixpt_t_2[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0] = {1'b0, image_window[conv3x3x3_4filters_fixpt_kr_0][conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0]};
          conv3x3x3_4filters_fixpt_mul_temp_0[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0] = conv3x3x3_4filters_fixpt_t_2[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0] * filter1[conv3x3x3_4filters_fixpt_kr_0][conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0];
          conv3x3x3_4filters_fixpt_add_cast_0 = conv3x3x3_4filters_fixpt_mul_temp_0[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0][10:0];
          conv3x3x3_4filters_fixpt_t_3[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0] = {{2{conv3x3x3_4filters_fixpt_add_cast_0[10]}}, conv3x3x3_4filters_fixpt_add_cast_0};
          conv3x3x3_4filters_fixpt_acc_0 = conv3x3x3_4filters_fixpt_acc_0 + conv3x3x3_4filters_fixpt_t_3[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0];
          conv3x3x3_4filters_fixpt_t_4[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0] = {1'b0, image_window[conv3x3x3_4filters_fixpt_kr_0][conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0]};
          conv3x3x3_4filters_fixpt_mul_temp_1[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0] = conv3x3x3_4filters_fixpt_t_4[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0] * filter2[conv3x3x3_4filters_fixpt_kr_0][conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0];
          conv3x3x3_4filters_fixpt_add_cast_1 = conv3x3x3_4filters_fixpt_mul_temp_1[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0][10:0];
          conv3x3x3_4filters_fixpt_t_5[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0] = {{2{conv3x3x3_4filters_fixpt_add_cast_1[10]}}, conv3x3x3_4filters_fixpt_add_cast_1};
          conv3x3x3_4filters_fixpt_acc_1 = conv3x3x3_4filters_fixpt_acc_1 + conv3x3x3_4filters_fixpt_t_5[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0];
          conv3x3x3_4filters_fixpt_t_6[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0] = {1'b0, image_window[conv3x3x3_4filters_fixpt_kr_0][conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0]};
          conv3x3x3_4filters_fixpt_mul_temp_2[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0] = conv3x3x3_4filters_fixpt_t_6[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0] * filter3[conv3x3x3_4filters_fixpt_kr_0][conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0];
          conv3x3x3_4filters_fixpt_add_cast_2 = conv3x3x3_4filters_fixpt_mul_temp_2[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0][10:0];
          conv3x3x3_4filters_fixpt_t_7[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0] = {{2{conv3x3x3_4filters_fixpt_add_cast_2[10]}}, conv3x3x3_4filters_fixpt_add_cast_2};
          conv3x3x3_4filters_fixpt_acc_2 = conv3x3x3_4filters_fixpt_acc_2 + conv3x3x3_4filters_fixpt_t_7[conv3x3x3_4filters_fixpt_kc_0][conv3x3x3_4filters_fixpt_ch_0];
        end
      end
    end

    output_rsvd_1[1] = conv3x3x3_4filters_fixpt_acc_0;
    output_rsvd_1[2] = conv3x3x3_4filters_fixpt_acc_1;
    output_rsvd_1[3] = conv3x3x3_4filters_fixpt_acc_2;
  end

  assign output_rsvd = output_rsvd_1;

endmodule  // conv3x3x3_4filters_fixpt

