-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\user\Desktop\SHREYASHREE\files\cnn_fpga\matlab\codegen\conv3x3x3_pixel\hdlsrc\conv3x3x3_pixel_fixpt_pkg.vhd
-- Created: 2026-09-15 12:09:58
-- 
-- Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
-- 
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE conv3x3x3_pixel_fixpt_pkg IS
  TYPE matrix3d_of_std_logic_vector6 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>) OF std_logic_vector(5 DOWNTO 0);
  TYPE matrix3d_of_std_logic_vector3 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>) OF std_logic_vector(2 DOWNTO 0);
  TYPE matrix3d_of_unsigned6 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>) OF unsigned(5 DOWNTO 0);
  TYPE matrix3d_of_signed3 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>) OF signed(2 DOWNTO 0);
END conv3x3x3_pixel_fixpt_pkg;

