// -------------------------------------------------------------
// 
// File Name: C:\Users\user\Desktop\SHREYASHREE\files\systolic_cnn\matlab\codegen\conv3x3x3_stream\hdlsrc\conv3x3x3_stream_fixpt.sv
// Created: 2026-09-16 18:35:20
// 
// Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// output_rsvd                   ce_out        1
// valid                         ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


import conv3x3x3_stream_fixpt_pkg::* ;

// -------------------------------------------------------------
// 
// Module: conv3x3x3_stream_fixpt
// Source Path: conv3x3x3_stream_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module conv3x3x3_stream_fixpt
          (  input logic clk,
             input logic reset,
             input logic clk_enable,
             input vector_of_unsigned_logic_8 pixel[0:2]  /* ufix8 [3] */,
             input vector_of_signed_logic_3 filter[0:2] [0:2] [0:2]  /* sfix3 [3x3x3] */,
             input logic reset_1,
             output logic ce_out,
             output logic [11:0] output_rsvd  /* ufix12 */,
             output logic valid);


  logic enb;
  logic [1:0] reduced_reg;  /* ufix1 [2] */
  logic reset_2;
  logic [4:0] col;  /* ufix5 */
  logic [4:0] col_1;  /* ufix5 */
  logic [4:0] col_2;  /* ufix5 */
  logic [4:0] tmp;  /* ufix5 */
  logic s;
  logic [4:0] tmp_1;  /* ufix5 */
  logic [4:0] tmp_2;  /* ufix5 */
  logic [5:0] row;  /* ufix6 */
  logic [5:0] row_1;  /* ufix6 */
  logic [5:0] tmp_3;  /* ufix6 */
  logic [5:0] tmp_4;  /* ufix6 */
  logic [5:0] tmp_5;  /* ufix6 */
  logic s_1;
  logic [1:0] delayMatch_reg;  /* ufix1 [2] */
  logic s_2;
  logic [11:0] output_reg;  /* ufix12 */
  vector_of_unsigned_logic_8 tmp_6 [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_unsigned_logic_8 c136_tmp [0:26];  /* ufix8 [27] */
  logic stateControl_1;
  logic [1:0] delayMatch_reg_1;  /* ufix1 [2] */
  logic stateControl_2;
  logic enb_gated;
  logic stateControl_4;
  logic [1:0] delayMatch_reg_2;  /* ufix1 [2] */
  logic stateControl_5;
  logic enb_gated_1;
  logic stateControl_7;
  logic [1:0] delayMatch_reg_3;  /* ufix1 [2] */
  logic stateControl_8;
  logic enb_gated_2;
  vector_of_unsigned_logic_8 top [0:2];  /* ufix8 [3] */
  logic [7:0] s_3;  /* ufix8 */
  logic [7:0] s_4;  /* ufix8 */
  logic [31:0] a1;  /* uint32 */
  logic [7:0] s_5;  /* ufix8 */
  logic [31:0] a1_1;  /* uint32 */
  logic [23:0] tmp_7;  /* ufix24 */
  logic [31:0] p80tmp_add_temp;  /* uint32 */
  logic [31:0] p80tmp_1;  /* uint32 */
  logic signed [31:0] tmp_8;  /* int32 */
  logic [4:0] indexLogic_fixptsig;  /* ufix5 */
  logic s_6;
  logic sel;
  logic sel_2;
  logic signed [31:0] tmp_9;  /* int32 */
  logic [4:0] indexLogic_fixptsig_1;  /* ufix5 */
  logic [23:0] line1;  /* ufix24 */
  logic signed [31:0] tmp_10;  /* int32 */
  logic [4:0] indexLogic_fixptsig_2;  /* ufix5 */
  logic [4:0] indexLogic_fixptsig_3;  /* ufix5 */
  logic s_7;
  logic sel_1;
  logic sel_2_1;
  logic sel_2_2;
  logic signed [31:0] tmp_11;  /* int32 */
  logic [4:0] indexLogic_fixptsig_4;  /* ufix5 */
  logic [4:0] indexLogic_fixptsig_5;  /* ufix5 */
  logic [23:0] line2;  /* ufix24 */
  logic [23:0] s_8;  /* ufix24 */
  logic [7:0] tmp_12;  /* ufix8 */
  logic [23:0] p88tmp_and_temp;  /* ufix24 */
  logic s_9;
  logic sel_3;
  logic sel_2_3;
  logic [23:0] y;  /* ufix24 */
  logic [1:0] delayMatch_reg_4;  /* ufix1 [2] */
  logic sel_2_4;
  vector_of_unsigned_logic_8 top_1 [0:2];  /* ufix8 [3] */
  logic [23:0] s_10;  /* ufix24 */
  logic [7:0] tmp_13;  /* ufix8 */
  logic [23:0] p87tmp_and_temp;  /* ufix24 */
  logic s_11;
  logic sel_4;
  logic sel_2_5;
  logic [1:0] delayMatch_reg_5;  /* ufix1 [2] */
  logic sel_2_6;
  vector_of_unsigned_logic_8 top_2 [0:2];  /* ufix8 [3] */
  logic [23:0] y_1;  /* ufix24 */
  logic [7:0] tmp_14;  /* ufix8 */
  logic s_12;
  logic sel_5;
  logic sel_2_7;
  logic [1:0] delayMatch_reg_6;  /* ufix1 [2] */
  logic sel_2_8;
  vector_of_unsigned_logic_8 top_3 [0:2];  /* ufix8 [3] */
  vector_of_unsigned_logic_8 middle [0:2];  /* ufix8 [3] */
  logic [23:0] s_13;  /* ufix24 */
  logic [7:0] tmp_15;  /* ufix8 */
  logic [23:0] p96tmp_and_temp;  /* ufix24 */
  logic s_14;
  logic sel_6;
  logic sel_2_9;
  logic [23:0] y_2;  /* ufix24 */
  logic sel_2_10;
  vector_of_unsigned_logic_8 middle_1 [0:2];  /* ufix8 [3] */
  logic [23:0] s_15;  /* ufix24 */
  logic [7:0] tmp_16;  /* ufix8 */
  logic [23:0] p95tmp_and_temp;  /* ufix24 */
  logic s_16;
  logic sel_7;
  logic sel_2_11;
  logic sel_2_12;
  vector_of_unsigned_logic_8 middle_2 [0:2];  /* ufix8 [3] */
  logic [23:0] y_3;  /* ufix24 */
  logic [7:0] tmp_17;  /* ufix8 */
  logic s_17;
  logic sel_8;
  logic sel_2_13;
  logic sel_2_14;
  vector_of_unsigned_logic_8 middle_3 [0:2];  /* ufix8 [3] */
  vector_of_unsigned_logic_8 middle_4 [0:2];  /* ufix8 [3] */
  vector_of_unsigned_logic_8 delayMatch_reg_7 [0:5];  /* ufix8 [6] */
  vector_of_unsigned_logic_8 pixel_1 [0:2];  /* ufix8 [3] */
  vector_of_unsigned_logic_8 tmp_18 [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_unsigned_logic_8 selector_out [0:2] [0:2];  /* ufix8 [3x3] */
  vector_of_unsigned_logic_8 c164_selector_out [0:8];  /* ufix8 [9] */
  vector_of_unsigned_logic_8 c164 [0:8];  /* ufix8 [9] */
  vector_of_unsigned_logic_8 s_18 [0:2] [0:2];  /* ufix8 [3x3] */
  vector_of_unsigned_logic_8 selector_out_1 [0:2] [0:2];  /* ufix8 [3x3] */
  vector_of_unsigned_logic_8 c163_selector_out [0:8];  /* ufix8 [9] */
  vector_of_unsigned_logic_8 c163 [0:8];  /* ufix8 [9] */
  vector_of_unsigned_logic_8 s_19 [0:2] [0:2];  /* ufix8 [3x3] */
  vector_of_unsigned_logic_8 next_window [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_unsigned_logic_8 c136_next_window [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 c136_tmp_1 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 selector_out_2 [0:2] [0:2];  /* ufix8 [3x3] */
  vector_of_unsigned_logic_8 c162_selector_out [0:8];  /* ufix8 [9] */
  vector_of_unsigned_logic_8 c162 [0:8];  /* ufix8 [9] */
  vector_of_unsigned_logic_8 s_20 [0:2] [0:2];  /* ufix8 [3x3] */
  vector_of_unsigned_logic_8 window [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_signed_logic_3 selector_out_3 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 c358_selector_out [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 selector_out_4 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 c359_selector_out [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 selector_out_5 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 c360_selector_out [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 delayMatch_reg_8 [0:17];  /* sfix3 [18] */
  vector_of_signed_logic_3 c358 [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 s_21 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 delayMatch_reg_9 [0:17];  /* sfix3 [18] */
  vector_of_signed_logic_3 c359 [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 s_22 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 delayMatch_reg_10 [0:17];  /* sfix3 [18] */
  vector_of_signed_logic_3 c360 [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 s_23 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 filter_1 [0:2] [0:2] [0:2];  /* sfix3 [3x3x3] */
  logic [11:0] acc;  /* ufix12 */
  logic [11:0] tmp_19;  /* ufix12 */
  logic [11:0] output_reg_1;  /* ufix12 */
  logic [11:0] tmp_20;  /* ufix12 */
  logic valid_reg;
  logic valid_reg_1;
  logic tmp_21;
  logic valid_reg_2;
  logic tmp_22;
  logic [1:0] delayMatch_reg_11;  /* ufix1 [2] */
  logic tmp_23;
  logic signed [31:0] selector_20_t_0;  /* int32 */
  logic signed [31:0] selector_10_t_0;  /* int32 */
  logic signed [31:0] selector_00_t_0;  /* int32 */
  vector_of_unsigned_logic_8 p15_next_window [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  logic signed [31:0] p15_t_0;  /* int32 */
  logic signed [31:0] p15_t_1;  /* int32 */
  logic signed [31:0] p15_ch;  /* int32 */
  logic signed [31:0] p15_t_2;  /* int32 */
  logic signed [31:0] p15_t_3;  /* int32 */
  logic signed [31:0] p15_t_4;  /* int32 */
  logic signed [31:0] selector_00_t_0_1;  /* int32 */
  logic signed [31:0] selector_10_t_0_1;  /* int32 */
  logic signed [31:0] selector_20_t_0_1;  /* int32 */
  logic signed [31:0] p14_kr;  /* int32 */
  logic signed [31:0] p14_kc;  /* int32 */
  logic signed [31:0] p14_ch;  /* int32 */
  logic [11:0] p14_acc;  /* ufix12 */
  logic [11:0] p14_acc_0;  /* ufix12 */
  logic [11:0] p14_acc_1;  /* ufix12 */
  logic signed [33:0] p14_add_temp;  /* sfix34 */
  vector_of_signed_logic_34 p14_t_0 [0:2] [0:2];  /* sfix34 [3x3] */
  vector_of_signed_logic_9 p14_t_1 [0:2] [0:2];  /* sfix9 [3x3] */
  vector_of_signed_logic_12 p14_mul_temp [0:2] [0:2];  /* sfix12 [3x3] */
  vector_of_signed_logic_34 p14_t_2 [0:2] [0:2];  /* sfix34 [3x3] */


  assign enb = clk_enable;

  always_ff @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        reduced_reg <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          reduced_reg[0] <= reset_1;
          reduced_reg[1] <= reduced_reg[0];
        end
      end
    end

  assign reset_2 = reduced_reg[1];

  assign col = 5'b00000;

  assign col_1 = 5'b00000;

  assign tmp = col_2 + 5'b00001;

  assign tmp_1 = (s == 1'b0 ? tmp :
              col);

  assign tmp_2 = (reset_1 == 1'b0 ? tmp_1 :
              col_1);

  always_ff @(posedge clk or posedge reset)
    begin : col_reg_process
      if (reset == 1'b1) begin
        col_2 <= 5'b00000;
      end
      else begin
        if (enb) begin
          col_2 <= tmp_2;
        end
      end
    end

  assign s = col_2 == 5'b11111;

  assign row = 6'b000000;

  assign tmp_3 = row_1 + 6'b000001;

  assign tmp_4 = (s == 1'b0 ? row_1 :
              tmp_3);

  assign tmp_5 = (reset_1 == 1'b0 ? tmp_4 :
              row);

  always_ff @(posedge clk or posedge reset)
    begin : row_reg_process
      if (reset == 1'b1) begin
        row_1 <= 6'b000000;
      end
      else begin
        if (enb) begin
          row_1 <= tmp_5;
        end
      end
    end

  assign s_1 = (row_1 >= 6'b000010) && (col_2 >= 5'b00010);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= s_1;
          delayMatch_reg[1] <= delayMatch_reg[0];
        end
      end
    end

  assign s_2 = delayMatch_reg[1];

  assign output_reg = 12'b000000000000;

assign tmp_6 = '{default:'0};

  generate
    genvar idx44;
    for(idx44 = 0; idx44 < 3; idx44 = idx44 + 1) begin : c136_tmp_gen2
      genvar idx43;
      for(idx43 = 0; idx43 < 3; idx43 = idx43 + 1) begin : c136_tmp_gen1
        genvar idx42;
        for(idx42 = 0; idx42 < 3; idx42 = idx42 + 1) begin : c136_tmp_gen
          assign c136_tmp[idx42 + (idx43 * 3) + (idx44 * 3 * 3)] = tmp_6[idx42][idx43][idx44];
        end
      end
    end
  endgenerate

  assign stateControl_1 = 1'b1;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_1_process
      if (reset == 1'b1) begin
        delayMatch_reg_1 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_1[0] <= stateControl_1;
          delayMatch_reg_1[1] <= delayMatch_reg_1[0];
        end
      end
    end

  assign stateControl_2 = delayMatch_reg_1[1];

  assign enb_gated = stateControl_2 && clk_enable;

  assign stateControl_4 = 1'b1;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_2_process
      if (reset == 1'b1) begin
        delayMatch_reg_2 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_2[0] <= stateControl_4;
          delayMatch_reg_2[1] <= delayMatch_reg_2[0];
        end
      end
    end

  assign stateControl_5 = delayMatch_reg_2[1];

  assign enb_gated_1 = stateControl_5 && clk_enable;

  assign stateControl_7 = 1'b1;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_3_process
      if (reset == 1'b1) begin
        delayMatch_reg_3 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_3[0] <= stateControl_7;
          delayMatch_reg_3[1] <= delayMatch_reg_3[0];
        end
      end
    end

  assign stateControl_8 = delayMatch_reg_3[1];

  assign enb_gated_2 = stateControl_8 && clk_enable;

  assign top = '{3{8'b00000000}};

  assign s_3 = pixel[0];

  assign s_4 = pixel[1];

  assign a1 = {24'b0, s_4};

  assign s_5 = pixel[2];

  assign a1_1 = {24'b0, s_5};

  assign p80tmp_1 = {24'b0, s_3};
  assign p80tmp_add_temp = (p80tmp_1 + (a1 <<< 32'sd8)) + (a1_1 <<< 32'sd16);
  assign tmp_7 = p80tmp_add_temp[23:0];

  assign tmp_8 = {27'b0, col_2};

  assign indexLogic_fixptsig = tmp_8[4:0];

  assign s_6 = 1'b1;

  assign sel = 1'b0;

  assign sel_2 = (reset_1 == 1'b0 ? s_6 :
              sel);

  assign tmp_9 = {27'b0, col_2};

  assign indexLogic_fixptsig_1 = tmp_9[4:0];

  SimpleDualPortRAM_generic #(.AddrWidth(5),
                              .DataWidth(24)
                              )
                            u_line1_ram_generic (.clk(clk),
                                                 .enb(clk_enable),
                                                 .wr_din(tmp_7),
                                                 .wr_addr(indexLogic_fixptsig),
                                                 .wr_en(sel_2),
                                                 .rd_addr(indexLogic_fixptsig_1),
                                                 .dout(line1)
                                                 );

  assign tmp_10 = {27'b0, col_2};

  assign indexLogic_fixptsig_2 = tmp_10[4:0];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_4_process
      if (reset == 1'b1) begin
        indexLogic_fixptsig_3 <= 5'b00000;
      end
      else begin
        if (enb) begin
          indexLogic_fixptsig_3 <= indexLogic_fixptsig_2;
        end
      end
    end

  assign s_7 = 1'b1;

  assign sel_1 = 1'b0;

  assign sel_2_1 = (reset_1 == 1'b0 ? s_7 :
              sel_1);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_5_process
      if (reset == 1'b1) begin
        sel_2_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          sel_2_2 <= sel_2_1;
        end
      end
    end

  assign tmp_11 = {27'b0, col_2};

  assign indexLogic_fixptsig_4 = tmp_11[4:0];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_6_process
      if (reset == 1'b1) begin
        indexLogic_fixptsig_5 <= 5'b00000;
      end
      else begin
        if (enb) begin
          indexLogic_fixptsig_5 <= indexLogic_fixptsig_4;
        end
      end
    end

  SimpleDualPortRAM_generic #(.AddrWidth(5),
                              .DataWidth(24)
                              )
                            u_line2_ram (.clk(clk),
                                         .enb(clk_enable),
                                         .wr_din(line1),
                                         .wr_addr(indexLogic_fixptsig_3),
                                         .wr_en(sel_2_2),
                                         .rd_addr(indexLogic_fixptsig_5),
                                         .dout(line2)
                                         );

  assign s_8 = 24'b000000000000000011111111;

  assign p88tmp_and_temp = line2 & s_8;
  assign tmp_12 = p88tmp_and_temp[7:0];

  assign s_9 = 1'b1;

  assign sel_3 = 1'b0;

  assign sel_2_3 = (reset_1 == 1'b0 ? s_9 :
              sel_3);

  assign y = line2 >>> 16'd8;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_7_process
      if (reset == 1'b1) begin
        delayMatch_reg_4 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_4[0] <= sel_2_3;
          delayMatch_reg_4[1] <= delayMatch_reg_4[0];
        end
      end
    end

  assign sel_2_4 = delayMatch_reg_4[1];

  always_comb begin
    top_1 = top;
    if (sel_2_4) begin
      top_1[0] = tmp_12;
    end
  end

  assign s_10 = 24'b000000000000000011111111;

  assign p87tmp_and_temp = y & s_10;
  assign tmp_13 = p87tmp_and_temp[7:0];

  assign s_11 = 1'b1;

  assign sel_4 = 1'b0;

  assign sel_2_5 = (reset_1 == 1'b0 ? s_11 :
              sel_4);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_8_process
      if (reset == 1'b1) begin
        delayMatch_reg_5 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_5[0] <= sel_2_5;
          delayMatch_reg_5[1] <= delayMatch_reg_5[0];
        end
      end
    end

  assign sel_2_6 = delayMatch_reg_5[1];

  always_comb begin
    top_2 = top_1;
    if (sel_2_6) begin
      top_2[1] = tmp_13;
    end
  end

  assign y_1 = line2 >>> 16'd16;

  assign tmp_14 = y_1[7:0];

  assign s_12 = 1'b1;

  assign sel_5 = 1'b0;

  assign sel_2_7 = (reset_1 == 1'b0 ? s_12 :
              sel_5);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_9_process
      if (reset == 1'b1) begin
        delayMatch_reg_6 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_6[0] <= sel_2_7;
          delayMatch_reg_6[1] <= delayMatch_reg_6[0];
        end
      end
    end

  assign sel_2_8 = delayMatch_reg_6[1];

  always_comb begin
    top_3 = top_2;
    if (sel_2_8) begin
      top_3[2] = tmp_14;
    end
  end

  assign middle = '{3{8'b00000000}};

  assign s_13 = 24'b000000000000000011111111;

  assign p96tmp_and_temp = line1 & s_13;
  assign tmp_15 = p96tmp_and_temp[7:0];

  assign s_14 = 1'b1;

  assign sel_6 = 1'b0;

  assign sel_2_9 = (reset_1 == 1'b0 ? s_14 :
              sel_6);

  assign y_2 = line1 >>> 16'd8;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_10_process
      if (reset == 1'b1) begin
        sel_2_10 <= 1'b0;
      end
      else begin
        if (enb) begin
          sel_2_10 <= sel_2_9;
        end
      end
    end

  always_comb begin
    middle_1 = middle;
    if (sel_2_10) begin
      middle_1[0] = tmp_15;
    end
  end

  assign s_15 = 24'b000000000000000011111111;

  assign p95tmp_and_temp = y_2 & s_15;
  assign tmp_16 = p95tmp_and_temp[7:0];

  assign s_16 = 1'b1;

  assign sel_7 = 1'b0;

  assign sel_2_11 = (reset_1 == 1'b0 ? s_16 :
              sel_7);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_11_process
      if (reset == 1'b1) begin
        sel_2_12 <= 1'b0;
      end
      else begin
        if (enb) begin
          sel_2_12 <= sel_2_11;
        end
      end
    end

  always_comb begin
    middle_2 = middle_1;
    if (sel_2_12) begin
      middle_2[1] = tmp_16;
    end
  end

  assign y_3 = line1 >>> 16'd16;

  assign tmp_17 = y_3[7:0];

  assign s_17 = 1'b1;

  assign sel_8 = 1'b0;

  assign sel_2_13 = (reset_1 == 1'b0 ? s_17 :
              sel_8);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_12_process
      if (reset == 1'b1) begin
        sel_2_14 <= 1'b0;
      end
      else begin
        if (enb) begin
          sel_2_14 <= sel_2_13;
        end
      end
    end

  always_comb begin
    middle_3 = middle_2;
    if (sel_2_14) begin
      middle_3[2] = tmp_17;
    end
  end

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_13_process
      if (reset == 1'b1) begin
        middle_4 <= '{3{8'b00000000}};
      end
      else begin
        if (enb) begin
          middle_4 <= middle_3;
        end
      end
    end

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_14_process
      if (reset == 1'b1) begin
        delayMatch_reg_7 <= '{6{8'b00000000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_7[32'sd0:32'sd2] <= pixel[32'sd0:32'sd2];
          delayMatch_reg_7[32'sd3:32'sd5] <= delayMatch_reg_7[32'sd0:32'sd2];
        end
      end
    end

  assign pixel_1[32'sd0:32'sd2] = delayMatch_reg_7[32'sd3:32'sd5];


  genvar t_1;
  generate
    for(t_1 = 32'sd0; t_1 <= 32'sd2; t_1 = t_1 + 32'sd1) begin:selector_out_gen
      genvar selector_20_t_0;
      for(selector_20_t_0 = 32'sd0; selector_20_t_0 <= 32'sd2; selector_20_t_0 = selector_20_t_0 + 32'sd1) begin:selector_out_gen_1
        assign selector_out[selector_20_t_0][t_1] = tmp_18[selector_20_t_0][t_1][2];
      end
    end
  endgenerate

  generate
    genvar idx41;
    for(idx41 = 0; idx41 < 3; idx41 = idx41 + 1) begin : c164_selector_out_gen1
      genvar idx40;
      for(idx40 = 0; idx40 < 3; idx40 = idx40 + 1) begin : c164_selector_out_gen
        assign c164_selector_out[idx40 + (idx41 * 3)] = selector_out[idx40][idx41];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : window_reg_process
      if (reset == 1'b1) begin
        c164 <= '{9{8'b00000000}};
      end
      else begin
        if (enb_gated_2) begin
          c164 <= c164_selector_out;
        end
      end
    end

  generate
    genvar idx39;
    for(idx39 = 0; idx39 < 3; idx39 = idx39 + 1) begin : s_18_gen1
      genvar idx38;
      for(idx38 = 0; idx38 < 3; idx38 = idx38 + 1) begin : s_18_gen
        assign s_18[idx38][idx39] = c164[idx38 + (idx39 * 3)];
      end
    end
  endgenerate


  genvar t_11;
  generate
    for(t_11 = 32'sd0; t_11 <= 32'sd2; t_11 = t_11 + 32'sd1) begin:selector_out_1_gen
      genvar selector_10_t_0;
      for(selector_10_t_0 = 32'sd0; selector_10_t_0 <= 32'sd2; selector_10_t_0 = selector_10_t_0 + 32'sd1) begin:selector_out_1_gen_1
        assign selector_out_1[selector_10_t_0][t_11] = tmp_18[selector_10_t_0][t_11][1];
      end
    end
  endgenerate

  generate
    genvar idx37;
    for(idx37 = 0; idx37 < 3; idx37 = idx37 + 1) begin : c163_selector_out_gen1
      genvar idx36;
      for(idx36 = 0; idx36 < 3; idx36 = idx36 + 1) begin : c163_selector_out_gen
        assign c163_selector_out[idx36 + (idx37 * 3)] = selector_out_1[idx36][idx37];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : window_reg_1_process
      if (reset == 1'b1) begin
        c163 <= '{9{8'b00000000}};
      end
      else begin
        if (enb_gated_1) begin
          c163 <= c163_selector_out;
        end
      end
    end

  generate
    genvar idx35;
    for(idx35 = 0; idx35 < 3; idx35 = idx35 + 1) begin : s_19_gen1
      genvar idx34;
      for(idx34 = 0; idx34 < 3; idx34 = idx34 + 1) begin : s_19_gen
        assign s_19[idx34][idx35] = c163[idx34 + (idx35 * 3)];
      end
    end
  endgenerate

  generate
    genvar idx33;
    for(idx33 = 0; idx33 < 3; idx33 = idx33 + 1) begin : c136_next_window_gen2
      genvar idx32;
      for(idx32 = 0; idx32 < 3; idx32 = idx32 + 1) begin : c136_next_window_gen1
        genvar idx31;
        for(idx31 = 0; idx31 < 3; idx31 = idx31 + 1) begin : c136_next_window_gen
          assign c136_next_window[idx31 + (idx32 * 3) + (idx33 * 3 * 3)] = next_window[idx31][idx32][idx33];
        end
      end
    end
  endgenerate

  assign c136_tmp_1 = (reset_2 == 1'b0 ? c136_next_window :
              c136_tmp);

  generate
    genvar idx30;
    for(idx30 = 0; idx30 < 3; idx30 = idx30 + 1) begin : tmp_18_gen2
      genvar idx29;
      for(idx29 = 0; idx29 < 3; idx29 = idx29 + 1) begin : tmp_18_gen1
        genvar idx28;
        for(idx28 = 0; idx28 < 3; idx28 = idx28 + 1) begin : tmp_18_gen
          assign tmp_18[idx28][idx29][idx30] = c136_tmp_1[idx28 + (idx29 * 3) + (idx30 * 3 * 3)];
        end
      end
    end
  endgenerate


  genvar t_12;
  generate
    for(t_12 = 32'sd0; t_12 <= 32'sd2; t_12 = t_12 + 32'sd1) begin:selector_out_2_gen
      genvar selector_00_t_0;
      for(selector_00_t_0 = 32'sd0; selector_00_t_0 <= 32'sd2; selector_00_t_0 = selector_00_t_0 + 32'sd1) begin:selector_out_2_gen_1
        assign selector_out_2[selector_00_t_0][t_12] = tmp_18[selector_00_t_0][t_12][0];
      end
    end
  endgenerate

  generate
    genvar idx27;
    for(idx27 = 0; idx27 < 3; idx27 = idx27 + 1) begin : c162_selector_out_gen1
      genvar idx26;
      for(idx26 = 0; idx26 < 3; idx26 = idx26 + 1) begin : c162_selector_out_gen
        assign c162_selector_out[idx26 + (idx27 * 3)] = selector_out_2[idx26][idx27];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : window_reg_2_process
      if (reset == 1'b1) begin
        c162 <= '{9{8'b00000000}};
      end
      else begin
        if (enb_gated) begin
          c162 <= c162_selector_out;
        end
      end
    end

  generate
    genvar idx25;
    for(idx25 = 0; idx25 < 3; idx25 = idx25 + 1) begin : s_20_gen1
      genvar idx24;
      for(idx24 = 0; idx24 < 3; idx24 = idx24 + 1) begin : s_20_gen
        assign s_20[idx24][idx25] = c162[idx24 + (idx25 * 3)];
      end
    end
  endgenerate

  generate
    genvar idx19;
    for(idx19 = 0; idx19 < 3; idx19 = idx19 + 1) begin : window_gen1
      genvar idx18;
      for(idx18 = 0; idx18 < 3; idx18 = idx18 + 1) begin : window_gen
        assign window[idx18][idx19][0] = s_20[idx18][idx19];
      end
    end
  endgenerate
  generate
    genvar idx21;
    for(idx21 = 0; idx21 < 3; idx21 = idx21 + 1) begin : window_gen3
      genvar idx20;
      for(idx20 = 0; idx20 < 3; idx20 = idx20 + 1) begin : window_gen2
        assign window[idx20][idx21][1] = s_19[idx20][idx21];
      end
    end
  endgenerate
  generate
    genvar idx23;
    for(idx23 = 0; idx23 < 3; idx23 = idx23 + 1) begin : window_gen5
      genvar idx22;
      for(idx22 = 0; idx22 < 3; idx22 = idx22 + 1) begin : window_gen4
        assign window[idx22][idx23][2] = s_18[idx22][idx23];
      end
    end
  endgenerate

  always_comb begin

    for(p15_ch = 32'sd0; p15_ch <= 32'sd2; p15_ch = p15_ch + 32'sd1) begin

      for(p15_t_1 = 32'sd0; p15_t_1 <= 32'sd2; p15_t_1 = p15_t_1 + 32'sd1) begin
        for(p15_t_0 = 32'sd0; p15_t_0 <= 32'sd2; p15_t_0 = p15_t_0 + 32'sd1) begin
          p15_next_window[p15_t_0][p15_t_1][p15_ch] = window[p15_t_0][p15_t_1][p15_ch];
        end
      end
      for(p15_t_4 = 32'sd0; p15_t_4 <= 32'sd1; p15_t_4 = p15_t_4 + 32'sd1) begin
        p15_next_window[0][p15_t_4][p15_ch] = window[0][32'sd1 + p15_t_4][p15_ch];
        p15_next_window[1][p15_t_4][p15_ch] = window[1][32'sd1 + p15_t_4][p15_ch];
        p15_next_window[2][p15_t_4][p15_ch] = window[2][32'sd1 + p15_t_4][p15_ch];
      end

      p15_next_window[0][2][p15_ch] = top_3[p15_ch];
      p15_next_window[1][2][p15_ch] = middle_4[p15_ch];
      p15_next_window[2][2][p15_ch] = pixel_1[p15_ch];

      for(p15_t_3 = 32'sd0; p15_t_3 <= 32'sd2; p15_t_3 = p15_t_3 + 32'sd1) begin
        for(p15_t_2 = 32'sd0; p15_t_2 <= 32'sd2; p15_t_2 = p15_t_2 + 32'sd1) begin
          next_window[p15_t_2][p15_t_3][p15_ch] = p15_next_window[p15_t_2][p15_t_3][p15_ch];
        end
      end

    end

  end


  genvar t_13;
  generate
    for(t_13 = 32'sd0; t_13 <= 32'sd2; t_13 = t_13 + 32'sd1) begin:selector_out_3_gen
      genvar selector_00_t_0_1;
      for(selector_00_t_0_1 = 32'sd0; selector_00_t_0_1 <= 32'sd2; selector_00_t_0_1 = selector_00_t_0_1 + 32'sd1) begin:selector_out_3_gen_1
        assign selector_out_3[selector_00_t_0_1][t_13] = filter[selector_00_t_0_1][t_13][0];
      end
    end
  endgenerate

  generate
    genvar idx17;
    for(idx17 = 0; idx17 < 3; idx17 = idx17 + 1) begin : c358_selector_out_gen1
      genvar idx16;
      for(idx16 = 0; idx16 < 3; idx16 = idx16 + 1) begin : c358_selector_out_gen
        assign c358_selector_out[idx16 + (idx17 * 3)] = selector_out_3[idx16][idx17];
      end
    end
  endgenerate


  genvar t_14;
  generate
    for(t_14 = 32'sd0; t_14 <= 32'sd2; t_14 = t_14 + 32'sd1) begin:selector_out_4_gen
      genvar selector_10_t_0_1;
      for(selector_10_t_0_1 = 32'sd0; selector_10_t_0_1 <= 32'sd2; selector_10_t_0_1 = selector_10_t_0_1 + 32'sd1) begin:selector_out_4_gen_1
        assign selector_out_4[selector_10_t_0_1][t_14] = filter[selector_10_t_0_1][t_14][1];
      end
    end
  endgenerate

  generate
    genvar idx15;
    for(idx15 = 0; idx15 < 3; idx15 = idx15 + 1) begin : c359_selector_out_gen1
      genvar idx14;
      for(idx14 = 0; idx14 < 3; idx14 = idx14 + 1) begin : c359_selector_out_gen
        assign c359_selector_out[idx14 + (idx15 * 3)] = selector_out_4[idx14][idx15];
      end
    end
  endgenerate


  genvar t_15;
  generate
    for(t_15 = 32'sd0; t_15 <= 32'sd2; t_15 = t_15 + 32'sd1) begin:selector_out_5_gen
      genvar selector_20_t_0_1;
      for(selector_20_t_0_1 = 32'sd0; selector_20_t_0_1 <= 32'sd2; selector_20_t_0_1 = selector_20_t_0_1 + 32'sd1) begin:selector_out_5_gen_1
        assign selector_out_5[selector_20_t_0_1][t_15] = filter[selector_20_t_0_1][t_15][2];
      end
    end
  endgenerate

  generate
    genvar idx13;
    for(idx13 = 0; idx13 < 3; idx13 = idx13 + 1) begin : c360_selector_out_gen1
      genvar idx12;
      for(idx12 = 0; idx12 < 3; idx12 = idx12 + 1) begin : c360_selector_out_gen
        assign c360_selector_out[idx12 + (idx13 * 3)] = selector_out_5[idx12][idx13];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_15_process
      if (reset == 1'b1) begin
        delayMatch_reg_8 <= '{18{3'sb000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_8[32'sd0:32'sd8] <= c358_selector_out[32'sd0:32'sd8];
          delayMatch_reg_8[32'sd9:32'sd17] <= delayMatch_reg_8[32'sd0:32'sd8];
        end
      end
    end

  assign c358[32'sd0:32'sd8] = delayMatch_reg_8[32'sd9:32'sd17];

  generate
    genvar idx11;
    for(idx11 = 0; idx11 < 3; idx11 = idx11 + 1) begin : s_21_gen1
      genvar idx10;
      for(idx10 = 0; idx10 < 3; idx10 = idx10 + 1) begin : s_21_gen
        assign s_21[idx10][idx11] = c358[idx10 + (idx11 * 3)];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_16_process
      if (reset == 1'b1) begin
        delayMatch_reg_9 <= '{18{3'sb000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_9[32'sd0:32'sd8] <= c359_selector_out[32'sd0:32'sd8];
          delayMatch_reg_9[32'sd9:32'sd17] <= delayMatch_reg_9[32'sd0:32'sd8];
        end
      end
    end

  assign c359[32'sd0:32'sd8] = delayMatch_reg_9[32'sd9:32'sd17];

  generate
    genvar idx9;
    for(idx9 = 0; idx9 < 3; idx9 = idx9 + 1) begin : s_22_gen1
      genvar idx8;
      for(idx8 = 0; idx8 < 3; idx8 = idx8 + 1) begin : s_22_gen
        assign s_22[idx8][idx9] = c359[idx8 + (idx9 * 3)];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_17_process
      if (reset == 1'b1) begin
        delayMatch_reg_10 <= '{18{3'sb000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_10[32'sd0:32'sd8] <= c360_selector_out[32'sd0:32'sd8];
          delayMatch_reg_10[32'sd9:32'sd17] <= delayMatch_reg_10[32'sd0:32'sd8];
        end
      end
    end

  assign c360[32'sd0:32'sd8] = delayMatch_reg_10[32'sd9:32'sd17];

  generate
    genvar idx7;
    for(idx7 = 0; idx7 < 3; idx7 = idx7 + 1) begin : s_23_gen1
      genvar idx6;
      for(idx6 = 0; idx6 < 3; idx6 = idx6 + 1) begin : s_23_gen
        assign s_23[idx6][idx7] = c360[idx6 + (idx7 * 3)];
      end
    end
  endgenerate

  generate
    genvar idx1;
    for(idx1 = 0; idx1 < 3; idx1 = idx1 + 1) begin : filter_1_gen1
      genvar idx;
      for(idx = 0; idx < 3; idx = idx + 1) begin : filter_1_gen
        assign filter_1[idx][idx1][0] = s_21[idx][idx1];
      end
    end
  endgenerate
  generate
    genvar idx3;
    for(idx3 = 0; idx3 < 3; idx3 = idx3 + 1) begin : filter_1_gen3
      genvar idx2;
      for(idx2 = 0; idx2 < 3; idx2 = idx2 + 1) begin : filter_1_gen2
        assign filter_1[idx2][idx3][1] = s_22[idx2][idx3];
      end
    end
  endgenerate
  generate
    genvar idx5;
    for(idx5 = 0; idx5 < 3; idx5 = idx5 + 1) begin : filter_1_gen5
      genvar idx4;
      for(idx4 = 0; idx4 < 3; idx4 = idx4 + 1) begin : filter_1_gen4
        assign filter_1[idx4][idx5][2] = s_23[idx4][idx5];
      end
    end
  endgenerate

  always_comb begin
    p14_acc_0 = 12'b000000000000;
    p14_acc_1 = 12'b000000000000;
    p14_add_temp = 34'sh000000000;
    p14_acc = 12'b000000000000;

    for(p14_kr = 32'sd0; p14_kr <= 32'sd2; p14_kr = p14_kr + 32'sd1) begin
      p14_acc_0 = p14_acc;

      for(p14_kc = 32'sd0; p14_kc <= 32'sd2; p14_kc = p14_kc + 32'sd1) begin
        p14_acc_1 = p14_acc_0;

        for(p14_ch = 32'sd0; p14_ch <= 32'sd2; p14_ch = p14_ch + 32'sd1) begin
          p14_t_0[p14_kc][p14_ch] = {22'b0, p14_acc_1};
          p14_t_1[p14_kc][p14_ch] = {1'b0, next_window[p14_kr][p14_kc][p14_ch]};
          p14_mul_temp[p14_kc][p14_ch] = p14_t_1[p14_kc][p14_ch] * filter_1[p14_kr][p14_kc][p14_ch];
          p14_t_2[p14_kc][p14_ch] = {{22{p14_mul_temp[p14_kc][p14_ch][11]}}, p14_mul_temp[p14_kc][p14_ch]};
          p14_add_temp = p14_t_0[p14_kc][p14_ch] + p14_t_2[p14_kc][p14_ch];
          p14_acc_1 = p14_add_temp[11:0];
        end

        p14_acc_0 = p14_acc_1;
      end

      p14_acc = p14_acc_0;
    end

    acc = p14_acc;
  end

  assign tmp_19 = (s_2 == 1'b0 ? output_reg :
              acc);

  assign output_reg_1 = 12'b000000000000;

  assign tmp_20 = (reset_2 == 1'b0 ? tmp_19 :
              output_reg_1);

  assign valid_reg = 1'b0;

  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //                                                                          %
  //          Generated by MATLAB 25.1 and Fixed-Point Designer 25.1          %
  //                                                                          %
  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  assign valid_reg_1 = 1'b1;

  assign tmp_21 = (s_1 == 1'b0 ? valid_reg :
              valid_reg_1);

  assign valid_reg_2 = 1'b0;

  assign tmp_22 = (reset_1 == 1'b0 ? tmp_21 :
              valid_reg_2);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_18_process
      if (reset == 1'b1) begin
        delayMatch_reg_11 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_11[0] <= tmp_22;
          delayMatch_reg_11[1] <= delayMatch_reg_11[0];
        end
      end
    end

  assign tmp_23 = delayMatch_reg_11[1];

  assign valid = tmp_23;

  assign ce_out = clk_enable;

  assign output_rsvd = tmp_20;

endmodule  // conv3x3x3_stream_fixpt

