// -------------------------------------------------------------
// 
// File Name: C:\Users\user\Desktop\SHREYASHREE\files\systolic_cnn\matlab\codegen\conv3x3x3_4filters_stream\hdlsrc\conv3x3x3_4filters_stream_fixpt.sv
// Created: 2026-09-17 23:26:55
// 
// Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// output_rsvd                   ce_out        1
// valid                         ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


import conv3x3x3_4filters_stream_fixpt_pkg::* ;

// -------------------------------------------------------------
// 
// Module: conv3x3x3_4filters_stream_fixpt
// Source Path: conv3x3x3_4filters_stream_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module conv3x3x3_4filters_stream_fixpt
          (  input logic clk,
             input logic reset,
             input logic clk_enable,
             input vector_of_unsigned_logic_8 pixel[0:2]  /* ufix8 [3] */,
             input vector_of_signed_logic_3 filter0[0:2] [0:2] [0:2]  /* sfix3 [3x3x3] */,
             input vector_of_signed_logic_3 filter1[0:2] [0:2] [0:2]  /* sfix3 [3x3x3] */,
             input vector_of_signed_logic_3 filter2[0:2] [0:2] [0:2]  /* sfix3 [3x3x3] */,
             input vector_of_signed_logic_3 filter3[0:2] [0:2] [0:2]  /* sfix3 [3x3x3] */,
             input logic reset_1,
             output logic ce_out,
             output vector_of_signed_logic_13 output_rsvd[0:3]  /* sfix13 [4] */,
             output logic valid);


  logic enb;
  logic [1:0] reduced_reg;  /* ufix1 [2] */
  logic reset_2;
  logic [4:0] col;  /* ufix5 */
  logic [4:0] col_1;  /* ufix5 */
  logic [4:0] col_2;  /* ufix5 */
  logic [4:0] tmp;  /* ufix5 */
  logic s;
  logic [4:0] tmp_1;  /* ufix5 */
  logic [4:0] tmp_2;  /* ufix5 */
  logic [4:0] row;  /* ufix5 */
  logic [4:0] row_1;  /* ufix5 */
  logic [4:0] tmp_3;  /* ufix5 */
  logic s_1;
  logic [4:0] tmp_4;  /* ufix5 */
  logic [4:0] tmp_5;  /* ufix5 */
  logic [4:0] tmp_6;  /* ufix5 */
  logic s_2;
  logic [1:0] delayMatch_reg;  /* ufix1 [2] */
  logic s_3;
  vector_of_unsigned_logic_8 tmp_7 [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_unsigned_logic_8 c187_tmp [0:26];  /* ufix8 [27] */
  logic stateControl_1;
  logic [1:0] delayMatch_reg_1;  /* ufix1 [2] */
  logic stateControl_2;
  logic enb_gated;
  logic stateControl_4;
  logic [1:0] delayMatch_reg_2;  /* ufix1 [2] */
  logic stateControl_5;
  logic enb_gated_1;
  logic stateControl_7;
  logic [1:0] delayMatch_reg_3;  /* ufix1 [2] */
  logic stateControl_8;
  logic enb_gated_2;
  vector_of_signed_logic_32 tmp_8 [0:2];  /* int32 [3] */
  logic signed [31:0] tmp_9;  /* int32 */
  vector_of_signed_logic_32 tmp_10 [0:2];  /* int32 [3] */
  vector_of_signed_logic_32 tmp_11 [0:2];  /* int32 [3] */
  logic signed [31:0] tmp_12;  /* int32 */
  vector_of_signed_logic_32 tmp_13 [0:2];  /* int32 [3] */
  logic [7:0] s_4;  /* ufix8 */
  logic [7:0] s_5;  /* ufix8 */
  logic [31:0] a1;  /* uint32 */
  logic [7:0] s_6;  /* ufix8 */
  logic [31:0] a1_1;  /* uint32 */
  logic [23:0] tmp_14;  /* ufix24 */
  logic [31:0] p130tmp_add_temp;  /* uint32 */
  logic [31:0] p130tmp_1;  /* uint32 */
  logic signed [31:0] tmp_15;  /* int32 */
  logic [4:0] indexLogic_fixptsig;  /* ufix5 */
  logic s_7;
  logic sel;
  logic sel_2;
  logic signed [31:0] tmp_16;  /* int32 */
  logic [4:0] indexLogic_fixptsig_1;  /* ufix5 */
  logic [23:0] line1;  /* ufix24 */
  logic signed [31:0] tmp_17;  /* int32 */
  logic [4:0] indexLogic_fixptsig_2;  /* ufix5 */
  logic [4:0] indexLogic_fixptsig_3;  /* ufix5 */
  logic s_8;
  logic sel_1;
  logic sel_2_1;
  logic sel_2_2;
  logic signed [31:0] tmp_18;  /* int32 */
  logic [4:0] indexLogic_fixptsig_4;  /* ufix5 */
  logic [4:0] indexLogic_fixptsig_5;  /* ufix5 */
  logic [23:0] line2;  /* ufix24 */
  logic [23:0] s_9;  /* ufix24 */
  logic [7:0] top_r;  /* ufix8 */
  logic [23:0] p138top_r_and_temp;  /* ufix24 */
  logic s_10;
  logic sel_3;
  logic sel_2_3;
  logic [23:0] y;  /* ufix24 */
  logic [1:0] delayMatch_reg_4;  /* ufix1 [2] */
  logic sel_2_4;
  logic [23:0] s_11;  /* ufix24 */
  logic [7:0] top_g;  /* ufix8 */
  logic [23:0] p137top_g_and_temp;  /* ufix24 */
  logic s_12;
  logic sel_4;
  logic sel_2_5;
  logic [1:0] delayMatch_reg_5;  /* ufix1 [2] */
  logic sel_2_6;
  logic [23:0] y_1;  /* ufix24 */
  logic [7:0] top_b;  /* ufix8 */
  logic s_13;
  logic sel_5;
  logic sel_2_7;
  logic [1:0] delayMatch_reg_6;  /* ufix1 [2] */
  logic sel_2_8;
  logic [23:0] s_14;  /* ufix24 */
  logic [7:0] middle_r;  /* ufix8 */
  logic [23:0] p143middle_r_and_temp;  /* ufix24 */
  logic [7:0] middle_r_1;  /* ufix8 */
  logic s_15;
  logic sel_6;
  logic sel_2_9;
  logic [1:0] delayMatch_reg_7;  /* ufix1 [2] */
  logic sel_2_10;
  logic [23:0] y_2;  /* ufix24 */
  logic [23:0] s_16;  /* ufix24 */
  logic [7:0] middle_g;  /* ufix8 */
  logic [23:0] p146middle_g_and_temp;  /* ufix24 */
  logic [7:0] middle_g_1;  /* ufix8 */
  logic s_17;
  logic sel_7;
  logic sel_2_11;
  logic [1:0] delayMatch_reg_8;  /* ufix1 [2] */
  logic sel_2_12;
  logic [23:0] y_3;  /* ufix24 */
  logic [7:0] middle_b;  /* ufix8 */
  logic [7:0] middle_b_1;  /* ufix8 */
  logic s_18;
  logic sel_8;
  logic sel_2_13;
  logic [1:0] delayMatch_reg_9;  /* ufix1 [2] */
  logic sel_2_14;
  logic [7:0] tmp_19;  /* ufix8 */
  vector_of_unsigned_logic_8 delayMatch_reg_10 [0:1];  /* ufix8 [2] */
  logic [7:0] tmp_20;  /* ufix8 */
  logic s_19;
  logic sel_9;
  logic sel_2_15;
  logic [1:0] delayMatch_reg_11;  /* ufix1 [2] */
  logic sel_2_16;
  logic [7:0] tmp_21;  /* ufix8 */
  vector_of_unsigned_logic_8 delayMatch_reg_12 [0:1];  /* ufix8 [2] */
  logic [7:0] tmp_22;  /* ufix8 */
  logic s_20;
  logic sel_10;
  logic sel_2_17;
  logic [1:0] delayMatch_reg_13;  /* ufix1 [2] */
  logic sel_2_18;
  logic [7:0] tmp_23;  /* ufix8 */
  vector_of_unsigned_logic_8 delayMatch_reg_14 [0:1];  /* ufix8 [2] */
  logic [7:0] tmp_24;  /* ufix8 */
  logic s_21;
  logic sel_11;
  logic sel_2_19;
  logic [1:0] delayMatch_reg_15;  /* ufix1 [2] */
  logic sel_2_20;
  vector_of_unsigned_logic_8 window [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_unsigned_logic_8 tmp_25 [0:2] [0:0] [0:2];  /* ufix8 [3x1x3] */
  vector_of_unsigned_logic_8 window_1 [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_unsigned_logic_8 tmp_26 [0:2] [0:0] [0:2];  /* ufix8 [3x1x3] */
  vector_of_unsigned_logic_8 tmp_27 [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_unsigned_logic_8 selector_out [0:2] [0:2];  /* ufix8 [3x3] */
  vector_of_unsigned_logic_8 c220_selector_out [0:8];  /* ufix8 [9] */
  vector_of_unsigned_logic_8 c220 [0:8];  /* ufix8 [9] */
  vector_of_unsigned_logic_8 s_22 [0:2] [0:2];  /* ufix8 [3x3] */
  vector_of_unsigned_logic_8 selector_out_1 [0:2] [0:2];  /* ufix8 [3x3] */
  vector_of_unsigned_logic_8 c219_selector_out [0:8];  /* ufix8 [9] */
  vector_of_unsigned_logic_8 c219 [0:8];  /* ufix8 [9] */
  vector_of_unsigned_logic_8 s_23 [0:2] [0:2];  /* ufix8 [3x3] */
  vector_of_unsigned_logic_8 window_2 [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_unsigned_logic_8 c187_window [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 c187_tmp_1 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 selector_out_2 [0:2] [0:2];  /* ufix8 [3x3] */
  vector_of_unsigned_logic_8 c218_selector_out [0:8];  /* ufix8 [9] */
  vector_of_unsigned_logic_8 c218 [0:8];  /* ufix8 [9] */
  vector_of_unsigned_logic_8 s_24 [0:2] [0:2];  /* ufix8 [3x3] */
  vector_of_unsigned_logic_8 window_3 [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_unsigned_logic_8 window_4 [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_unsigned_logic_8 window_5 [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_unsigned_logic_8 window_6 [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_unsigned_logic_8 window_7 [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_unsigned_logic_8 window_8 [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_unsigned_logic_8 window_9 [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_unsigned_logic_8 window_10 [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_unsigned_logic_8 window_11 [0:2] [0:2] [0:2];  /* ufix8 [3x3x3] */
  vector_of_signed_logic_3 selector_out_3 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 c517_selector_out [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 selector_out_4 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 c518_selector_out [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 selector_out_5 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 c519_selector_out [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 delayMatch_reg_16 [0:17];  /* sfix3 [18] */
  vector_of_signed_logic_3 c517 [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 s_25 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 delayMatch_reg_17 [0:17];  /* sfix3 [18] */
  vector_of_signed_logic_3 c518 [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 s_26 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 delayMatch_reg_18 [0:17];  /* sfix3 [18] */
  vector_of_signed_logic_3 c519 [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 s_27 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 filter0_1 [0:2] [0:2] [0:2];  /* sfix3 [3x3x3] */
  logic signed [12:0] acc;  /* sfix13 */
  logic sel_12;
  logic s_28;
  logic sel_2_21;
  logic sel_13;
  logic sel_2_22;
  logic [1:0] delayMatch_reg_19;  /* ufix1 [2] */
  logic sel_2_23;
  vector_of_signed_logic_13 output_rsvd_1 [0:3];  /* sfix13 [4] */
  vector_of_signed_logic_3 selector_out_6 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 c530_selector_out [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 selector_out_7 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 c531_selector_out [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 selector_out_8 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 c532_selector_out [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 delayMatch_reg_20 [0:17];  /* sfix3 [18] */
  vector_of_signed_logic_3 c530 [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 s_29 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 delayMatch_reg_21 [0:17];  /* sfix3 [18] */
  vector_of_signed_logic_3 c531 [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 s_30 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 delayMatch_reg_22 [0:17];  /* sfix3 [18] */
  vector_of_signed_logic_3 c532 [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 s_31 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 filter1_1 [0:2] [0:2] [0:2];  /* sfix3 [3x3x3] */
  logic signed [12:0] acc_1;  /* sfix13 */
  logic sel_14;
  logic s_32;
  logic sel_2_24;
  logic sel_15;
  logic sel_2_25;
  logic [1:0] delayMatch_reg_23;  /* ufix1 [2] */
  logic sel_2_26;
  vector_of_signed_logic_3 selector_out_9 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 c543_selector_out [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 selector_out_10 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 c544_selector_out [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 selector_out_11 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 c545_selector_out [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 delayMatch_reg_24 [0:17];  /* sfix3 [18] */
  vector_of_signed_logic_3 c543 [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 s_33 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 delayMatch_reg_25 [0:17];  /* sfix3 [18] */
  vector_of_signed_logic_3 c544 [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 s_34 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 delayMatch_reg_26 [0:17];  /* sfix3 [18] */
  vector_of_signed_logic_3 c545 [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 s_35 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 filter2_1 [0:2] [0:2] [0:2];  /* sfix3 [3x3x3] */
  vector_of_signed_logic_13 output_rsvd_2 [0:3];  /* sfix13 [4] */
  logic signed [12:0] acc_2;  /* sfix13 */
  logic sel_16;
  logic s_36;
  logic sel_2_27;
  logic sel_17;
  logic sel_2_28;
  vector_of_signed_logic_3 selector_out_12 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 c556_selector_out [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 selector_out_13 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 c557_selector_out [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 selector_out_14 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 c558_selector_out [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 delayMatch_reg_27 [0:17];  /* sfix3 [18] */
  vector_of_signed_logic_3 c556 [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 s_37 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 delayMatch_reg_28 [0:17];  /* sfix3 [18] */
  vector_of_signed_logic_3 c557 [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 s_38 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 delayMatch_reg_29 [0:17];  /* sfix3 [18] */
  vector_of_signed_logic_3 c558 [0:8];  /* sfix3 [9] */
  vector_of_signed_logic_3 s_39 [0:2] [0:2];  /* sfix3 [3x3] */
  vector_of_signed_logic_3 filter3_1 [0:2] [0:2] [0:2];  /* sfix3 [3x3x3] */
  logic [1:0] delayMatch_reg_30;  /* ufix1 [2] */
  logic sel_2_29;
  vector_of_signed_logic_13 output_rsvd_3 [0:3];  /* sfix13 [4] */
  logic signed [12:0] acc_3;  /* sfix13 */
  logic sel_18;
  logic s_40;
  logic sel_2_30;
  logic sel_19;
  logic sel_2_31;
  logic [1:0] delayMatch_reg_31;  /* ufix1 [2] */
  logic sel_2_32;
  vector_of_signed_logic_13 output_rsvd_4 [0:3];  /* sfix13 [4] */
  vector_of_signed_logic_13 tmp_28 [0:3];  /* sfix13 [4] */
  vector_of_signed_logic_13 tmp_29 [0:3];  /* sfix13 [4] */
  logic valid_1;
  logic valid_2;
  logic tmp_30;
  logic tmp_31;
  logic [1:0] delayMatch_reg_32;  /* ufix1 [2] */
  logic tmp_32;
  logic signed [31:0] p110tmp_t_0;  /* int32 */
  logic signed [31:0] p105tmp_t_0;  /* int32 */
  logic signed [31:0] p105tmp_t_1;  /* int32 */
  logic signed [31:0] p105tmp_t_2;  /* int32 */
  logic signed [31:0] p105tmp_t_3;  /* int32 */
  logic signed [31:0] selector_20_t_0;  /* int32 */
  logic signed [31:0] selector_10_t_0;  /* int32 */
  logic signed [31:0] selector_00_t_0;  /* int32 */
  logic signed [31:0] p109window_t_0;  /* int32 */
  logic signed [31:0] p109window_t_1;  /* int32 */
  logic signed [31:0] p109window_t_2;  /* int32 */
  logic signed [31:0] p109window_t_3;  /* int32 */
  logic signed [31:0] p111window_t_0;  /* int32 */
  logic signed [31:0] p111window_t_1;  /* int32 */
  logic signed [31:0] selector_00_t_0_1;  /* int32 */
  logic signed [31:0] selector_10_t_0_1;  /* int32 */
  logic signed [31:0] selector_20_t_0_1;  /* int32 */
  logic signed [31:0] p31_kr;  /* int32 */
  logic signed [31:0] p31_kc;  /* int32 */
  logic signed [31:0] p31_ch;  /* int32 */
  logic signed [12:0] p31_acc;  /* sfix13 */
  logic signed [12:0] p31_acc_0;  /* sfix13 */
  logic signed [12:0] p31_acc_1;  /* sfix13 */
  logic signed [10:0] p31_add_cast;  /* sfix11 */
  vector_of_signed_logic_9 p31_t_0 [0:2] [0:2];  /* sfix9 [3x3] */
  vector_of_signed_logic_12 p31_mul_temp [0:2] [0:2];  /* sfix12 [3x3] */
  vector_of_signed_logic_13 p31_t_1 [0:2] [0:2];  /* sfix13 [3x3] */
  logic signed [31:0] selector_00_t_0_2;  /* int32 */
  logic signed [31:0] selector_10_t_0_2;  /* int32 */
  logic signed [31:0] selector_20_t_0_2;  /* int32 */
  logic signed [31:0] p33_kr;  /* int32 */
  logic signed [31:0] p33_kc;  /* int32 */
  logic signed [31:0] p33_ch;  /* int32 */
  logic signed [12:0] p33_acc;  /* sfix13 */
  logic signed [12:0] p33_acc_0;  /* sfix13 */
  logic signed [12:0] p33_acc_1;  /* sfix13 */
  logic signed [10:0] p33_add_cast;  /* sfix11 */
  vector_of_signed_logic_9 p33_t_0 [0:2] [0:2];  /* sfix9 [3x3] */
  vector_of_signed_logic_12 p33_mul_temp [0:2] [0:2];  /* sfix12 [3x3] */
  vector_of_signed_logic_13 p33_t_1 [0:2] [0:2];  /* sfix13 [3x3] */
  logic signed [31:0] selector_00_t_0_3;  /* int32 */
  logic signed [31:0] selector_10_t_0_3;  /* int32 */
  logic signed [31:0] selector_20_t_0_3;  /* int32 */
  logic signed [31:0] p29_kr;  /* int32 */
  logic signed [31:0] p29_kc;  /* int32 */
  logic signed [31:0] p29_ch;  /* int32 */
  logic signed [12:0] p29_acc;  /* sfix13 */
  logic signed [12:0] p29_acc_0;  /* sfix13 */
  logic signed [12:0] p29_acc_1;  /* sfix13 */
  logic signed [10:0] p29_add_cast;  /* sfix11 */
  vector_of_signed_logic_9 p29_t_0 [0:2] [0:2];  /* sfix9 [3x3] */
  vector_of_signed_logic_12 p29_mul_temp [0:2] [0:2];  /* sfix12 [3x3] */
  vector_of_signed_logic_13 p29_t_1 [0:2] [0:2];  /* sfix13 [3x3] */
  logic signed [31:0] selector_00_t_0_4;  /* int32 */
  logic signed [31:0] selector_10_t_0_4;  /* int32 */
  logic signed [31:0] selector_20_t_0_4;  /* int32 */
  logic signed [31:0] p27_kr;  /* int32 */
  logic signed [31:0] p27_kc;  /* int32 */
  logic signed [31:0] p27_ch;  /* int32 */
  logic signed [12:0] p27_acc;  /* sfix13 */
  logic signed [12:0] p27_acc_0;  /* sfix13 */
  logic signed [12:0] p27_acc_1;  /* sfix13 */
  logic signed [10:0] p27_add_cast;  /* sfix11 */
  vector_of_signed_logic_9 p27_t_0 [0:2] [0:2];  /* sfix9 [3x3] */
  vector_of_signed_logic_12 p27_mul_temp [0:2] [0:2];  /* sfix12 [3x3] */
  vector_of_signed_logic_13 p27_t_1 [0:2] [0:2];  /* sfix13 [3x3] */


  assign enb = clk_enable;

  always_ff @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        reduced_reg <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          reduced_reg[0] <= reset_1;
          reduced_reg[1] <= reduced_reg[0];
        end
      end
    end

  assign reset_2 = reduced_reg[1];

  assign col = 5'b00000;

  assign col_1 = 5'b00000;

  assign tmp = col_2 + 5'b00001;

  assign tmp_1 = (s == 1'b0 ? tmp :
              col);

  assign tmp_2 = (reset_1 == 1'b0 ? tmp_1 :
              col_1);

  always_ff @(posedge clk or posedge reset)
    begin : col_reg_process
      if (reset == 1'b1) begin
        col_2 <= 5'b00000;
      end
      else begin
        if (enb) begin
          col_2 <= tmp_2;
        end
      end
    end

  assign s = col_2 == 5'b11111;

  assign row = 5'b00000;

  assign tmp_3 = row_1 + 5'b00001;

  assign s_1 = row_1 < 5'b11111;

  assign tmp_4 = (s_1 == 1'b0 ? row_1 :
              tmp_3);

  assign tmp_5 = (s == 1'b0 ? row_1 :
              tmp_4);

  assign tmp_6 = (reset_1 == 1'b0 ? tmp_5 :
              row);

  always_ff @(posedge clk or posedge reset)
    begin : row_reg_process
      if (reset == 1'b1) begin
        row_1 <= 5'b00000;
      end
      else begin
        if (enb) begin
          row_1 <= tmp_6;
        end
      end
    end

  assign s_2 = (row_1 >= 5'b00010) && (col_2 >= 5'b00010);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= s_2;
          delayMatch_reg[1] <= delayMatch_reg[0];
        end
      end
    end

  assign s_3 = delayMatch_reg[1];

  assign tmp_7 = '{27{'{9{'{3{8'b00000000}}}}}};

  generate
    genvar idx98;
    for(idx98 = 0; idx98 < 3; idx98 = idx98 + 1) begin : c187_tmp_gen2
      genvar idx97;
      for(idx97 = 0; idx97 < 3; idx97 = idx97 + 1) begin : c187_tmp_gen1
        genvar idx96;
        for(idx96 = 0; idx96 < 3; idx96 = idx96 + 1) begin : c187_tmp_gen
          assign c187_tmp[idx96 + (idx97 * 3) + (idx98 * 3 * 3)] = tmp_7[idx96][idx97][idx98];
        end
      end
    end
  endgenerate

  assign stateControl_1 = 1'b1;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_1_process
      if (reset == 1'b1) begin
        delayMatch_reg_1 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_1[0] <= stateControl_1;
          delayMatch_reg_1[1] <= delayMatch_reg_1[0];
        end
      end
    end

  assign stateControl_2 = delayMatch_reg_1[1];

  assign enb_gated = stateControl_2 && clk_enable;

  assign stateControl_4 = 1'b1;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_2_process
      if (reset == 1'b1) begin
        delayMatch_reg_2 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_2[0] <= stateControl_4;
          delayMatch_reg_2[1] <= delayMatch_reg_2[0];
        end
      end
    end

  assign stateControl_5 = delayMatch_reg_2[1];

  assign enb_gated_1 = stateControl_5 && clk_enable;

  assign stateControl_7 = 1'b1;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_3_process
      if (reset == 1'b1) begin
        delayMatch_reg_3 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_3[0] <= stateControl_7;
          delayMatch_reg_3[1] <= delayMatch_reg_3[0];
        end
      end
    end

  assign stateControl_8 = delayMatch_reg_3[1];

  assign enb_gated_2 = stateControl_8 && clk_enable;


  genvar t_0;
  generate
    for(t_0 = 32'sd0; t_0 <= 32'sd2; t_0 = t_0 + 32'sd1) begin:tmp_8_gen
      assign tmp_8[t_0] = t_0;
    end
  endgenerate

  assign tmp_9 = 32'sd1;


  genvar t_01;
  generate
    for(t_01 = 32'sd0; t_01 <= 32'sd2; t_01 = t_01 + 32'sd1) begin:tmp_10_gen
      assign tmp_10[t_01] = t_01;
    end
  endgenerate


  genvar t_02;
  generate
    for(t_02 = 32'sd0; t_02 <= 32'sd2; t_02 = t_02 + 32'sd1) begin:tmp_11_gen
      assign tmp_11[t_02] = t_02;
    end
  endgenerate

  assign tmp_12 = 32'sd0;


  genvar t_03;
  generate
    for(t_03 = 32'sd0; t_03 <= 32'sd2; t_03 = t_03 + 32'sd1) begin:tmp_13_gen
      assign tmp_13[t_03] = t_03;
    end
  endgenerate

  assign s_4 = pixel[0];

  assign s_5 = pixel[1];

  assign a1 = {24'b0, s_5};

  assign s_6 = pixel[2];

  assign a1_1 = {24'b0, s_6};

  assign p130tmp_1 = {24'b0, s_4};
  assign p130tmp_add_temp = (p130tmp_1 + (a1 <<< 32'sd8)) + (a1_1 <<< 32'sd16);
  assign tmp_14 = p130tmp_add_temp[23:0];

  assign tmp_15 = {27'b0, col_2};

  assign indexLogic_fixptsig = tmp_15[4:0];

  assign s_7 = 1'b1;

  assign sel = 1'b0;

  assign sel_2 = (reset_1 == 1'b0 ? s_7 :
              sel);

  assign tmp_16 = {27'b0, col_2};

  assign indexLogic_fixptsig_1 = tmp_16[4:0];

  SimpleDualPortRAM_generic #(.AddrWidth(5),
                              .DataWidth(24)
                              )
                            u_line1_ram_generic (.clk(clk),
                                                 .enb(clk_enable),
                                                 .wr_din(tmp_14),
                                                 .wr_addr(indexLogic_fixptsig),
                                                 .wr_en(sel_2),
                                                 .rd_addr(indexLogic_fixptsig_1),
                                                 .dout(line1)
                                                 );

  assign tmp_17 = {27'b0, col_2};

  assign indexLogic_fixptsig_2 = tmp_17[4:0];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_4_process
      if (reset == 1'b1) begin
        indexLogic_fixptsig_3 <= 5'b00000;
      end
      else begin
        if (enb) begin
          indexLogic_fixptsig_3 <= indexLogic_fixptsig_2;
        end
      end
    end

  assign s_8 = 1'b1;

  assign sel_1 = 1'b0;

  assign sel_2_1 = (reset_1 == 1'b0 ? s_8 :
              sel_1);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_5_process
      if (reset == 1'b1) begin
        sel_2_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          sel_2_2 <= sel_2_1;
        end
      end
    end

  assign tmp_18 = {27'b0, col_2};

  assign indexLogic_fixptsig_4 = tmp_18[4:0];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_6_process
      if (reset == 1'b1) begin
        indexLogic_fixptsig_5 <= 5'b00000;
      end
      else begin
        if (enb) begin
          indexLogic_fixptsig_5 <= indexLogic_fixptsig_4;
        end
      end
    end

  SimpleDualPortRAM_generic #(.AddrWidth(5),
                              .DataWidth(24)
                              )
                            u_line2_ram (.clk(clk),
                                         .enb(clk_enable),
                                         .wr_din(line1),
                                         .wr_addr(indexLogic_fixptsig_3),
                                         .wr_en(sel_2_2),
                                         .rd_addr(indexLogic_fixptsig_5),
                                         .dout(line2)
                                         );

  assign s_9 = 24'b000000000000000011111111;

  assign p138top_r_and_temp = line2 & s_9;
  assign top_r = p138top_r_and_temp[7:0];

  assign s_10 = 1'b1;

  assign sel_3 = 1'b0;

  assign sel_2_3 = (reset_1 == 1'b0 ? s_10 :
              sel_3);

  assign y = line2 >>> 16'd8;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_7_process
      if (reset == 1'b1) begin
        delayMatch_reg_4 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_4[0] <= sel_2_3;
          delayMatch_reg_4[1] <= delayMatch_reg_4[0];
        end
      end
    end

  assign sel_2_4 = delayMatch_reg_4[1];

  assign s_11 = 24'b000000000000000011111111;

  assign p137top_g_and_temp = y & s_11;
  assign top_g = p137top_g_and_temp[7:0];

  assign s_12 = 1'b1;

  assign sel_4 = 1'b0;

  assign sel_2_5 = (reset_1 == 1'b0 ? s_12 :
              sel_4);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_8_process
      if (reset == 1'b1) begin
        delayMatch_reg_5 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_5[0] <= sel_2_5;
          delayMatch_reg_5[1] <= delayMatch_reg_5[0];
        end
      end
    end

  assign sel_2_6 = delayMatch_reg_5[1];

  assign y_1 = line2 >>> 16'd16;

  assign top_b = y_1[7:0];

  assign s_13 = 1'b1;

  assign sel_5 = 1'b0;

  assign sel_2_7 = (reset_1 == 1'b0 ? s_13 :
              sel_5);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_9_process
      if (reset == 1'b1) begin
        delayMatch_reg_6 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_6[0] <= sel_2_7;
          delayMatch_reg_6[1] <= delayMatch_reg_6[0];
        end
      end
    end

  assign sel_2_8 = delayMatch_reg_6[1];

  assign s_14 = 24'b000000000000000011111111;

  assign p143middle_r_and_temp = line1 & s_14;
  assign middle_r = p143middle_r_and_temp[7:0];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_10_process
      if (reset == 1'b1) begin
        middle_r_1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          middle_r_1 <= middle_r;
        end
      end
    end

  assign s_15 = 1'b1;

  assign sel_6 = 1'b0;

  assign sel_2_9 = (reset_1 == 1'b0 ? s_15 :
              sel_6);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_11_process
      if (reset == 1'b1) begin
        delayMatch_reg_7 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_7[0] <= sel_2_9;
          delayMatch_reg_7[1] <= delayMatch_reg_7[0];
        end
      end
    end

  assign sel_2_10 = delayMatch_reg_7[1];

  assign y_2 = line1 >>> 16'd8;

  assign s_16 = 24'b000000000000000011111111;

  assign p146middle_g_and_temp = y_2 & s_16;
  assign middle_g = p146middle_g_and_temp[7:0];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_12_process
      if (reset == 1'b1) begin
        middle_g_1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          middle_g_1 <= middle_g;
        end
      end
    end

  assign s_17 = 1'b1;

  assign sel_7 = 1'b0;

  assign sel_2_11 = (reset_1 == 1'b0 ? s_17 :
              sel_7);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_13_process
      if (reset == 1'b1) begin
        delayMatch_reg_8 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_8[0] <= sel_2_11;
          delayMatch_reg_8[1] <= delayMatch_reg_8[0];
        end
      end
    end

  assign sel_2_12 = delayMatch_reg_8[1];

  assign y_3 = line1 >>> 16'd16;

  assign middle_b = y_3[7:0];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_14_process
      if (reset == 1'b1) begin
        middle_b_1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          middle_b_1 <= middle_b;
        end
      end
    end

  assign s_18 = 1'b1;

  assign sel_8 = 1'b0;

  assign sel_2_13 = (reset_1 == 1'b0 ? s_18 :
              sel_8);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_15_process
      if (reset == 1'b1) begin
        delayMatch_reg_9 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_9[0] <= sel_2_13;
          delayMatch_reg_9[1] <= delayMatch_reg_9[0];
        end
      end
    end

  assign sel_2_14 = delayMatch_reg_9[1];

  assign tmp_19 = pixel[0];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_16_process
      if (reset == 1'b1) begin
        delayMatch_reg_10 <= '{2{8'b00000000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_10[0] <= tmp_19;
          delayMatch_reg_10[1] <= delayMatch_reg_10[0];
        end
      end
    end

  assign tmp_20 = delayMatch_reg_10[1];

  assign s_19 = 1'b1;

  assign sel_9 = 1'b0;

  assign sel_2_15 = (reset_1 == 1'b0 ? s_19 :
              sel_9);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_17_process
      if (reset == 1'b1) begin
        delayMatch_reg_11 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_11[0] <= sel_2_15;
          delayMatch_reg_11[1] <= delayMatch_reg_11[0];
        end
      end
    end

  assign sel_2_16 = delayMatch_reg_11[1];

  assign tmp_21 = pixel[1];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_18_process
      if (reset == 1'b1) begin
        delayMatch_reg_12 <= '{2{8'b00000000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_12[0] <= tmp_21;
          delayMatch_reg_12[1] <= delayMatch_reg_12[0];
        end
      end
    end

  assign tmp_22 = delayMatch_reg_12[1];

  assign s_20 = 1'b1;

  assign sel_10 = 1'b0;

  assign sel_2_17 = (reset_1 == 1'b0 ? s_20 :
              sel_10);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_19_process
      if (reset == 1'b1) begin
        delayMatch_reg_13 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_13[0] <= sel_2_17;
          delayMatch_reg_13[1] <= delayMatch_reg_13[0];
        end
      end
    end

  assign sel_2_18 = delayMatch_reg_13[1];

  assign tmp_23 = pixel[2];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_20_process
      if (reset == 1'b1) begin
        delayMatch_reg_14 <= '{2{8'b00000000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_14[0] <= tmp_23;
          delayMatch_reg_14[1] <= delayMatch_reg_14[0];
        end
      end
    end

  assign tmp_24 = delayMatch_reg_14[1];

  assign s_21 = 1'b1;

  assign sel_11 = 1'b0;

  assign sel_2_19 = (reset_1 == 1'b0 ? s_21 :
              sel_11);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_21_process
      if (reset == 1'b1) begin
        delayMatch_reg_15 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_15[0] <= sel_2_19;
          delayMatch_reg_15[1] <= delayMatch_reg_15[0];
        end
      end
    end

  assign sel_2_20 = delayMatch_reg_15[1];


  genvar t_1;
  generate
    for(t_1 = 32'sd0; t_1 <= 32'sd2; t_1 = t_1 + 32'sd1) begin:tmp_25_gen
      genvar p110tmp_t_0;
      for(p110tmp_t_0 = 32'sd0; p110tmp_t_0 <= 32'sd2; p110tmp_t_0 = p110tmp_t_0 + 32'sd1) begin:tmp_25_gen_1
        assign tmp_25[p110tmp_t_0][0][t_1] = window[p110tmp_t_0][2][t_1];
      end
    end
  endgenerate

  always_comb begin
    p105tmp_t_2 = 32'sd0;
    p105tmp_t_3 = 32'sd0;

    for(p105tmp_t_1 = 32'sd0; p105tmp_t_1 <= 32'sd2; p105tmp_t_1 = p105tmp_t_1 + 32'sd1) begin
      for(p105tmp_t_0 = 32'sd0; p105tmp_t_0 <= 32'sd2; p105tmp_t_0 = p105tmp_t_0 + 32'sd1) begin
        p105tmp_t_2 = tmp_8[p105tmp_t_0];
        p105tmp_t_3 = tmp_10[p105tmp_t_1];
        tmp_26[p105tmp_t_0][0][p105tmp_t_1] = window_1[p105tmp_t_2][tmp_9][p105tmp_t_3];
      end
    end

  end


  genvar t_11;
  generate
    for(t_11 = 32'sd0; t_11 <= 32'sd2; t_11 = t_11 + 32'sd1) begin:selector_out_gen
      genvar selector_20_t_0;
      for(selector_20_t_0 = 32'sd0; selector_20_t_0 <= 32'sd2; selector_20_t_0 = selector_20_t_0 + 32'sd1) begin:selector_out_gen_1
        assign selector_out[selector_20_t_0][t_11] = tmp_27[selector_20_t_0][t_11][2];
      end
    end
  endgenerate

  generate
    genvar idx95;
    for(idx95 = 0; idx95 < 3; idx95 = idx95 + 1) begin : c220_selector_out_gen1
      genvar idx94;
      for(idx94 = 0; idx94 < 3; idx94 = idx94 + 1) begin : c220_selector_out_gen
        assign c220_selector_out[idx94 + (idx95 * 3)] = selector_out[idx94][idx95];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : window_reg_process
      if (reset == 1'b1) begin
        c220 <= '{9{8'b00000000}};
      end
      else begin
        if (enb_gated_2) begin
          c220 <= c220_selector_out;
        end
      end
    end

  generate
    genvar idx93;
    for(idx93 = 0; idx93 < 3; idx93 = idx93 + 1) begin : s_22_gen1
      genvar idx92;
      for(idx92 = 0; idx92 < 3; idx92 = idx92 + 1) begin : s_22_gen
        assign s_22[idx92][idx93] = c220[idx92 + (idx93 * 3)];
      end
    end
  endgenerate


  genvar t_12;
  generate
    for(t_12 = 32'sd0; t_12 <= 32'sd2; t_12 = t_12 + 32'sd1) begin:selector_out_1_gen
      genvar selector_10_t_0;
      for(selector_10_t_0 = 32'sd0; selector_10_t_0 <= 32'sd2; selector_10_t_0 = selector_10_t_0 + 32'sd1) begin:selector_out_1_gen_1
        assign selector_out_1[selector_10_t_0][t_12] = tmp_27[selector_10_t_0][t_12][1];
      end
    end
  endgenerate

  generate
    genvar idx91;
    for(idx91 = 0; idx91 < 3; idx91 = idx91 + 1) begin : c219_selector_out_gen1
      genvar idx90;
      for(idx90 = 0; idx90 < 3; idx90 = idx90 + 1) begin : c219_selector_out_gen
        assign c219_selector_out[idx90 + (idx91 * 3)] = selector_out_1[idx90][idx91];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : window_reg_1_process
      if (reset == 1'b1) begin
        c219 <= '{9{8'b00000000}};
      end
      else begin
        if (enb_gated_1) begin
          c219 <= c219_selector_out;
        end
      end
    end

  generate
    genvar idx89;
    for(idx89 = 0; idx89 < 3; idx89 = idx89 + 1) begin : s_23_gen1
      genvar idx88;
      for(idx88 = 0; idx88 < 3; idx88 = idx88 + 1) begin : s_23_gen
        assign s_23[idx88][idx89] = c219[idx88 + (idx89 * 3)];
      end
    end
  endgenerate

  generate
    genvar idx87;
    for(idx87 = 0; idx87 < 3; idx87 = idx87 + 1) begin : c187_window_gen2
      genvar idx86;
      for(idx86 = 0; idx86 < 3; idx86 = idx86 + 1) begin : c187_window_gen1
        genvar idx85;
        for(idx85 = 0; idx85 < 3; idx85 = idx85 + 1) begin : c187_window_gen
          assign c187_window[idx85 + (idx86 * 3) + (idx87 * 3 * 3)] = window_2[idx85][idx86][idx87];
        end
      end
    end
  endgenerate

  assign c187_tmp_1 = (reset_2 == 1'b0 ? c187_window :
              c187_tmp);

  generate
    genvar idx84;
    for(idx84 = 0; idx84 < 3; idx84 = idx84 + 1) begin : tmp_27_gen2
      genvar idx83;
      for(idx83 = 0; idx83 < 3; idx83 = idx83 + 1) begin : tmp_27_gen1
        genvar idx82;
        for(idx82 = 0; idx82 < 3; idx82 = idx82 + 1) begin : tmp_27_gen
          assign tmp_27[idx82][idx83][idx84] = c187_tmp_1[idx82 + (idx83 * 3) + (idx84 * 3 * 3)];
        end
      end
    end
  endgenerate


  genvar t_13;
  generate
    for(t_13 = 32'sd0; t_13 <= 32'sd2; t_13 = t_13 + 32'sd1) begin:selector_out_2_gen
      genvar selector_00_t_0;
      for(selector_00_t_0 = 32'sd0; selector_00_t_0 <= 32'sd2; selector_00_t_0 = selector_00_t_0 + 32'sd1) begin:selector_out_2_gen_1
        assign selector_out_2[selector_00_t_0][t_13] = tmp_27[selector_00_t_0][t_13][0];
      end
    end
  endgenerate

  generate
    genvar idx81;
    for(idx81 = 0; idx81 < 3; idx81 = idx81 + 1) begin : c218_selector_out_gen1
      genvar idx80;
      for(idx80 = 0; idx80 < 3; idx80 = idx80 + 1) begin : c218_selector_out_gen
        assign c218_selector_out[idx80 + (idx81 * 3)] = selector_out_2[idx80][idx81];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : window_reg_2_process
      if (reset == 1'b1) begin
        c218 <= '{9{8'b00000000}};
      end
      else begin
        if (enb_gated) begin
          c218 <= c218_selector_out;
        end
      end
    end

  generate
    genvar idx79;
    for(idx79 = 0; idx79 < 3; idx79 = idx79 + 1) begin : s_24_gen1
      genvar idx78;
      for(idx78 = 0; idx78 < 3; idx78 = idx78 + 1) begin : s_24_gen
        assign s_24[idx78][idx79] = c218[idx78 + (idx79 * 3)];
      end
    end
  endgenerate

  generate
    genvar idx73;
    for(idx73 = 0; idx73 < 3; idx73 = idx73 + 1) begin : window_1_gen1
      genvar idx72;
      for(idx72 = 0; idx72 < 3; idx72 = idx72 + 1) begin : window_1_gen
        assign window_1[idx72][idx73][0] = s_24[idx72][idx73];
      end
    end
  endgenerate
  generate
    genvar idx75;
    for(idx75 = 0; idx75 < 3; idx75 = idx75 + 1) begin : window_1_gen3
      genvar idx74;
      for(idx74 = 0; idx74 < 3; idx74 = idx74 + 1) begin : window_1_gen2
        assign window_1[idx74][idx75][1] = s_23[idx74][idx75];
      end
    end
  endgenerate
  generate
    genvar idx77;
    for(idx77 = 0; idx77 < 3; idx77 = idx77 + 1) begin : window_1_gen5
      genvar idx76;
      for(idx76 = 0; idx76 < 3; idx76 = idx76 + 1) begin : window_1_gen4
        assign window_1[idx76][idx77][2] = s_22[idx76][idx77];
      end
    end
  endgenerate

  always_comb begin
    p109window_t_2 = 32'sd0;
    p109window_t_3 = 32'sd0;
    window = window_1;

    for(p109window_t_1 = 32'sd0; p109window_t_1 <= 32'sd2; p109window_t_1 = p109window_t_1 + 32'sd1) begin
      for(p109window_t_0 = 32'sd0; p109window_t_0 <= 32'sd2; p109window_t_0 = p109window_t_0 + 32'sd1) begin
        p109window_t_2 = tmp_11[p109window_t_0];
        p109window_t_3 = tmp_13[p109window_t_1];
        window[p109window_t_2][tmp_12][p109window_t_3] = tmp_26[p109window_t_0][0][p109window_t_1];
      end
    end

  end

  always_comb begin
    window_3 = window;

    for(p111window_t_1 = 32'sd0; p111window_t_1 <= 32'sd2; p111window_t_1 = p111window_t_1 + 32'sd1) begin
      for(p111window_t_0 = 32'sd0; p111window_t_0 <= 32'sd2; p111window_t_0 = p111window_t_0 + 32'sd1) begin
        window_3[p111window_t_0][1][p111window_t_1] = tmp_25[p111window_t_0][0][p111window_t_1];
      end
    end

  end

  always_comb begin
    window_4 = window_3;
    if (sel_2_4) begin
      window_4[0][2][0] = top_r;
    end
  end

  always_comb begin
    window_5 = window_4;
    if (sel_2_6) begin
      window_5[0][2][1] = top_g;
    end
  end

  always_comb begin
    window_6 = window_5;
    if (sel_2_8) begin
      window_6[0][2][2] = top_b;
    end
  end

  always_comb begin
    window_7 = window_6;
    if (sel_2_10) begin
      window_7[1][2][0] = middle_r_1;
    end
  end

  always_comb begin
    window_8 = window_7;
    if (sel_2_12) begin
      window_8[1][2][1] = middle_g_1;
    end
  end

  always_comb begin
    window_9 = window_8;
    if (sel_2_14) begin
      window_9[1][2][2] = middle_b_1;
    end
  end

  always_comb begin
    window_10 = window_9;
    if (sel_2_16) begin
      window_10[2][2][0] = tmp_20;
    end
  end

  always_comb begin
    window_11 = window_10;
    if (sel_2_18) begin
      window_11[2][2][1] = tmp_22;
    end
  end

  always_comb begin
    window_2 = window_11;
    if (sel_2_20) begin
      window_2[2][2][2] = tmp_24;
    end
  end


  genvar t_14;
  generate
    for(t_14 = 32'sd0; t_14 <= 32'sd2; t_14 = t_14 + 32'sd1) begin:selector_out_3_gen
      genvar selector_00_t_0_1;
      for(selector_00_t_0_1 = 32'sd0; selector_00_t_0_1 <= 32'sd2; selector_00_t_0_1 = selector_00_t_0_1 + 32'sd1) begin:selector_out_3_gen_1
        assign selector_out_3[selector_00_t_0_1][t_14] = filter0[selector_00_t_0_1][t_14][0];
      end
    end
  endgenerate

  generate
    genvar idx71;
    for(idx71 = 0; idx71 < 3; idx71 = idx71 + 1) begin : c517_selector_out_gen1
      genvar idx70;
      for(idx70 = 0; idx70 < 3; idx70 = idx70 + 1) begin : c517_selector_out_gen
        assign c517_selector_out[idx70 + (idx71 * 3)] = selector_out_3[idx70][idx71];
      end
    end
  endgenerate


  genvar t_15;
  generate
    for(t_15 = 32'sd0; t_15 <= 32'sd2; t_15 = t_15 + 32'sd1) begin:selector_out_4_gen
      genvar selector_10_t_0_1;
      for(selector_10_t_0_1 = 32'sd0; selector_10_t_0_1 <= 32'sd2; selector_10_t_0_1 = selector_10_t_0_1 + 32'sd1) begin:selector_out_4_gen_1
        assign selector_out_4[selector_10_t_0_1][t_15] = filter0[selector_10_t_0_1][t_15][1];
      end
    end
  endgenerate

  generate
    genvar idx69;
    for(idx69 = 0; idx69 < 3; idx69 = idx69 + 1) begin : c518_selector_out_gen1
      genvar idx68;
      for(idx68 = 0; idx68 < 3; idx68 = idx68 + 1) begin : c518_selector_out_gen
        assign c518_selector_out[idx68 + (idx69 * 3)] = selector_out_4[idx68][idx69];
      end
    end
  endgenerate


  genvar t_16;
  generate
    for(t_16 = 32'sd0; t_16 <= 32'sd2; t_16 = t_16 + 32'sd1) begin:selector_out_5_gen
      genvar selector_20_t_0_1;
      for(selector_20_t_0_1 = 32'sd0; selector_20_t_0_1 <= 32'sd2; selector_20_t_0_1 = selector_20_t_0_1 + 32'sd1) begin:selector_out_5_gen_1
        assign selector_out_5[selector_20_t_0_1][t_16] = filter0[selector_20_t_0_1][t_16][2];
      end
    end
  endgenerate

  generate
    genvar idx67;
    for(idx67 = 0; idx67 < 3; idx67 = idx67 + 1) begin : c519_selector_out_gen1
      genvar idx66;
      for(idx66 = 0; idx66 < 3; idx66 = idx66 + 1) begin : c519_selector_out_gen
        assign c519_selector_out[idx66 + (idx67 * 3)] = selector_out_5[idx66][idx67];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_22_process
      if (reset == 1'b1) begin
        delayMatch_reg_16 <= '{18{3'sb000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_16[32'sd0:32'sd8] <= c517_selector_out[32'sd0:32'sd8];
          delayMatch_reg_16[32'sd9:32'sd17] <= delayMatch_reg_16[32'sd0:32'sd8];
        end
      end
    end

  assign c517[32'sd0:32'sd8] = delayMatch_reg_16[32'sd9:32'sd17];

  generate
    genvar idx65;
    for(idx65 = 0; idx65 < 3; idx65 = idx65 + 1) begin : s_25_gen1
      genvar idx64;
      for(idx64 = 0; idx64 < 3; idx64 = idx64 + 1) begin : s_25_gen
        assign s_25[idx64][idx65] = c517[idx64 + (idx65 * 3)];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_23_process
      if (reset == 1'b1) begin
        delayMatch_reg_17 <= '{18{3'sb000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_17[32'sd0:32'sd8] <= c518_selector_out[32'sd0:32'sd8];
          delayMatch_reg_17[32'sd9:32'sd17] <= delayMatch_reg_17[32'sd0:32'sd8];
        end
      end
    end

  assign c518[32'sd0:32'sd8] = delayMatch_reg_17[32'sd9:32'sd17];

  generate
    genvar idx63;
    for(idx63 = 0; idx63 < 3; idx63 = idx63 + 1) begin : s_26_gen1
      genvar idx62;
      for(idx62 = 0; idx62 < 3; idx62 = idx62 + 1) begin : s_26_gen
        assign s_26[idx62][idx63] = c518[idx62 + (idx63 * 3)];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_24_process
      if (reset == 1'b1) begin
        delayMatch_reg_18 <= '{18{3'sb000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_18[32'sd0:32'sd8] <= c519_selector_out[32'sd0:32'sd8];
          delayMatch_reg_18[32'sd9:32'sd17] <= delayMatch_reg_18[32'sd0:32'sd8];
        end
      end
    end

  assign c519[32'sd0:32'sd8] = delayMatch_reg_18[32'sd9:32'sd17];

  generate
    genvar idx61;
    for(idx61 = 0; idx61 < 3; idx61 = idx61 + 1) begin : s_27_gen1
      genvar idx60;
      for(idx60 = 0; idx60 < 3; idx60 = idx60 + 1) begin : s_27_gen
        assign s_27[idx60][idx61] = c519[idx60 + (idx61 * 3)];
      end
    end
  endgenerate

  generate
    genvar idx55;
    for(idx55 = 0; idx55 < 3; idx55 = idx55 + 1) begin : filter0_1_gen1
      genvar idx54;
      for(idx54 = 0; idx54 < 3; idx54 = idx54 + 1) begin : filter0_1_gen
        assign filter0_1[idx54][idx55][0] = s_25[idx54][idx55];
      end
    end
  endgenerate
  generate
    genvar idx57;
    for(idx57 = 0; idx57 < 3; idx57 = idx57 + 1) begin : filter0_1_gen3
      genvar idx56;
      for(idx56 = 0; idx56 < 3; idx56 = idx56 + 1) begin : filter0_1_gen2
        assign filter0_1[idx56][idx57][1] = s_26[idx56][idx57];
      end
    end
  endgenerate
  generate
    genvar idx59;
    for(idx59 = 0; idx59 < 3; idx59 = idx59 + 1) begin : filter0_1_gen5
      genvar idx58;
      for(idx58 = 0; idx58 < 3; idx58 = idx58 + 1) begin : filter0_1_gen4
        assign filter0_1[idx58][idx59][2] = s_27[idx58][idx59];
      end
    end
  endgenerate

  always_comb begin
    p31_acc_0 = 13'sb0000000000000;
    p31_acc_1 = 13'sb0000000000000;
    p31_add_cast = 11'sb00000000000;
    p31_acc = 13'sb0000000000000;

    for(p31_kr = 32'sd0; p31_kr <= 32'sd2; p31_kr = p31_kr + 32'sd1) begin
      p31_acc_0 = p31_acc;

      for(p31_kc = 32'sd0; p31_kc <= 32'sd2; p31_kc = p31_kc + 32'sd1) begin
        p31_acc_1 = p31_acc_0;

        for(p31_ch = 32'sd0; p31_ch <= 32'sd2; p31_ch = p31_ch + 32'sd1) begin
          p31_t_0[p31_kc][p31_ch] = {1'b0, window_2[p31_kr][p31_kc][p31_ch]};
          p31_mul_temp[p31_kc][p31_ch] = p31_t_0[p31_kc][p31_ch] * filter0_1[p31_kr][p31_kc][p31_ch];
          p31_add_cast = p31_mul_temp[p31_kc][p31_ch][10:0];
          p31_t_1[p31_kc][p31_ch] = {{2{p31_add_cast[10]}}, p31_add_cast};
          p31_acc_1 = p31_acc_1 + p31_t_1[p31_kc][p31_ch];
        end

        p31_acc_0 = p31_acc_1;
      end

      p31_acc = p31_acc_0;
    end

    acc = p31_acc;
  end

  assign sel_12 = 1'b0;

  assign s_28 = 1'b1;

  assign sel_2_21 = (s_2 == 1'b0 ? sel_12 :
              s_28);

  assign sel_13 = 1'b0;

  assign sel_2_22 = (reset_1 == 1'b0 ? sel_2_21 :
              sel_13);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_25_process
      if (reset == 1'b1) begin
        delayMatch_reg_19 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_19[0] <= sel_2_22;
          delayMatch_reg_19[1] <= delayMatch_reg_19[0];
        end
      end
    end

  assign sel_2_23 = delayMatch_reg_19[1];

  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //                                                                          %
  //          Generated by MATLAB 25.1 and Fixed-Point Designer 25.1          %
  //                                                                          %
  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  always_comb begin
    output_rsvd_1 = '{4{13'sb0000000000000}};
    if (sel_2_23) begin
      output_rsvd_1[0] = acc;
    end
  end


  genvar t_17;
  generate
    for(t_17 = 32'sd0; t_17 <= 32'sd2; t_17 = t_17 + 32'sd1) begin:selector_out_6_gen
      genvar selector_00_t_0_2;
      for(selector_00_t_0_2 = 32'sd0; selector_00_t_0_2 <= 32'sd2; selector_00_t_0_2 = selector_00_t_0_2 + 32'sd1) begin:selector_out_6_gen_1
        assign selector_out_6[selector_00_t_0_2][t_17] = filter1[selector_00_t_0_2][t_17][0];
      end
    end
  endgenerate

  generate
    genvar idx53;
    for(idx53 = 0; idx53 < 3; idx53 = idx53 + 1) begin : c530_selector_out_gen1
      genvar idx52;
      for(idx52 = 0; idx52 < 3; idx52 = idx52 + 1) begin : c530_selector_out_gen
        assign c530_selector_out[idx52 + (idx53 * 3)] = selector_out_6[idx52][idx53];
      end
    end
  endgenerate


  genvar t_18;
  generate
    for(t_18 = 32'sd0; t_18 <= 32'sd2; t_18 = t_18 + 32'sd1) begin:selector_out_7_gen
      genvar selector_10_t_0_2;
      for(selector_10_t_0_2 = 32'sd0; selector_10_t_0_2 <= 32'sd2; selector_10_t_0_2 = selector_10_t_0_2 + 32'sd1) begin:selector_out_7_gen_1
        assign selector_out_7[selector_10_t_0_2][t_18] = filter1[selector_10_t_0_2][t_18][1];
      end
    end
  endgenerate

  generate
    genvar idx51;
    for(idx51 = 0; idx51 < 3; idx51 = idx51 + 1) begin : c531_selector_out_gen1
      genvar idx50;
      for(idx50 = 0; idx50 < 3; idx50 = idx50 + 1) begin : c531_selector_out_gen
        assign c531_selector_out[idx50 + (idx51 * 3)] = selector_out_7[idx50][idx51];
      end
    end
  endgenerate


  genvar t_19;
  generate
    for(t_19 = 32'sd0; t_19 <= 32'sd2; t_19 = t_19 + 32'sd1) begin:selector_out_8_gen
      genvar selector_20_t_0_2;
      for(selector_20_t_0_2 = 32'sd0; selector_20_t_0_2 <= 32'sd2; selector_20_t_0_2 = selector_20_t_0_2 + 32'sd1) begin:selector_out_8_gen_1
        assign selector_out_8[selector_20_t_0_2][t_19] = filter1[selector_20_t_0_2][t_19][2];
      end
    end
  endgenerate

  generate
    genvar idx49;
    for(idx49 = 0; idx49 < 3; idx49 = idx49 + 1) begin : c532_selector_out_gen1
      genvar idx48;
      for(idx48 = 0; idx48 < 3; idx48 = idx48 + 1) begin : c532_selector_out_gen
        assign c532_selector_out[idx48 + (idx49 * 3)] = selector_out_8[idx48][idx49];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_26_process
      if (reset == 1'b1) begin
        delayMatch_reg_20 <= '{18{3'sb000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_20[32'sd0:32'sd8] <= c530_selector_out[32'sd0:32'sd8];
          delayMatch_reg_20[32'sd9:32'sd17] <= delayMatch_reg_20[32'sd0:32'sd8];
        end
      end
    end

  assign c530[32'sd0:32'sd8] = delayMatch_reg_20[32'sd9:32'sd17];

  generate
    genvar idx47;
    for(idx47 = 0; idx47 < 3; idx47 = idx47 + 1) begin : s_29_gen1
      genvar idx46;
      for(idx46 = 0; idx46 < 3; idx46 = idx46 + 1) begin : s_29_gen
        assign s_29[idx46][idx47] = c530[idx46 + (idx47 * 3)];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_27_process
      if (reset == 1'b1) begin
        delayMatch_reg_21 <= '{18{3'sb000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_21[32'sd0:32'sd8] <= c531_selector_out[32'sd0:32'sd8];
          delayMatch_reg_21[32'sd9:32'sd17] <= delayMatch_reg_21[32'sd0:32'sd8];
        end
      end
    end

  assign c531[32'sd0:32'sd8] = delayMatch_reg_21[32'sd9:32'sd17];

  generate
    genvar idx45;
    for(idx45 = 0; idx45 < 3; idx45 = idx45 + 1) begin : s_30_gen1
      genvar idx44;
      for(idx44 = 0; idx44 < 3; idx44 = idx44 + 1) begin : s_30_gen
        assign s_30[idx44][idx45] = c531[idx44 + (idx45 * 3)];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_28_process
      if (reset == 1'b1) begin
        delayMatch_reg_22 <= '{18{3'sb000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_22[32'sd0:32'sd8] <= c532_selector_out[32'sd0:32'sd8];
          delayMatch_reg_22[32'sd9:32'sd17] <= delayMatch_reg_22[32'sd0:32'sd8];
        end
      end
    end

  assign c532[32'sd0:32'sd8] = delayMatch_reg_22[32'sd9:32'sd17];

  generate
    genvar idx43;
    for(idx43 = 0; idx43 < 3; idx43 = idx43 + 1) begin : s_31_gen1
      genvar idx42;
      for(idx42 = 0; idx42 < 3; idx42 = idx42 + 1) begin : s_31_gen
        assign s_31[idx42][idx43] = c532[idx42 + (idx43 * 3)];
      end
    end
  endgenerate

  generate
    genvar idx37;
    for(idx37 = 0; idx37 < 3; idx37 = idx37 + 1) begin : filter1_1_gen1
      genvar idx36;
      for(idx36 = 0; idx36 < 3; idx36 = idx36 + 1) begin : filter1_1_gen
        assign filter1_1[idx36][idx37][0] = s_29[idx36][idx37];
      end
    end
  endgenerate
  generate
    genvar idx39;
    for(idx39 = 0; idx39 < 3; idx39 = idx39 + 1) begin : filter1_1_gen3
      genvar idx38;
      for(idx38 = 0; idx38 < 3; idx38 = idx38 + 1) begin : filter1_1_gen2
        assign filter1_1[idx38][idx39][1] = s_30[idx38][idx39];
      end
    end
  endgenerate
  generate
    genvar idx41;
    for(idx41 = 0; idx41 < 3; idx41 = idx41 + 1) begin : filter1_1_gen5
      genvar idx40;
      for(idx40 = 0; idx40 < 3; idx40 = idx40 + 1) begin : filter1_1_gen4
        assign filter1_1[idx40][idx41][2] = s_31[idx40][idx41];
      end
    end
  endgenerate

  always_comb begin
    p33_acc_0 = 13'sb0000000000000;
    p33_acc_1 = 13'sb0000000000000;
    p33_add_cast = 11'sb00000000000;
    p33_acc = 13'sb0000000000000;

    for(p33_kr = 32'sd0; p33_kr <= 32'sd2; p33_kr = p33_kr + 32'sd1) begin
      p33_acc_0 = p33_acc;

      for(p33_kc = 32'sd0; p33_kc <= 32'sd2; p33_kc = p33_kc + 32'sd1) begin
        p33_acc_1 = p33_acc_0;

        for(p33_ch = 32'sd0; p33_ch <= 32'sd2; p33_ch = p33_ch + 32'sd1) begin
          p33_t_0[p33_kc][p33_ch] = {1'b0, window_2[p33_kr][p33_kc][p33_ch]};
          p33_mul_temp[p33_kc][p33_ch] = p33_t_0[p33_kc][p33_ch] * filter1_1[p33_kr][p33_kc][p33_ch];
          p33_add_cast = p33_mul_temp[p33_kc][p33_ch][10:0];
          p33_t_1[p33_kc][p33_ch] = {{2{p33_add_cast[10]}}, p33_add_cast};
          p33_acc_1 = p33_acc_1 + p33_t_1[p33_kc][p33_ch];
        end

        p33_acc_0 = p33_acc_1;
      end

      p33_acc = p33_acc_0;
    end

    acc_1 = p33_acc;
  end

  assign sel_14 = 1'b0;

  assign s_32 = 1'b1;

  assign sel_2_24 = (s_2 == 1'b0 ? sel_14 :
              s_32);

  assign sel_15 = 1'b0;

  assign sel_2_25 = (reset_1 == 1'b0 ? sel_2_24 :
              sel_15);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_29_process
      if (reset == 1'b1) begin
        delayMatch_reg_23 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_23[0] <= sel_2_25;
          delayMatch_reg_23[1] <= delayMatch_reg_23[0];
        end
      end
    end

  assign sel_2_26 = delayMatch_reg_23[1];


  genvar t_110;
  generate
    for(t_110 = 32'sd0; t_110 <= 32'sd2; t_110 = t_110 + 32'sd1) begin:selector_out_9_gen
      genvar selector_00_t_0_3;
      for(selector_00_t_0_3 = 32'sd0; selector_00_t_0_3 <= 32'sd2; selector_00_t_0_3 = selector_00_t_0_3 + 32'sd1) begin:selector_out_9_gen_1
        assign selector_out_9[selector_00_t_0_3][t_110] = filter2[selector_00_t_0_3][t_110][0];
      end
    end
  endgenerate

  generate
    genvar idx35;
    for(idx35 = 0; idx35 < 3; idx35 = idx35 + 1) begin : c543_selector_out_gen1
      genvar idx34;
      for(idx34 = 0; idx34 < 3; idx34 = idx34 + 1) begin : c543_selector_out_gen
        assign c543_selector_out[idx34 + (idx35 * 3)] = selector_out_9[idx34][idx35];
      end
    end
  endgenerate


  genvar t_111;
  generate
    for(t_111 = 32'sd0; t_111 <= 32'sd2; t_111 = t_111 + 32'sd1) begin:selector_out_10_gen
      genvar selector_10_t_0_3;
      for(selector_10_t_0_3 = 32'sd0; selector_10_t_0_3 <= 32'sd2; selector_10_t_0_3 = selector_10_t_0_3 + 32'sd1) begin:selector_out_10_gen_1
        assign selector_out_10[selector_10_t_0_3][t_111] = filter2[selector_10_t_0_3][t_111][1];
      end
    end
  endgenerate

  generate
    genvar idx33;
    for(idx33 = 0; idx33 < 3; idx33 = idx33 + 1) begin : c544_selector_out_gen1
      genvar idx32;
      for(idx32 = 0; idx32 < 3; idx32 = idx32 + 1) begin : c544_selector_out_gen
        assign c544_selector_out[idx32 + (idx33 * 3)] = selector_out_10[idx32][idx33];
      end
    end
  endgenerate


  genvar t_112;
  generate
    for(t_112 = 32'sd0; t_112 <= 32'sd2; t_112 = t_112 + 32'sd1) begin:selector_out_11_gen
      genvar selector_20_t_0_3;
      for(selector_20_t_0_3 = 32'sd0; selector_20_t_0_3 <= 32'sd2; selector_20_t_0_3 = selector_20_t_0_3 + 32'sd1) begin:selector_out_11_gen_1
        assign selector_out_11[selector_20_t_0_3][t_112] = filter2[selector_20_t_0_3][t_112][2];
      end
    end
  endgenerate

  generate
    genvar idx31;
    for(idx31 = 0; idx31 < 3; idx31 = idx31 + 1) begin : c545_selector_out_gen1
      genvar idx30;
      for(idx30 = 0; idx30 < 3; idx30 = idx30 + 1) begin : c545_selector_out_gen
        assign c545_selector_out[idx30 + (idx31 * 3)] = selector_out_11[idx30][idx31];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_30_process
      if (reset == 1'b1) begin
        delayMatch_reg_24 <= '{18{3'sb000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_24[32'sd0:32'sd8] <= c543_selector_out[32'sd0:32'sd8];
          delayMatch_reg_24[32'sd9:32'sd17] <= delayMatch_reg_24[32'sd0:32'sd8];
        end
      end
    end

  assign c543[32'sd0:32'sd8] = delayMatch_reg_24[32'sd9:32'sd17];

  generate
    genvar idx29;
    for(idx29 = 0; idx29 < 3; idx29 = idx29 + 1) begin : s_33_gen1
      genvar idx28;
      for(idx28 = 0; idx28 < 3; idx28 = idx28 + 1) begin : s_33_gen
        assign s_33[idx28][idx29] = c543[idx28 + (idx29 * 3)];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_31_process
      if (reset == 1'b1) begin
        delayMatch_reg_25 <= '{18{3'sb000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_25[32'sd0:32'sd8] <= c544_selector_out[32'sd0:32'sd8];
          delayMatch_reg_25[32'sd9:32'sd17] <= delayMatch_reg_25[32'sd0:32'sd8];
        end
      end
    end

  assign c544[32'sd0:32'sd8] = delayMatch_reg_25[32'sd9:32'sd17];

  generate
    genvar idx27;
    for(idx27 = 0; idx27 < 3; idx27 = idx27 + 1) begin : s_34_gen1
      genvar idx26;
      for(idx26 = 0; idx26 < 3; idx26 = idx26 + 1) begin : s_34_gen
        assign s_34[idx26][idx27] = c544[idx26 + (idx27 * 3)];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_32_process
      if (reset == 1'b1) begin
        delayMatch_reg_26 <= '{18{3'sb000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_26[32'sd0:32'sd8] <= c545_selector_out[32'sd0:32'sd8];
          delayMatch_reg_26[32'sd9:32'sd17] <= delayMatch_reg_26[32'sd0:32'sd8];
        end
      end
    end

  assign c545[32'sd0:32'sd8] = delayMatch_reg_26[32'sd9:32'sd17];

  generate
    genvar idx25;
    for(idx25 = 0; idx25 < 3; idx25 = idx25 + 1) begin : s_35_gen1
      genvar idx24;
      for(idx24 = 0; idx24 < 3; idx24 = idx24 + 1) begin : s_35_gen
        assign s_35[idx24][idx25] = c545[idx24 + (idx25 * 3)];
      end
    end
  endgenerate

  generate
    genvar idx19;
    for(idx19 = 0; idx19 < 3; idx19 = idx19 + 1) begin : filter2_1_gen1
      genvar idx18;
      for(idx18 = 0; idx18 < 3; idx18 = idx18 + 1) begin : filter2_1_gen
        assign filter2_1[idx18][idx19][0] = s_33[idx18][idx19];
      end
    end
  endgenerate
  generate
    genvar idx21;
    for(idx21 = 0; idx21 < 3; idx21 = idx21 + 1) begin : filter2_1_gen3
      genvar idx20;
      for(idx20 = 0; idx20 < 3; idx20 = idx20 + 1) begin : filter2_1_gen2
        assign filter2_1[idx20][idx21][1] = s_34[idx20][idx21];
      end
    end
  endgenerate
  generate
    genvar idx23;
    for(idx23 = 0; idx23 < 3; idx23 = idx23 + 1) begin : filter2_1_gen5
      genvar idx22;
      for(idx22 = 0; idx22 < 3; idx22 = idx22 + 1) begin : filter2_1_gen4
        assign filter2_1[idx22][idx23][2] = s_35[idx22][idx23];
      end
    end
  endgenerate

  always_comb begin
    output_rsvd_2 = output_rsvd_1;
    if (sel_2_26) begin
      output_rsvd_2[1] = acc_1;
    end
  end

  always_comb begin
    p29_acc_0 = 13'sb0000000000000;
    p29_acc_1 = 13'sb0000000000000;
    p29_add_cast = 11'sb00000000000;
    p29_acc = 13'sb0000000000000;

    for(p29_kr = 32'sd0; p29_kr <= 32'sd2; p29_kr = p29_kr + 32'sd1) begin
      p29_acc_0 = p29_acc;

      for(p29_kc = 32'sd0; p29_kc <= 32'sd2; p29_kc = p29_kc + 32'sd1) begin
        p29_acc_1 = p29_acc_0;

        for(p29_ch = 32'sd0; p29_ch <= 32'sd2; p29_ch = p29_ch + 32'sd1) begin
          p29_t_0[p29_kc][p29_ch] = {1'b0, window_2[p29_kr][p29_kc][p29_ch]};
          p29_mul_temp[p29_kc][p29_ch] = p29_t_0[p29_kc][p29_ch] * filter2_1[p29_kr][p29_kc][p29_ch];
          p29_add_cast = p29_mul_temp[p29_kc][p29_ch][10:0];
          p29_t_1[p29_kc][p29_ch] = {{2{p29_add_cast[10]}}, p29_add_cast};
          p29_acc_1 = p29_acc_1 + p29_t_1[p29_kc][p29_ch];
        end

        p29_acc_0 = p29_acc_1;
      end

      p29_acc = p29_acc_0;
    end

    acc_2 = p29_acc;
  end

  assign sel_16 = 1'b0;

  assign s_36 = 1'b1;

  assign sel_2_27 = (s_2 == 1'b0 ? sel_16 :
              s_36);

  assign sel_17 = 1'b0;

  assign sel_2_28 = (reset_1 == 1'b0 ? sel_2_27 :
              sel_17);


  genvar t_113;
  generate
    for(t_113 = 32'sd0; t_113 <= 32'sd2; t_113 = t_113 + 32'sd1) begin:selector_out_12_gen
      genvar selector_00_t_0_4;
      for(selector_00_t_0_4 = 32'sd0; selector_00_t_0_4 <= 32'sd2; selector_00_t_0_4 = selector_00_t_0_4 + 32'sd1) begin:selector_out_12_gen_1
        assign selector_out_12[selector_00_t_0_4][t_113] = filter3[selector_00_t_0_4][t_113][0];
      end
    end
  endgenerate

  generate
    genvar idx17;
    for(idx17 = 0; idx17 < 3; idx17 = idx17 + 1) begin : c556_selector_out_gen1
      genvar idx16;
      for(idx16 = 0; idx16 < 3; idx16 = idx16 + 1) begin : c556_selector_out_gen
        assign c556_selector_out[idx16 + (idx17 * 3)] = selector_out_12[idx16][idx17];
      end
    end
  endgenerate


  genvar t_114;
  generate
    for(t_114 = 32'sd0; t_114 <= 32'sd2; t_114 = t_114 + 32'sd1) begin:selector_out_13_gen
      genvar selector_10_t_0_4;
      for(selector_10_t_0_4 = 32'sd0; selector_10_t_0_4 <= 32'sd2; selector_10_t_0_4 = selector_10_t_0_4 + 32'sd1) begin:selector_out_13_gen_1
        assign selector_out_13[selector_10_t_0_4][t_114] = filter3[selector_10_t_0_4][t_114][1];
      end
    end
  endgenerate

  generate
    genvar idx15;
    for(idx15 = 0; idx15 < 3; idx15 = idx15 + 1) begin : c557_selector_out_gen1
      genvar idx14;
      for(idx14 = 0; idx14 < 3; idx14 = idx14 + 1) begin : c557_selector_out_gen
        assign c557_selector_out[idx14 + (idx15 * 3)] = selector_out_13[idx14][idx15];
      end
    end
  endgenerate


  genvar t_115;
  generate
    for(t_115 = 32'sd0; t_115 <= 32'sd2; t_115 = t_115 + 32'sd1) begin:selector_out_14_gen
      genvar selector_20_t_0_4;
      for(selector_20_t_0_4 = 32'sd0; selector_20_t_0_4 <= 32'sd2; selector_20_t_0_4 = selector_20_t_0_4 + 32'sd1) begin:selector_out_14_gen_1
        assign selector_out_14[selector_20_t_0_4][t_115] = filter3[selector_20_t_0_4][t_115][2];
      end
    end
  endgenerate

  generate
    genvar idx13;
    for(idx13 = 0; idx13 < 3; idx13 = idx13 + 1) begin : c558_selector_out_gen1
      genvar idx12;
      for(idx12 = 0; idx12 < 3; idx12 = idx12 + 1) begin : c558_selector_out_gen
        assign c558_selector_out[idx12 + (idx13 * 3)] = selector_out_14[idx12][idx13];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_33_process
      if (reset == 1'b1) begin
        delayMatch_reg_27 <= '{18{3'sb000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_27[32'sd0:32'sd8] <= c556_selector_out[32'sd0:32'sd8];
          delayMatch_reg_27[32'sd9:32'sd17] <= delayMatch_reg_27[32'sd0:32'sd8];
        end
      end
    end

  assign c556[32'sd0:32'sd8] = delayMatch_reg_27[32'sd9:32'sd17];

  generate
    genvar idx11;
    for(idx11 = 0; idx11 < 3; idx11 = idx11 + 1) begin : s_37_gen1
      genvar idx10;
      for(idx10 = 0; idx10 < 3; idx10 = idx10 + 1) begin : s_37_gen
        assign s_37[idx10][idx11] = c556[idx10 + (idx11 * 3)];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_34_process
      if (reset == 1'b1) begin
        delayMatch_reg_28 <= '{18{3'sb000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_28[32'sd0:32'sd8] <= c557_selector_out[32'sd0:32'sd8];
          delayMatch_reg_28[32'sd9:32'sd17] <= delayMatch_reg_28[32'sd0:32'sd8];
        end
      end
    end

  assign c557[32'sd0:32'sd8] = delayMatch_reg_28[32'sd9:32'sd17];

  generate
    genvar idx9;
    for(idx9 = 0; idx9 < 3; idx9 = idx9 + 1) begin : s_38_gen1
      genvar idx8;
      for(idx8 = 0; idx8 < 3; idx8 = idx8 + 1) begin : s_38_gen
        assign s_38[idx8][idx9] = c557[idx8 + (idx9 * 3)];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_35_process
      if (reset == 1'b1) begin
        delayMatch_reg_29 <= '{18{3'sb000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_29[32'sd0:32'sd8] <= c558_selector_out[32'sd0:32'sd8];
          delayMatch_reg_29[32'sd9:32'sd17] <= delayMatch_reg_29[32'sd0:32'sd8];
        end
      end
    end

  assign c558[32'sd0:32'sd8] = delayMatch_reg_29[32'sd9:32'sd17];

  generate
    genvar idx7;
    for(idx7 = 0; idx7 < 3; idx7 = idx7 + 1) begin : s_39_gen1
      genvar idx6;
      for(idx6 = 0; idx6 < 3; idx6 = idx6 + 1) begin : s_39_gen
        assign s_39[idx6][idx7] = c558[idx6 + (idx7 * 3)];
      end
    end
  endgenerate

  generate
    genvar idx1;
    for(idx1 = 0; idx1 < 3; idx1 = idx1 + 1) begin : filter3_1_gen1
      genvar idx;
      for(idx = 0; idx < 3; idx = idx + 1) begin : filter3_1_gen
        assign filter3_1[idx][idx1][0] = s_37[idx][idx1];
      end
    end
  endgenerate
  generate
    genvar idx3;
    for(idx3 = 0; idx3 < 3; idx3 = idx3 + 1) begin : filter3_1_gen3
      genvar idx2;
      for(idx2 = 0; idx2 < 3; idx2 = idx2 + 1) begin : filter3_1_gen2
        assign filter3_1[idx2][idx3][1] = s_38[idx2][idx3];
      end
    end
  endgenerate
  generate
    genvar idx5;
    for(idx5 = 0; idx5 < 3; idx5 = idx5 + 1) begin : filter3_1_gen5
      genvar idx4;
      for(idx4 = 0; idx4 < 3; idx4 = idx4 + 1) begin : filter3_1_gen4
        assign filter3_1[idx4][idx5][2] = s_39[idx4][idx5];
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_36_process
      if (reset == 1'b1) begin
        delayMatch_reg_30 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_30[0] <= sel_2_28;
          delayMatch_reg_30[1] <= delayMatch_reg_30[0];
        end
      end
    end

  assign sel_2_29 = delayMatch_reg_30[1];

  always_comb begin
    output_rsvd_3 = output_rsvd_2;
    if (sel_2_29) begin
      output_rsvd_3[2] = acc_2;
    end
  end

  always_comb begin
    p27_acc_0 = 13'sb0000000000000;
    p27_acc_1 = 13'sb0000000000000;
    p27_add_cast = 11'sb00000000000;
    p27_acc = 13'sb0000000000000;

    for(p27_kr = 32'sd0; p27_kr <= 32'sd2; p27_kr = p27_kr + 32'sd1) begin
      p27_acc_0 = p27_acc;

      for(p27_kc = 32'sd0; p27_kc <= 32'sd2; p27_kc = p27_kc + 32'sd1) begin
        p27_acc_1 = p27_acc_0;

        for(p27_ch = 32'sd0; p27_ch <= 32'sd2; p27_ch = p27_ch + 32'sd1) begin
          p27_t_0[p27_kc][p27_ch] = {1'b0, window_2[p27_kr][p27_kc][p27_ch]};
          p27_mul_temp[p27_kc][p27_ch] = p27_t_0[p27_kc][p27_ch] * filter3_1[p27_kr][p27_kc][p27_ch];
          p27_add_cast = p27_mul_temp[p27_kc][p27_ch][10:0];
          p27_t_1[p27_kc][p27_ch] = {{2{p27_add_cast[10]}}, p27_add_cast};
          p27_acc_1 = p27_acc_1 + p27_t_1[p27_kc][p27_ch];
        end

        p27_acc_0 = p27_acc_1;
      end

      p27_acc = p27_acc_0;
    end

    acc_3 = p27_acc;
  end

  assign sel_18 = 1'b0;

  assign s_40 = 1'b1;

  assign sel_2_30 = (s_2 == 1'b0 ? sel_18 :
              s_40);

  assign sel_19 = 1'b0;

  assign sel_2_31 = (reset_1 == 1'b0 ? sel_2_30 :
              sel_19);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_37_process
      if (reset == 1'b1) begin
        delayMatch_reg_31 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_31[0] <= sel_2_31;
          delayMatch_reg_31[1] <= delayMatch_reg_31[0];
        end
      end
    end

  assign sel_2_32 = delayMatch_reg_31[1];

  always_comb begin
    output_rsvd_4 = output_rsvd_3;
    if (sel_2_32) begin
      output_rsvd_4[3] = acc_3;
    end
  end

  assign tmp_28 = (s_3 == 1'b0 ? output_rsvd_1 :
              output_rsvd_4);

  assign tmp_29 = (reset_2 == 1'b0 ? tmp_28 :
              output_rsvd_1);

  assign output_rsvd = tmp_29;

  assign valid_1 = 1'b0;

  assign valid_2 = 1'b1;

  assign tmp_30 = (s_2 == 1'b0 ? valid_1 :
              valid_2);

  assign tmp_31 = (reset_1 == 1'b0 ? tmp_30 :
              valid_1);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_38_process
      if (reset == 1'b1) begin
        delayMatch_reg_32 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_32[0] <= tmp_31;
          delayMatch_reg_32[1] <= delayMatch_reg_32[0];
        end
      end
    end

  assign tmp_32 = delayMatch_reg_32[1];

  assign valid = tmp_32;

  assign ce_out = clk_enable;

endmodule  // conv3x3x3_4filters_stream_fixpt

