-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\user\Desktop\SHREYASHREE\files\systolic_cnn\matlab\codegen\conv3x3x3_4filters_stream\hdlsrc\conv3x3x3_4filters_stream_fixpt_pkg.vhd
-- Created: 2026-09-18 10:57:09
-- 
-- Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
-- 
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE conv3x3x3_4filters_stream_fixpt_pkg IS
  TYPE vector_of_std_logic_vector8 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(7 DOWNTO 0);
  TYPE matrix3d_of_std_logic_vector3 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>) OF std_logic_vector(2 DOWNTO 0);
  TYPE vector_of_std_logic_vector13 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(12 DOWNTO 0);
  TYPE matrix3d_of_unsigned8 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>) OF unsigned(7 DOWNTO 0);
  TYPE vector_of_signed32 IS ARRAY (NATURAL RANGE <>) OF signed(31 DOWNTO 0);
  TYPE vector_of_unsigned8 IS ARRAY (NATURAL RANGE <>) OF unsigned(7 DOWNTO 0);
  TYPE matrix_of_unsigned8 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF unsigned(7 DOWNTO 0);
  TYPE matrix3d_of_signed3 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>) OF signed(2 DOWNTO 0);
  TYPE matrix_of_signed3 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF signed(2 DOWNTO 0);
  TYPE vector_of_signed3 IS ARRAY (NATURAL RANGE <>) OF signed(2 DOWNTO 0);
  TYPE vector_of_signed13 IS ARRAY (NATURAL RANGE <>) OF signed(12 DOWNTO 0);
END conv3x3x3_4filters_stream_fixpt_pkg;

