// -------------------------------------------------------------
// 
// File Name: C:\Users\user\Desktop\SHREYASHREE\files\systolic_cnn\matlab\codegen\systolic_4x4\hdlsrc\systolic_4x4_fixpt.sv
// Created: 2026-09-18 22:33:26
// 
// Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// output_rsvd                   ce_out        1
// valid                         ce_out        1
// ready                         ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


import systolic_4x4_fixpt_pkg::* ;

// -------------------------------------------------------------
// 
// Module: systolic_4x4_fixpt
// Source Path: systolic_4x4_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module systolic_4x4_fixpt
          (  input logic clk,
             input logic reset,
             input logic clk_enable,
             input vector_of_unsigned_logic_8 pixel[0:2]  /* ufix8 [3] */,
             input vector_of_signed_logic_3 filter0[0:2] [0:2] [0:2]  /* sfix3 [3x3x3] */,
             input vector_of_signed_logic_3 filter1[0:2] [0:2] [0:2]  /* sfix3 [3x3x3] */,
             input vector_of_signed_logic_3 filter2[0:2] [0:2] [0:2]  /* sfix3 [3x3x3] */,
             input vector_of_signed_logic_3 filter3[0:2] [0:2] [0:2]  /* sfix3 [3x3x3] */,
             input logic reset_1,
             output logic ce_out,
             output vector_of_signed_logic_13 output_rsvd[0:3]  /* sfix13 [4] */,
             output logic valid,
             output logic ready);


  logic enb;
  logic [1:0] reduced_reg;  /* ufix1 [2] */
  logic reset_2;
  logic [2:0] cycle;  /* ufix3 */
  logic [4:0] col;  /* ufix5 */
  logic [4:0] col_1;  /* ufix5 */
  logic [4:0] row;  /* ufix5 */
  logic [2:0] cycle_1;  /* ufix3 */
  logic [2:0] cycle_2;  /* ufix3 */
  logic state;  /* ufix1 */
  logic state_1;  /* ufix1 */
  logic state_2;  /* ufix1 */
  logic s;
  logic state_3;  /* ufix1 */
  logic tmp;  /* ufix1 */
  logic [4:0] row_1;  /* ufix5 */
  logic [4:0] tmp_1;  /* ufix5 */
  logic s_1;
  logic [4:0] tmp_2;  /* ufix5 */
  logic [4:0] col_2;  /* ufix5 */
  logic [4:0] tmp_3;  /* ufix5 */
  logic s_2;
  logic [4:0] tmp_4;  /* ufix5 */
  logic s_3;
  logic [4:0] tmp_5;  /* ufix5 */
  logic [4:0] tmp_6;  /* ufix5 */
  logic [4:0] tmp_7;  /* ufix5 */
  logic [4:0] tmp_8;  /* ufix5 */
  logic [4:0] tmp_9;  /* ufix5 */
  logic [2:0] cycle_3;  /* ufix3 */
  logic [2:0] tmp_10;  /* ufix3 */
  logic [2:0] tmp_11;  /* ufix3 */
  logic s_4;
  logic [2:0] tmp_12;  /* ufix3 */
  logic [2:0] tmp_13;  /* ufix3 */
  logic [2:0] tmp_14;  /* ufix3 */
  logic tmp_15;  /* ufix1 */
  logic tmp_16;  /* ufix1 */
  logic tmp_17;  /* ufix1 */
  logic [1:0] reduced_reg_1;  /* ufix1 [2] */
  logic s_5;
  logic [1:0] delayMatch_reg;  /* ufix1 [2] */
  logic s_6;
  logic [1:0] delayMatch_reg_1;  /* ufix1 [2] */
  logic s_7;
  vector_of_signed_logic_13 tmp_18 [0:15];  /* sfix13 [16] */
  vector_of_signed_logic_13 tmp_19 [0:15];  /* sfix13 [16] */
  logic stateControl_1;
  logic [1:0] delayMatch_reg_2;  /* ufix1 [2] */
  logic stateControl_2;
  logic enb_gated;
  vector_of_unsigned_logic_3 delayMatch_reg_3 [0:1];  /* ufix3 [2] */
  logic [2:0] cycle_4;  /* ufix3 */
  vector_of_unsigned_logic_8 new_window [0:26];  /* ufix8 [27] */
  logic signed [31:0] tmp_20;  /* int32 */
  logic sel;
  logic s_8;
  logic sel_2;
  logic sel_1;
  logic sel_2_1;
  logic [1:0] delayMatch_reg_4;  /* ufix1 [2] */
  logic sel_2_2;
  logic signed [31:0] tmp_21;  /* int32 */
  logic sel_3;
  logic s_9;
  logic sel_2_3;
  logic sel_4;
  logic sel_2_4;
  logic [1:0] delayMatch_reg_5;  /* ufix1 [2] */
  logic sel_2_5;
  logic signed [31:0] tmp_22;  /* int32 */
  logic sel_5;
  logic s_10;
  logic sel_2_6;
  logic sel_6;
  logic sel_2_7;
  logic [1:0] delayMatch_reg_6;  /* ufix1 [2] */
  logic sel_2_8;
  logic signed [31:0] tmp_23;  /* int32 */
  logic sel_7;
  logic s_11;
  logic sel_2_9;
  logic sel_8;
  logic sel_2_10;
  logic [1:0] delayMatch_reg_7;  /* ufix1 [2] */
  logic sel_2_11;
  logic signed [31:0] tmp_24;  /* int32 */
  logic sel_9;
  logic s_12;
  logic sel_2_12;
  logic sel_10;
  logic sel_2_13;
  logic [1:0] delayMatch_reg_8;  /* ufix1 [2] */
  logic sel_2_14;
  logic signed [31:0] tmp_25;  /* int32 */
  logic sel_11;
  logic s_13;
  logic sel_2_15;
  logic sel_12;
  logic sel_2_16;
  logic [1:0] delayMatch_reg_9;  /* ufix1 [2] */
  logic sel_2_17;
  logic [7:0] s_14;  /* ufix8 */
  logic [7:0] s_15;  /* ufix8 */
  logic [31:0] a1;  /* uint32 */
  logic [7:0] s_16;  /* ufix8 */
  logic [31:0] a1_1;  /* uint32 */
  logic [23:0] tmp_26;  /* ufix24 */
  logic [31:0] p349tmp_add_temp;  /* uint32 */
  logic [31:0] p349tmp_1;  /* uint32 */
  logic signed [31:0] tmp_27;  /* int32 */
  logic [4:0] indexLogic_fixptsig;  /* ufix5 */
  logic sel_13;
  logic s_17;
  logic sel_2_18;
  logic sel_14;
  logic sel_2_19;
  logic signed [31:0] tmp_28;  /* int32 */
  logic [4:0] indexLogic_fixptsig_1;  /* ufix5 */
  logic [23:0] line1;  /* ufix24 */
  logic signed [31:0] tmp_29;  /* int32 */
  logic [4:0] indexLogic_fixptsig_2;  /* ufix5 */
  logic [4:0] indexLogic_fixptsig_3;  /* ufix5 */
  logic sel_15;
  logic s_18;
  logic sel_2_20;
  logic sel_16;
  logic sel_2_21;
  logic sel_2_22;
  logic signed [31:0] tmp_30;  /* int32 */
  logic [4:0] indexLogic_fixptsig_4;  /* ufix5 */
  logic [4:0] indexLogic_fixptsig_5;  /* ufix5 */
  logic [23:0] line2;  /* ufix24 */
  logic [23:0] s_19;  /* ufix24 */
  logic [7:0] top_r;  /* ufix8 */
  logic [23:0] p369top_r_and_temp;  /* ufix24 */
  logic sel_17;
  logic s_20;
  logic sel_2_23;
  logic sel_18;
  logic sel_2_24;
  logic [23:0] y;  /* ufix24 */
  logic [1:0] delayMatch_reg_10;  /* ufix1 [2] */
  logic sel_2_25;
  logic [23:0] s_21;  /* ufix24 */
  logic [7:0] top_g;  /* ufix8 */
  logic [23:0] p368top_g_and_temp;  /* ufix24 */
  logic sel_19;
  logic s_22;
  logic sel_2_26;
  logic sel_20;
  logic sel_2_27;
  logic [1:0] delayMatch_reg_11;  /* ufix1 [2] */
  logic sel_2_28;
  logic [23:0] y_1;  /* ufix24 */
  logic [7:0] top_b;  /* ufix8 */
  logic sel_21;
  logic s_23;
  logic sel_2_29;
  logic sel_22;
  logic sel_2_30;
  logic [1:0] delayMatch_reg_12;  /* ufix1 [2] */
  logic sel_2_31;
  logic signed [31:0] tmp_31;  /* int32 */
  logic sel_23;
  logic s_24;
  logic sel_2_32;
  logic sel_24;
  logic sel_2_33;
  logic [1:0] delayMatch_reg_13;  /* ufix1 [2] */
  logic sel_2_34;
  logic signed [31:0] tmp_32;  /* int32 */
  logic sel_25;
  logic s_25;
  logic sel_2_35;
  logic sel_26;
  logic sel_2_36;
  logic [1:0] delayMatch_reg_14;  /* ufix1 [2] */
  logic sel_2_37;
  logic signed [31:0] tmp_33;  /* int32 */
  logic sel_27;
  logic s_26;
  logic sel_2_38;
  logic sel_28;
  logic sel_2_39;
  logic [1:0] delayMatch_reg_15;  /* ufix1 [2] */
  logic sel_2_40;
  logic signed [31:0] tmp_34;  /* int32 */
  logic sel_29;
  logic s_27;
  logic sel_2_41;
  logic sel_30;
  logic sel_2_42;
  logic [1:0] delayMatch_reg_16;  /* ufix1 [2] */
  logic sel_2_43;
  logic signed [31:0] tmp_35;  /* int32 */
  logic sel_31;
  logic s_28;
  logic sel_2_44;
  logic sel_32;
  logic sel_2_45;
  logic [1:0] delayMatch_reg_17;  /* ufix1 [2] */
  logic sel_2_46;
  logic signed [31:0] tmp_36;  /* int32 */
  logic sel_33;
  logic s_29;
  logic sel_2_47;
  logic sel_34;
  logic sel_2_48;
  logic [1:0] delayMatch_reg_18;  /* ufix1 [2] */
  logic sel_2_49;
  logic [23:0] s_30;  /* ufix24 */
  logic [7:0] middle_r;  /* ufix8 */
  logic [23:0] p358middle_r_and_temp;  /* ufix24 */
  logic [7:0] middle_r_1;  /* ufix8 */
  logic sel_35;
  logic s_31;
  logic sel_2_50;
  logic sel_36;
  logic sel_2_51;
  logic [1:0] delayMatch_reg_19;  /* ufix1 [2] */
  logic sel_2_52;
  logic [23:0] y_2;  /* ufix24 */
  logic [23:0] s_32;  /* ufix24 */
  logic [7:0] middle_g;  /* ufix8 */
  logic [23:0] p361middle_g_and_temp;  /* ufix24 */
  logic [7:0] middle_g_1;  /* ufix8 */
  logic sel_37;
  logic s_33;
  logic sel_2_53;
  logic sel_38;
  logic sel_2_54;
  logic [1:0] delayMatch_reg_20;  /* ufix1 [2] */
  logic sel_2_55;
  logic [23:0] y_3;  /* ufix24 */
  logic [7:0] middle_b;  /* ufix8 */
  logic [7:0] middle_b_1;  /* ufix8 */
  logic sel_39;
  logic s_34;
  logic sel_2_56;
  logic sel_40;
  logic sel_2_57;
  logic [1:0] delayMatch_reg_21;  /* ufix1 [2] */
  logic sel_2_58;
  logic signed [31:0] tmp_37;  /* int32 */
  logic sel_41;
  logic s_35;
  logic sel_2_59;
  logic sel_42;
  logic sel_2_60;
  logic [1:0] delayMatch_reg_22;  /* ufix1 [2] */
  logic sel_2_61;
  logic signed [31:0] tmp_38;  /* int32 */
  logic sel_43;
  logic s_36;
  logic sel_2_62;
  logic sel_44;
  logic sel_2_63;
  logic [1:0] delayMatch_reg_23;  /* ufix1 [2] */
  logic sel_2_64;
  logic signed [31:0] tmp_39;  /* int32 */
  logic sel_45;
  logic s_37;
  logic sel_2_65;
  logic sel_46;
  logic sel_2_66;
  logic [1:0] delayMatch_reg_24;  /* ufix1 [2] */
  logic sel_2_67;
  logic signed [31:0] tmp_40;  /* int32 */
  logic sel_47;
  logic s_38;
  logic sel_2_68;
  logic sel_48;
  logic sel_2_69;
  logic [1:0] delayMatch_reg_25;  /* ufix1 [2] */
  logic sel_2_70;
  logic signed [31:0] tmp_41;  /* int32 */
  logic sel_49;
  logic s_39;
  logic sel_2_71;
  logic sel_50;
  logic sel_2_72;
  logic [1:0] delayMatch_reg_26;  /* ufix1 [2] */
  logic sel_2_73;
  logic signed [31:0] tmp_42;  /* int32 */
  logic sel_51;
  logic s_40;
  logic sel_2_74;
  logic sel_52;
  logic sel_2_75;
  logic [1:0] delayMatch_reg_27;  /* ufix1 [2] */
  logic sel_2_76;
  logic [7:0] tmp_43;  /* ufix8 */
  vector_of_unsigned_logic_8 delayMatch_reg_28 [0:1];  /* ufix8 [2] */
  logic [7:0] tmp_44;  /* ufix8 */
  logic sel_53;
  logic s_41;
  logic sel_2_77;
  logic sel_54;
  logic sel_2_78;
  logic [1:0] delayMatch_reg_29;  /* ufix1 [2] */
  logic sel_2_79;
  logic [7:0] tmp_45;  /* ufix8 */
  vector_of_unsigned_logic_8 delayMatch_reg_30 [0:1];  /* ufix8 [2] */
  logic [7:0] tmp_46;  /* ufix8 */
  logic sel_55;
  logic s_42;
  logic sel_2_80;
  logic sel_56;
  logic sel_2_81;
  logic [1:0] delayMatch_reg_31;  /* ufix1 [2] */
  logic sel_2_82;
  logic [7:0] tmp_47;  /* ufix8 */
  vector_of_unsigned_logic_8 delayMatch_reg_32 [0:1];  /* ufix8 [2] */
  logic [7:0] tmp_48;  /* ufix8 */
  logic sel_57;
  logic s_43;
  logic sel_2_83;
  logic sel_58;
  logic sel_2_84;
  logic [1:0] delayMatch_reg_33;  /* ufix1 [2] */
  logic sel_2_85;
  vector_of_unsigned_logic_8 tmp_49 [0:26];  /* ufix8 [27] */
  logic stateControl_4;
  logic [1:0] delayMatch_reg_34;  /* ufix1 [2] */
  logic stateControl_5;
  logic enb_gated_1;
  vector_of_unsigned_logic_8 window [0:26];  /* ufix8 [27] */
  logic [7:0] tmp_50;  /* ufix8 */
  logic [7:0] tmp_51;  /* ufix8 */
  logic [7:0] tmp_52;  /* ufix8 */
  logic [7:0] tmp_53;  /* ufix8 */
  logic [7:0] tmp_54;  /* ufix8 */
  logic [7:0] tmp_55;  /* ufix8 */
  logic [7:0] tmp_56;  /* ufix8 */
  logic [7:0] tmp_57;  /* ufix8 */
  logic [7:0] tmp_58;  /* ufix8 */
  logic [7:0] tmp_59;  /* ufix8 */
  logic [7:0] tmp_60;  /* ufix8 */
  logic [7:0] tmp_61;  /* ufix8 */
  logic [7:0] tmp_62;  /* ufix8 */
  logic [7:0] tmp_63;  /* ufix8 */
  logic [7:0] tmp_64;  /* ufix8 */
  logic [7:0] tmp_65;  /* ufix8 */
  logic [7:0] tmp_66;  /* ufix8 */
  logic [7:0] tmp_67;  /* ufix8 */
  vector_of_unsigned_logic_8 new_window_1 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_2 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_3 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_4 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_5 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_6 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_7 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_8 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_9 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_10 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_11 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_12 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_13 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_14 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_15 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_16 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_17 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_18 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_19 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_20 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_21 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_22 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_23 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_24 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_25 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_26 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 new_window_27 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 tmp_68 [0:26];  /* ufix8 [27] */
  vector_of_unsigned_logic_8 tmp_69 [0:26];  /* ufix8 [27] */
  logic [4:0] p;  /* ufix5 */
  vector_of_signed_logic_3 tmp_70 [0:107];  /* sfix3 [108] */
  vector_of_signed_logic_3 weights [0:107];  /* sfix3 [108] */
  vector_of_signed_logic_3 weights_1 [0:107];  /* sfix3 [108] */
  vector_of_signed_logic_3 tmp_71 [0:107];  /* sfix3 [108] */
  vector_of_signed_logic_3 tmp_72 [0:107];  /* sfix3 [108] */
  vector_of_signed_logic_3 tmp_73 [0:107];  /* sfix3 [108] */
  vector_of_signed_logic_3 delayMatch_reg_35 [0:215];  /* sfix3 [216] */
  vector_of_signed_logic_3 weights_2 [0:107];  /* sfix3 [108] */
  vector_of_signed_logic_13 pe_acc [0:15];  /* sfix13 [16] */
  vector_of_signed_logic_13 tmp_74 [0:15];  /* sfix13 [16] */
  vector_of_signed_logic_13 next_acc [0:15];  /* sfix13 [16] */
  vector_of_signed_logic_13 tmp_75 [0:15];  /* sfix13 [16] */
  vector_of_signed_logic_13 tmp_76 [0:15];  /* sfix13 [16] */
  logic signed [12:0] next_acc_1;  /* sfix13 */
  logic signed [12:0] next_acc_2;  /* sfix13 */
  logic signed [12:0] next_acc_3;  /* sfix13 */
  logic signed [12:0] next_acc_4;  /* sfix13 */
  logic signed [12:0] tmp_77;  /* sfix13 */
  logic signed [13:0] p353tmp_add_temp;  /* sfix14 */
  logic signed [14:0] p353tmp_add_temp_1;  /* sfix15 */
  logic signed [15:0] p353tmp_add_temp_2;  /* sfix16 */
  logic signed [13:0] p353tmp_1;  /* sfix14 */
  logic signed [13:0] p353tmp_2;  /* sfix14 */
  logic signed [14:0] p353tmp_3;  /* sfix15 */
  logic signed [14:0] p353tmp_4;  /* sfix15 */
  logic signed [15:0] p353tmp_5;  /* sfix16 */
  logic signed [15:0] p353tmp_6;  /* sfix16 */
  logic sel_59;
  logic s_44;
  logic sel_2_86;
  logic sel_60;
  logic sel_2_87;
  logic sel_61;
  logic sel_2_88;
  logic [1:0] delayMatch_reg_36;  /* ufix1 [2] */
  logic sel_2_89;
  vector_of_signed_logic_13 output_rsvd_1 [0:3];  /* sfix13 [4] */
  logic signed [12:0] next_acc_5;  /* sfix13 */
  logic signed [12:0] next_acc_6;  /* sfix13 */
  logic signed [12:0] next_acc_7;  /* sfix13 */
  logic signed [12:0] next_acc_8;  /* sfix13 */
  logic signed [12:0] tmp_78;  /* sfix13 */
  logic signed [13:0] p351tmp_add_temp;  /* sfix14 */
  logic signed [14:0] p351tmp_add_temp_1;  /* sfix15 */
  logic signed [15:0] p351tmp_add_temp_2;  /* sfix16 */
  logic signed [13:0] p351tmp_1;  /* sfix14 */
  logic signed [13:0] p351tmp_2;  /* sfix14 */
  logic signed [14:0] p351tmp_3;  /* sfix15 */
  logic signed [14:0] p351tmp_4;  /* sfix15 */
  logic signed [15:0] p351tmp_5;  /* sfix16 */
  logic signed [15:0] p351tmp_6;  /* sfix16 */
  logic sel_62;
  logic s_45;
  logic sel_2_90;
  logic sel_63;
  logic sel_2_91;
  logic sel_64;
  logic sel_2_92;
  logic [1:0] delayMatch_reg_37;  /* ufix1 [2] */
  logic sel_2_93;
  logic signed [12:0] next_acc_9;  /* sfix13 */
  logic signed [12:0] next_acc_10;  /* sfix13 */
  logic signed [12:0] next_acc_11;  /* sfix13 */
  vector_of_signed_logic_13 output_rsvd_2 [0:3];  /* sfix13 [4] */
  logic signed [12:0] next_acc_12;  /* sfix13 */
  logic signed [12:0] tmp_79;  /* sfix13 */
  logic signed [13:0] p352tmp_add_temp;  /* sfix14 */
  logic signed [14:0] p352tmp_add_temp_1;  /* sfix15 */
  logic signed [15:0] p352tmp_add_temp_2;  /* sfix16 */
  logic signed [13:0] p352tmp_1;  /* sfix14 */
  logic signed [13:0] p352tmp_2;  /* sfix14 */
  logic signed [14:0] p352tmp_3;  /* sfix15 */
  logic signed [14:0] p352tmp_4;  /* sfix15 */
  logic signed [15:0] p352tmp_5;  /* sfix16 */
  logic signed [15:0] p352tmp_6;  /* sfix16 */
  logic sel_65;
  logic s_46;
  logic sel_2_94;
  logic sel_66;
  logic sel_2_95;
  logic sel_67;
  logic sel_2_96;
  logic signed [12:0] next_acc_13;  /* sfix13 */
  logic signed [12:0] next_acc_14;  /* sfix13 */
  logic signed [12:0] next_acc_15;  /* sfix13 */
  logic [1:0] delayMatch_reg_38;  /* ufix1 [2] */
  logic sel_2_97;
  vector_of_signed_logic_13 output_rsvd_3 [0:3];  /* sfix13 [4] */
  logic signed [12:0] next_acc_16;  /* sfix13 */
  logic signed [12:0] tmp_80;  /* sfix13 */
  logic signed [13:0] p350tmp_add_temp;  /* sfix14 */
  logic signed [14:0] p350tmp_add_temp_1;  /* sfix15 */
  logic signed [15:0] p350tmp_add_temp_2;  /* sfix16 */
  logic signed [13:0] p350tmp_1;  /* sfix14 */
  logic signed [13:0] p350tmp_2;  /* sfix14 */
  logic signed [14:0] p350tmp_3;  /* sfix15 */
  logic signed [14:0] p350tmp_4;  /* sfix15 */
  logic signed [15:0] p350tmp_5;  /* sfix16 */
  logic signed [15:0] p350tmp_6;  /* sfix16 */
  logic sel_68;
  logic s_47;
  logic sel_2_98;
  logic sel_69;
  logic sel_2_99;
  logic sel_70;
  logic sel_2_100;
  logic [1:0] delayMatch_reg_39;  /* ufix1 [2] */
  logic sel_2_101;
  vector_of_signed_logic_13 output_rsvd_4 [0:3];  /* sfix13 [4] */
  vector_of_signed_logic_13 tmp_81 [0:3];  /* sfix13 [4] */
  vector_of_signed_logic_13 tmp_82 [0:3];  /* sfix13 [4] */
  vector_of_signed_logic_13 tmp_83 [0:3];  /* sfix13 [4] */
  logic valid_1;
  logic valid_2;
  logic tmp_84;
  logic tmp_85;
  logic tmp_86;
  logic [1:0] delayMatch_reg_40;  /* ufix1 [2] */
  logic tmp_87;
  logic ready_1;
  logic ready_2;
  logic tmp_88;
  logic ready_3;
  logic tmp_89;
  logic [1:0] delayMatch_reg_41;  /* ufix1 [2] */
  logic tmp_90;
  logic signed [31:0] p249_kr;  /* int32 */
  vector_of_signed_logic_3 p249_weights [0:107];  /* sfix3 [108] */
  logic signed [31:0] p249_kc;  /* int32 */
  logic signed [31:0] p249_ch;  /* int32 */
  logic [4:0] p249_p;  /* ufix5 */
  logic [4:0] p249_p_0;  /* ufix5 */
  logic [4:0] p249_p_1;  /* ufix5 */
  logic [5:0] p249_add_temp;  /* ufix6 */
  logic [6:0] p249_add_temp_0;  /* ufix7 */
  logic [7:0] p249_add_temp_1;  /* ufix8 */
  vector_of_unsigned_logic_6 p249_t_0 [0:2] [0:2];  /* ufix6 [3x3] */
  vector_of_unsigned_logic_7 p249_t_1 [0:2] [0:2];  /* ufix7 [3x3] */
  vector_of_unsigned_logic_8 p249_t_2 [0:2] [0:2];  /* ufix8 [3x3] */
  logic signed [31:0] p250_f_iter;  /* int32 */
  vector_of_signed_logic_13 p250_next_acc [0:15];  /* sfix13 [16] */
  logic signed [31:0] p250_lane_iter;  /* int32 */
  logic [1:0] p250_f;  /* ufix2 */
  logic [1:0] p250_lane;  /* ufix2 */
  logic [4:0] p250_pe;  /* ufix5 */
  logic [4:0] p250_index;  /* ufix5 */
  logic [4:0] p250_add_cast;  /* ufix5 */
  logic [5:0] p250_add_temp;  /* ufix6 */
  logic [6:0] p250_add_temp_0;  /* ufix7 */
  logic [5:0] p250_add_cast_0;  /* ufix6 */
  logic [6:0] p250_add_temp_1;  /* ufix7 */
  logic [7:0] p250_add_temp_2;  /* ufix8 */
  logic [7:0] p250_add_temp_3;  /* ufix8 */
  logic signed [10:0] p250_add_cast_1;  /* sfix11 */
  vector_of_unsigned_logic_6 p250_t_0 [0:3] [0:3];  /* ufix6 [4x4] */
  vector_of_unsigned_logic_6 p250_t_1 [0:3] [0:3];  /* ufix6 [4x4] */
  vector_of_unsigned_logic_7 p250_t_2 [0:3] [0:3];  /* ufix7 [4x4] */
  vector_of_unsigned_logic_7 p250_t_3 [0:3] [0:3];  /* ufix7 [4x4] */
  vector_of_unsigned_logic_7 p250_t_4 [0:3] [0:3];  /* ufix7 [4x4] */
  vector_of_unsigned_logic_8 p250_t_5 [0:3] [0:3];  /* ufix8 [4x4] */
  vector_of_unsigned_logic_7 p250_mul_temp [0:3] [0:3];  /* ufix7 [4x4] */
  vector_of_unsigned_logic_8 p250_t_6 [0:3] [0:3];  /* ufix8 [4x4] */
  vector_of_unsigned_logic_8 p250_t_7 [0:3] [0:3];  /* ufix8 [4x4] */
  vector_of_signed_logic_9 p250_t_8 [0:3] [0:3];  /* sfix9 [4x4] */
  vector_of_signed_logic_12 p250_mul_temp_0 [0:3] [0:3];  /* sfix12 [4x4] */
  vector_of_signed_logic_13 p250_t_9 [0:3] [0:3];  /* sfix13 [4x4] */


  assign enb = clk_enable;

  always_ff @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        reduced_reg <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          reduced_reg[0] <= reset_1;
          reduced_reg[1] <= reduced_reg[0];
        end
      end
    end

  assign reset_2 = reduced_reg[1];

  assign cycle = 3'b000;

  assign col = 5'b00000;

  assign col_1 = 5'b00000;

  assign row = 5'b00000;

  assign cycle_1 = 3'b000;

  assign cycle_2 = 3'b000;

  assign state = 1'b0;

  assign state_1 = 1'b1;

  assign state_2 = 1'b0;

  assign tmp = (s == 1'b0 ? state_3 :
              state_1);

  assign tmp_1 = row_1 + 5'b00001;

  assign s_1 = row_1 < 5'b11111;

  assign tmp_2 = (s_1 == 1'b0 ? row_1 :
              tmp_1);

  assign tmp_3 = col_2 + 5'b00001;

  assign tmp_4 = (s_2 == 1'b0 ? tmp_3 :
              col);

  assign tmp_5 = (s_3 == 1'b0 ? col_2 :
              tmp_4);

  assign tmp_6 = (reset_1 == 1'b0 ? tmp_5 :
              col_1);

  always_ff @(posedge clk or posedge reset)
    begin : col_reg_process
      if (reset == 1'b1) begin
        col_2 <= 5'b00000;
      end
      else begin
        if (enb) begin
          col_2 <= tmp_6;
        end
      end
    end

  assign s_2 = col_2 == 5'b11111;

  assign tmp_7 = (s_2 == 1'b0 ? row_1 :
              tmp_2);

  assign tmp_8 = (s_3 == 1'b0 ? row_1 :
              tmp_7);

  assign tmp_9 = (reset_1 == 1'b0 ? tmp_8 :
              row);

  always_ff @(posedge clk or posedge reset)
    begin : row_reg_process
      if (reset == 1'b1) begin
        row_1 <= 5'b00000;
      end
      else begin
        if (enb) begin
          row_1 <= tmp_9;
        end
      end
    end

  assign s = (row_1 >= 5'b00010) && (col_2 >= 5'b00010);

  assign tmp_10 = (s == 1'b0 ? cycle_3 :
              cycle_1);

  assign tmp_11 = cycle_3 + 3'b001;

  assign tmp_12 = (s_4 == 1'b0 ? tmp_11 :
              cycle);

  assign tmp_13 = (s_3 == 1'b0 ? tmp_12 :
              tmp_10);

  assign tmp_14 = (reset_1 == 1'b0 ? tmp_13 :
              cycle_2);

  always_ff @(posedge clk or posedge reset)
    begin : cycle_reg_process
      if (reset == 1'b1) begin
        cycle_3 <= 3'b000;
      end
      else begin
        if (enb) begin
          cycle_3 <= tmp_14;
        end
      end
    end

  assign s_4 = cycle_3 == 3'b110;

  assign tmp_15 = (s_4 == 1'b0 ? state_3 :
              state);

  assign tmp_16 = (s_3 == 1'b0 ? tmp_15 :
              tmp);

  assign tmp_17 = (reset_1 == 1'b0 ? tmp_16 :
              state_2);

  always_ff @(posedge clk or posedge reset)
    begin : state_reg_process
      if (reset == 1'b1) begin
        state_3 <= 1'b0;
      end
      else begin
        if (enb) begin
          state_3 <= tmp_17;
        end
      end
    end

  assign s_3 = state_3 == 1'b0;

  always_ff @(posedge clk or posedge reset)
    begin : reduced_1_process
      if (reset == 1'b1) begin
        reduced_reg_1 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          reduced_reg_1[0] <= s_3;
          reduced_reg_1[1] <= reduced_reg_1[0];
        end
      end
    end

  assign s_5 = reduced_reg_1[1];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= s_4;
          delayMatch_reg[1] <= delayMatch_reg[0];
        end
      end
    end

  assign s_6 = delayMatch_reg[1];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_1_process
      if (reset == 1'b1) begin
        delayMatch_reg_1 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_1[0] <= s;
          delayMatch_reg_1[1] <= delayMatch_reg_1[0];
        end
      end
    end

  assign s_7 = delayMatch_reg_1[1];

  assign tmp_18 = '{16{13'sb0000000000000}};

  assign tmp_19 = '{16{13'sb0000000000000}};

  assign stateControl_1 = 1'b1;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_2_process
      if (reset == 1'b1) begin
        delayMatch_reg_2 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_2[0] <= stateControl_1;
          delayMatch_reg_2[1] <= delayMatch_reg_2[0];
        end
      end
    end

  assign stateControl_2 = delayMatch_reg_2[1];

  assign enb_gated = stateControl_2 && clk_enable;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_3_process
      if (reset == 1'b1) begin
        delayMatch_reg_3 <= '{2{3'b000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_3[0] <= cycle_3;
          delayMatch_reg_3[1] <= delayMatch_reg_3[0];
        end
      end
    end

  assign cycle_4 = delayMatch_reg_3[1];

  assign new_window = '{27{8'b00000000}};

  assign tmp_20 = 32'sd3;

  assign sel = 1'b0;

  assign s_8 = 1'b1;

  assign sel_2 = (s_3 == 1'b0 ? sel :
              s_8);

  assign sel_1 = 1'b0;

  assign sel_2_1 = (reset_1 == 1'b0 ? sel_2 :
              sel_1);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_4_process
      if (reset == 1'b1) begin
        delayMatch_reg_4 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_4[0] <= sel_2_1;
          delayMatch_reg_4[1] <= delayMatch_reg_4[0];
        end
      end
    end

  assign sel_2_2 = delayMatch_reg_4[1];

  assign tmp_21 = 32'sd4;

  assign sel_3 = 1'b0;

  assign s_9 = 1'b1;

  assign sel_2_3 = (s_3 == 1'b0 ? sel_3 :
              s_9);

  assign sel_4 = 1'b0;

  assign sel_2_4 = (reset_1 == 1'b0 ? sel_2_3 :
              sel_4);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_5_process
      if (reset == 1'b1) begin
        delayMatch_reg_5 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_5[0] <= sel_2_4;
          delayMatch_reg_5[1] <= delayMatch_reg_5[0];
        end
      end
    end

  assign sel_2_5 = delayMatch_reg_5[1];

  assign tmp_22 = 32'sd5;

  assign sel_5 = 1'b0;

  assign s_10 = 1'b1;

  assign sel_2_6 = (s_3 == 1'b0 ? sel_5 :
              s_10);

  assign sel_6 = 1'b0;

  assign sel_2_7 = (reset_1 == 1'b0 ? sel_2_6 :
              sel_6);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_6_process
      if (reset == 1'b1) begin
        delayMatch_reg_6 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_6[0] <= sel_2_7;
          delayMatch_reg_6[1] <= delayMatch_reg_6[0];
        end
      end
    end

  assign sel_2_8 = delayMatch_reg_6[1];

  assign tmp_23 = 32'sd6;

  assign sel_7 = 1'b0;

  assign s_11 = 1'b1;

  assign sel_2_9 = (s_3 == 1'b0 ? sel_7 :
              s_11);

  assign sel_8 = 1'b0;

  assign sel_2_10 = (reset_1 == 1'b0 ? sel_2_9 :
              sel_8);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_7_process
      if (reset == 1'b1) begin
        delayMatch_reg_7 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_7[0] <= sel_2_10;
          delayMatch_reg_7[1] <= delayMatch_reg_7[0];
        end
      end
    end

  assign sel_2_11 = delayMatch_reg_7[1];

  assign tmp_24 = 32'sd7;

  assign sel_9 = 1'b0;

  assign s_12 = 1'b1;

  assign sel_2_12 = (s_3 == 1'b0 ? sel_9 :
              s_12);

  assign sel_10 = 1'b0;

  assign sel_2_13 = (reset_1 == 1'b0 ? sel_2_12 :
              sel_10);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_8_process
      if (reset == 1'b1) begin
        delayMatch_reg_8 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_8[0] <= sel_2_13;
          delayMatch_reg_8[1] <= delayMatch_reg_8[0];
        end
      end
    end

  assign sel_2_14 = delayMatch_reg_8[1];

  assign tmp_25 = 32'sd8;

  assign sel_11 = 1'b0;

  assign s_13 = 1'b1;

  assign sel_2_15 = (s_3 == 1'b0 ? sel_11 :
              s_13);

  assign sel_12 = 1'b0;

  assign sel_2_16 = (reset_1 == 1'b0 ? sel_2_15 :
              sel_12);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_9_process
      if (reset == 1'b1) begin
        delayMatch_reg_9 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_9[0] <= sel_2_16;
          delayMatch_reg_9[1] <= delayMatch_reg_9[0];
        end
      end
    end

  assign sel_2_17 = delayMatch_reg_9[1];

  assign s_14 = pixel[0];

  assign s_15 = pixel[1];

  assign a1 = {24'b0, s_15};

  assign s_16 = pixel[2];

  assign a1_1 = {24'b0, s_16};

  assign p349tmp_1 = {24'b0, s_14};
  assign p349tmp_add_temp = (p349tmp_1 + (a1 <<< 32'sd8)) + (a1_1 <<< 32'sd16);
  assign tmp_26 = p349tmp_add_temp[23:0];

  assign tmp_27 = {27'b0, col_2};

  assign indexLogic_fixptsig = tmp_27[4:0];

  assign sel_13 = 1'b0;

  assign s_17 = 1'b1;

  assign sel_2_18 = (s_3 == 1'b0 ? sel_13 :
              s_17);

  assign sel_14 = 1'b0;

  assign sel_2_19 = (reset_1 == 1'b0 ? sel_2_18 :
              sel_14);

  assign tmp_28 = {27'b0, col_2};

  assign indexLogic_fixptsig_1 = tmp_28[4:0];

  SimpleDualPortRAM_generic #(.AddrWidth(5),
                              .DataWidth(24)
                              )
                            u_line1_ram_generic (.clk(clk),
                                                 .enb(clk_enable),
                                                 .wr_din(tmp_26),
                                                 .wr_addr(indexLogic_fixptsig),
                                                 .wr_en(sel_2_19),
                                                 .rd_addr(indexLogic_fixptsig_1),
                                                 .dout(line1)
                                                 );

  assign tmp_29 = {27'b0, col_2};

  assign indexLogic_fixptsig_2 = tmp_29[4:0];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_10_process
      if (reset == 1'b1) begin
        indexLogic_fixptsig_3 <= 5'b00000;
      end
      else begin
        if (enb) begin
          indexLogic_fixptsig_3 <= indexLogic_fixptsig_2;
        end
      end
    end

  assign sel_15 = 1'b0;

  assign s_18 = 1'b1;

  assign sel_2_20 = (s_3 == 1'b0 ? sel_15 :
              s_18);

  assign sel_16 = 1'b0;

  assign sel_2_21 = (reset_1 == 1'b0 ? sel_2_20 :
              sel_16);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_11_process
      if (reset == 1'b1) begin
        sel_2_22 <= 1'b0;
      end
      else begin
        if (enb) begin
          sel_2_22 <= sel_2_21;
        end
      end
    end

  assign tmp_30 = {27'b0, col_2};

  assign indexLogic_fixptsig_4 = tmp_30[4:0];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_12_process
      if (reset == 1'b1) begin
        indexLogic_fixptsig_5 <= 5'b00000;
      end
      else begin
        if (enb) begin
          indexLogic_fixptsig_5 <= indexLogic_fixptsig_4;
        end
      end
    end

  SimpleDualPortRAM_generic #(.AddrWidth(5),
                              .DataWidth(24)
                              )
                            u_line2_ram (.clk(clk),
                                         .enb(clk_enable),
                                         .wr_din(line1),
                                         .wr_addr(indexLogic_fixptsig_3),
                                         .wr_en(sel_2_22),
                                         .rd_addr(indexLogic_fixptsig_5),
                                         .dout(line2)
                                         );

  assign s_19 = 24'b000000000000000011111111;

  assign p369top_r_and_temp = line2 & s_19;
  assign top_r = p369top_r_and_temp[7:0];

  assign sel_17 = 1'b0;

  assign s_20 = 1'b1;

  assign sel_2_23 = (s_3 == 1'b0 ? sel_17 :
              s_20);

  assign sel_18 = 1'b0;

  assign sel_2_24 = (reset_1 == 1'b0 ? sel_2_23 :
              sel_18);

  assign y = line2 >>> 16'd8;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_13_process
      if (reset == 1'b1) begin
        delayMatch_reg_10 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_10[0] <= sel_2_24;
          delayMatch_reg_10[1] <= delayMatch_reg_10[0];
        end
      end
    end

  assign sel_2_25 = delayMatch_reg_10[1];

  assign s_21 = 24'b000000000000000011111111;

  assign p368top_g_and_temp = y & s_21;
  assign top_g = p368top_g_and_temp[7:0];

  assign sel_19 = 1'b0;

  assign s_22 = 1'b1;

  assign sel_2_26 = (s_3 == 1'b0 ? sel_19 :
              s_22);

  assign sel_20 = 1'b0;

  assign sel_2_27 = (reset_1 == 1'b0 ? sel_2_26 :
              sel_20);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_14_process
      if (reset == 1'b1) begin
        delayMatch_reg_11 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_11[0] <= sel_2_27;
          delayMatch_reg_11[1] <= delayMatch_reg_11[0];
        end
      end
    end

  assign sel_2_28 = delayMatch_reg_11[1];

  assign y_1 = line2 >>> 16'd16;

  assign top_b = y_1[7:0];

  assign sel_21 = 1'b0;

  assign s_23 = 1'b1;

  assign sel_2_29 = (s_3 == 1'b0 ? sel_21 :
              s_23);

  assign sel_22 = 1'b0;

  assign sel_2_30 = (reset_1 == 1'b0 ? sel_2_29 :
              sel_22);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_15_process
      if (reset == 1'b1) begin
        delayMatch_reg_12 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_12[0] <= sel_2_30;
          delayMatch_reg_12[1] <= delayMatch_reg_12[0];
        end
      end
    end

  assign sel_2_31 = delayMatch_reg_12[1];

  assign tmp_31 = 32'sd12;

  assign sel_23 = 1'b0;

  assign s_24 = 1'b1;

  assign sel_2_32 = (s_3 == 1'b0 ? sel_23 :
              s_24);

  assign sel_24 = 1'b0;

  assign sel_2_33 = (reset_1 == 1'b0 ? sel_2_32 :
              sel_24);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_16_process
      if (reset == 1'b1) begin
        delayMatch_reg_13 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_13[0] <= sel_2_33;
          delayMatch_reg_13[1] <= delayMatch_reg_13[0];
        end
      end
    end

  assign sel_2_34 = delayMatch_reg_13[1];

  assign tmp_32 = 32'sd13;

  assign sel_25 = 1'b0;

  assign s_25 = 1'b1;

  assign sel_2_35 = (s_3 == 1'b0 ? sel_25 :
              s_25);

  assign sel_26 = 1'b0;

  assign sel_2_36 = (reset_1 == 1'b0 ? sel_2_35 :
              sel_26);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_17_process
      if (reset == 1'b1) begin
        delayMatch_reg_14 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_14[0] <= sel_2_36;
          delayMatch_reg_14[1] <= delayMatch_reg_14[0];
        end
      end
    end

  assign sel_2_37 = delayMatch_reg_14[1];

  assign tmp_33 = 32'sd14;

  assign sel_27 = 1'b0;

  assign s_26 = 1'b1;

  assign sel_2_38 = (s_3 == 1'b0 ? sel_27 :
              s_26);

  assign sel_28 = 1'b0;

  assign sel_2_39 = (reset_1 == 1'b0 ? sel_2_38 :
              sel_28);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_18_process
      if (reset == 1'b1) begin
        delayMatch_reg_15 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_15[0] <= sel_2_39;
          delayMatch_reg_15[1] <= delayMatch_reg_15[0];
        end
      end
    end

  assign sel_2_40 = delayMatch_reg_15[1];

  assign tmp_34 = 32'sd15;

  assign sel_29 = 1'b0;

  assign s_27 = 1'b1;

  assign sel_2_41 = (s_3 == 1'b0 ? sel_29 :
              s_27);

  assign sel_30 = 1'b0;

  assign sel_2_42 = (reset_1 == 1'b0 ? sel_2_41 :
              sel_30);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_19_process
      if (reset == 1'b1) begin
        delayMatch_reg_16 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_16[0] <= sel_2_42;
          delayMatch_reg_16[1] <= delayMatch_reg_16[0];
        end
      end
    end

  assign sel_2_43 = delayMatch_reg_16[1];

  assign tmp_35 = 32'sd16;

  assign sel_31 = 1'b0;

  assign s_28 = 1'b1;

  assign sel_2_44 = (s_3 == 1'b0 ? sel_31 :
              s_28);

  assign sel_32 = 1'b0;

  assign sel_2_45 = (reset_1 == 1'b0 ? sel_2_44 :
              sel_32);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_20_process
      if (reset == 1'b1) begin
        delayMatch_reg_17 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_17[0] <= sel_2_45;
          delayMatch_reg_17[1] <= delayMatch_reg_17[0];
        end
      end
    end

  assign sel_2_46 = delayMatch_reg_17[1];

  assign tmp_36 = 32'sd17;

  assign sel_33 = 1'b0;

  assign s_29 = 1'b1;

  assign sel_2_47 = (s_3 == 1'b0 ? sel_33 :
              s_29);

  assign sel_34 = 1'b0;

  assign sel_2_48 = (reset_1 == 1'b0 ? sel_2_47 :
              sel_34);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_21_process
      if (reset == 1'b1) begin
        delayMatch_reg_18 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_18[0] <= sel_2_48;
          delayMatch_reg_18[1] <= delayMatch_reg_18[0];
        end
      end
    end

  assign sel_2_49 = delayMatch_reg_18[1];

  assign s_30 = 24'b000000000000000011111111;

  assign p358middle_r_and_temp = line1 & s_30;
  assign middle_r = p358middle_r_and_temp[7:0];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_22_process
      if (reset == 1'b1) begin
        middle_r_1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          middle_r_1 <= middle_r;
        end
      end
    end

  assign sel_35 = 1'b0;

  assign s_31 = 1'b1;

  assign sel_2_50 = (s_3 == 1'b0 ? sel_35 :
              s_31);

  assign sel_36 = 1'b0;

  assign sel_2_51 = (reset_1 == 1'b0 ? sel_2_50 :
              sel_36);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_23_process
      if (reset == 1'b1) begin
        delayMatch_reg_19 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_19[0] <= sel_2_51;
          delayMatch_reg_19[1] <= delayMatch_reg_19[0];
        end
      end
    end

  assign sel_2_52 = delayMatch_reg_19[1];

  assign y_2 = line1 >>> 16'd8;

  assign s_32 = 24'b000000000000000011111111;

  assign p361middle_g_and_temp = y_2 & s_32;
  assign middle_g = p361middle_g_and_temp[7:0];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_24_process
      if (reset == 1'b1) begin
        middle_g_1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          middle_g_1 <= middle_g;
        end
      end
    end

  assign sel_37 = 1'b0;

  assign s_33 = 1'b1;

  assign sel_2_53 = (s_3 == 1'b0 ? sel_37 :
              s_33);

  assign sel_38 = 1'b0;

  assign sel_2_54 = (reset_1 == 1'b0 ? sel_2_53 :
              sel_38);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_25_process
      if (reset == 1'b1) begin
        delayMatch_reg_20 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_20[0] <= sel_2_54;
          delayMatch_reg_20[1] <= delayMatch_reg_20[0];
        end
      end
    end

  assign sel_2_55 = delayMatch_reg_20[1];

  assign y_3 = line1 >>> 16'd16;

  assign middle_b = y_3[7:0];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_26_process
      if (reset == 1'b1) begin
        middle_b_1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          middle_b_1 <= middle_b;
        end
      end
    end

  assign sel_39 = 1'b0;

  assign s_34 = 1'b1;

  assign sel_2_56 = (s_3 == 1'b0 ? sel_39 :
              s_34);

  assign sel_40 = 1'b0;

  assign sel_2_57 = (reset_1 == 1'b0 ? sel_2_56 :
              sel_40);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_27_process
      if (reset == 1'b1) begin
        delayMatch_reg_21 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_21[0] <= sel_2_57;
          delayMatch_reg_21[1] <= delayMatch_reg_21[0];
        end
      end
    end

  assign sel_2_58 = delayMatch_reg_21[1];

  assign tmp_37 = 32'sd21;

  assign sel_41 = 1'b0;

  assign s_35 = 1'b1;

  assign sel_2_59 = (s_3 == 1'b0 ? sel_41 :
              s_35);

  assign sel_42 = 1'b0;

  assign sel_2_60 = (reset_1 == 1'b0 ? sel_2_59 :
              sel_42);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_28_process
      if (reset == 1'b1) begin
        delayMatch_reg_22 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_22[0] <= sel_2_60;
          delayMatch_reg_22[1] <= delayMatch_reg_22[0];
        end
      end
    end

  assign sel_2_61 = delayMatch_reg_22[1];

  assign tmp_38 = 32'sd22;

  assign sel_43 = 1'b0;

  assign s_36 = 1'b1;

  assign sel_2_62 = (s_3 == 1'b0 ? sel_43 :
              s_36);

  assign sel_44 = 1'b0;

  assign sel_2_63 = (reset_1 == 1'b0 ? sel_2_62 :
              sel_44);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_29_process
      if (reset == 1'b1) begin
        delayMatch_reg_23 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_23[0] <= sel_2_63;
          delayMatch_reg_23[1] <= delayMatch_reg_23[0];
        end
      end
    end

  assign sel_2_64 = delayMatch_reg_23[1];

  assign tmp_39 = 32'sd23;

  assign sel_45 = 1'b0;

  assign s_37 = 1'b1;

  assign sel_2_65 = (s_3 == 1'b0 ? sel_45 :
              s_37);

  assign sel_46 = 1'b0;

  assign sel_2_66 = (reset_1 == 1'b0 ? sel_2_65 :
              sel_46);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_30_process
      if (reset == 1'b1) begin
        delayMatch_reg_24 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_24[0] <= sel_2_66;
          delayMatch_reg_24[1] <= delayMatch_reg_24[0];
        end
      end
    end

  assign sel_2_67 = delayMatch_reg_24[1];

  assign tmp_40 = 32'sd24;

  assign sel_47 = 1'b0;

  assign s_38 = 1'b1;

  assign sel_2_68 = (s_3 == 1'b0 ? sel_47 :
              s_38);

  assign sel_48 = 1'b0;

  assign sel_2_69 = (reset_1 == 1'b0 ? sel_2_68 :
              sel_48);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_31_process
      if (reset == 1'b1) begin
        delayMatch_reg_25 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_25[0] <= sel_2_69;
          delayMatch_reg_25[1] <= delayMatch_reg_25[0];
        end
      end
    end

  assign sel_2_70 = delayMatch_reg_25[1];

  assign tmp_41 = 32'sd25;

  assign sel_49 = 1'b0;

  assign s_39 = 1'b1;

  assign sel_2_71 = (s_3 == 1'b0 ? sel_49 :
              s_39);

  assign sel_50 = 1'b0;

  assign sel_2_72 = (reset_1 == 1'b0 ? sel_2_71 :
              sel_50);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_32_process
      if (reset == 1'b1) begin
        delayMatch_reg_26 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_26[0] <= sel_2_72;
          delayMatch_reg_26[1] <= delayMatch_reg_26[0];
        end
      end
    end

  assign sel_2_73 = delayMatch_reg_26[1];

  assign tmp_42 = 32'sd26;

  assign sel_51 = 1'b0;

  assign s_40 = 1'b1;

  assign sel_2_74 = (s_3 == 1'b0 ? sel_51 :
              s_40);

  assign sel_52 = 1'b0;

  assign sel_2_75 = (reset_1 == 1'b0 ? sel_2_74 :
              sel_52);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_33_process
      if (reset == 1'b1) begin
        delayMatch_reg_27 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_27[0] <= sel_2_75;
          delayMatch_reg_27[1] <= delayMatch_reg_27[0];
        end
      end
    end

  assign sel_2_76 = delayMatch_reg_27[1];

  assign tmp_43 = pixel[0];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_34_process
      if (reset == 1'b1) begin
        delayMatch_reg_28 <= '{2{8'b00000000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_28[0] <= tmp_43;
          delayMatch_reg_28[1] <= delayMatch_reg_28[0];
        end
      end
    end

  assign tmp_44 = delayMatch_reg_28[1];

  assign sel_53 = 1'b0;

  assign s_41 = 1'b1;

  assign sel_2_77 = (s_3 == 1'b0 ? sel_53 :
              s_41);

  assign sel_54 = 1'b0;

  assign sel_2_78 = (reset_1 == 1'b0 ? sel_2_77 :
              sel_54);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_35_process
      if (reset == 1'b1) begin
        delayMatch_reg_29 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_29[0] <= sel_2_78;
          delayMatch_reg_29[1] <= delayMatch_reg_29[0];
        end
      end
    end

  assign sel_2_79 = delayMatch_reg_29[1];

  assign tmp_45 = pixel[1];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_36_process
      if (reset == 1'b1) begin
        delayMatch_reg_30 <= '{2{8'b00000000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_30[0] <= tmp_45;
          delayMatch_reg_30[1] <= delayMatch_reg_30[0];
        end
      end
    end

  assign tmp_46 = delayMatch_reg_30[1];

  assign sel_55 = 1'b0;

  assign s_42 = 1'b1;

  assign sel_2_80 = (s_3 == 1'b0 ? sel_55 :
              s_42);

  assign sel_56 = 1'b0;

  assign sel_2_81 = (reset_1 == 1'b0 ? sel_2_80 :
              sel_56);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_37_process
      if (reset == 1'b1) begin
        delayMatch_reg_31 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_31[0] <= sel_2_81;
          delayMatch_reg_31[1] <= delayMatch_reg_31[0];
        end
      end
    end

  assign sel_2_82 = delayMatch_reg_31[1];

  assign tmp_47 = pixel[2];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_38_process
      if (reset == 1'b1) begin
        delayMatch_reg_32 <= '{2{8'b00000000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_32[0] <= tmp_47;
          delayMatch_reg_32[1] <= delayMatch_reg_32[0];
        end
      end
    end

  assign tmp_48 = delayMatch_reg_32[1];

  assign sel_57 = 1'b0;

  assign s_43 = 1'b1;

  assign sel_2_83 = (s_3 == 1'b0 ? sel_57 :
              s_43);

  assign sel_58 = 1'b0;

  assign sel_2_84 = (reset_1 == 1'b0 ? sel_2_83 :
              sel_58);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_39_process
      if (reset == 1'b1) begin
        delayMatch_reg_33 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_33[0] <= sel_2_84;
          delayMatch_reg_33[1] <= delayMatch_reg_33[0];
        end
      end
    end

  assign sel_2_85 = delayMatch_reg_33[1];

  assign tmp_49 = '{27{8'b00000000}};

  assign stateControl_4 = 1'b1;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_40_process
      if (reset == 1'b1) begin
        delayMatch_reg_34 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_34[0] <= stateControl_4;
          delayMatch_reg_34[1] <= delayMatch_reg_34[0];
        end
      end
    end

  assign stateControl_5 = delayMatch_reg_34[1];

  assign enb_gated_1 = stateControl_5 && clk_enable;

  assign tmp_50 = window[tmp_42];

  assign tmp_51 = window[tmp_41];

  assign tmp_52 = window[tmp_40];

  assign tmp_53 = window[tmp_39];

  assign tmp_54 = window[tmp_38];

  assign tmp_55 = window[tmp_37];

  assign tmp_56 = window[tmp_36];

  assign tmp_57 = window[tmp_35];

  assign tmp_58 = window[tmp_34];

  assign tmp_59 = window[tmp_33];

  assign tmp_60 = window[tmp_32];

  assign tmp_61 = window[tmp_31];

  assign tmp_62 = window[tmp_25];

  assign tmp_63 = window[tmp_24];

  assign tmp_64 = window[tmp_23];

  assign tmp_65 = window[tmp_22];

  assign tmp_66 = window[tmp_21];

  assign tmp_67 = window[tmp_20];

  always_comb begin
    new_window_1 = new_window;
    if (sel_2_2) begin
      new_window_1[0] = tmp_67;
    end
  end

  always_comb begin
    new_window_2 = new_window_1;
    if (sel_2_5) begin
      new_window_2[1] = tmp_66;
    end
  end

  always_comb begin
    new_window_3 = new_window_2;
    if (sel_2_8) begin
      new_window_3[2] = tmp_65;
    end
  end

  always_comb begin
    new_window_4 = new_window_3;
    if (sel_2_11) begin
      new_window_4[3] = tmp_64;
    end
  end

  always_comb begin
    new_window_5 = new_window_4;
    if (sel_2_14) begin
      new_window_5[4] = tmp_63;
    end
  end

  always_comb begin
    new_window_6 = new_window_5;
    if (sel_2_17) begin
      new_window_6[5] = tmp_62;
    end
  end

  always_comb begin
    new_window_7 = new_window_6;
    if (sel_2_25) begin
      new_window_7[6] = top_r;
    end
  end

  always_comb begin
    new_window_8 = new_window_7;
    if (sel_2_28) begin
      new_window_8[7] = top_g;
    end
  end

  always_comb begin
    new_window_9 = new_window_8;
    if (sel_2_31) begin
      new_window_9[8] = top_b;
    end
  end

  always_comb begin
    new_window_10 = new_window_9;
    if (sel_2_34) begin
      new_window_10[9] = tmp_61;
    end
  end

  always_comb begin
    new_window_11 = new_window_10;
    if (sel_2_37) begin
      new_window_11[10] = tmp_60;
    end
  end

  always_comb begin
    new_window_12 = new_window_11;
    if (sel_2_40) begin
      new_window_12[11] = tmp_59;
    end
  end

  always_comb begin
    new_window_13 = new_window_12;
    if (sel_2_43) begin
      new_window_13[12] = tmp_58;
    end
  end

  always_comb begin
    new_window_14 = new_window_13;
    if (sel_2_46) begin
      new_window_14[13] = tmp_57;
    end
  end

  always_comb begin
    new_window_15 = new_window_14;
    if (sel_2_49) begin
      new_window_15[14] = tmp_56;
    end
  end

  always_comb begin
    new_window_16 = new_window_15;
    if (sel_2_52) begin
      new_window_16[15] = middle_r_1;
    end
  end

  always_comb begin
    new_window_17 = new_window_16;
    if (sel_2_55) begin
      new_window_17[16] = middle_g_1;
    end
  end

  always_comb begin
    new_window_18 = new_window_17;
    if (sel_2_58) begin
      new_window_18[17] = middle_b_1;
    end
  end

  always_comb begin
    new_window_19 = new_window_18;
    if (sel_2_61) begin
      new_window_19[18] = tmp_55;
    end
  end

  always_comb begin
    new_window_20 = new_window_19;
    if (sel_2_64) begin
      new_window_20[19] = tmp_54;
    end
  end

  always_comb begin
    new_window_21 = new_window_20;
    if (sel_2_67) begin
      new_window_21[20] = tmp_53;
    end
  end

  always_comb begin
    new_window_22 = new_window_21;
    if (sel_2_70) begin
      new_window_22[21] = tmp_52;
    end
  end

  always_comb begin
    new_window_23 = new_window_22;
    if (sel_2_73) begin
      new_window_23[22] = tmp_51;
    end
  end

  always_comb begin
    new_window_24 = new_window_23;
    if (sel_2_76) begin
      new_window_24[23] = tmp_50;
    end
  end

  always_comb begin
    new_window_25 = new_window_24;
    if (sel_2_79) begin
      new_window_25[24] = tmp_44;
    end
  end

  always_comb begin
    new_window_26 = new_window_25;
    if (sel_2_82) begin
      new_window_26[25] = tmp_46;
    end
  end

  always_comb begin
    new_window_27 = new_window_26;
    if (sel_2_85) begin
      new_window_27[26] = tmp_48;
    end
  end

  assign tmp_68 = (s_5 == 1'b0 ? window :
              new_window_27);

  assign tmp_69 = (reset_2 == 1'b0 ? tmp_68 :
              tmp_49);

  always_ff @(posedge clk or posedge reset)
    begin : window_reg_process
      if (reset == 1'b1) begin
        window <= '{27{8'b00000000}};
      end
      else begin
        if (enb_gated_1) begin
          window <= tmp_69;
        end
      end
    end

  assign p = 5'b00001;

  assign tmp_70 = '{108{3'sb000}};

  always_comb begin
    p249_p_0 = 5'b00000;
    p249_p_1 = 5'b00000;
    p249_add_temp = 6'b000000;
    p249_add_temp_0 = 7'b0000000;
    p249_add_temp_1 = 8'b00000000;
    p249_weights = weights;
    p249_p = p;

    for(p249_kr = 32'sd0; p249_kr <= 32'sd2; p249_kr = p249_kr + 32'sd1) begin
      p249_p_0 = p249_p;

      for(p249_kc = 32'sd0; p249_kc <= 32'sd2; p249_kc = p249_kc + 32'sd1) begin
        p249_p_1 = p249_p_0;

        for(p249_ch = 32'sd0; p249_ch <= 32'sd2; p249_ch = p249_ch + 32'sd1) begin
          p249_weights[$signed({1'b0, p249_p_1}) - 32'sd1] = filter0[p249_kr][p249_kc][p249_ch];
          p249_t_0[p249_kc][p249_ch] = {1'b0, p249_p_1};
          p249_add_temp = p249_t_0[p249_kc][p249_ch] + 6'b011011;
          p249_weights[$signed({1'b0, p249_add_temp}) - 32'sd1] = filter1[p249_kr][p249_kc][p249_ch];
          p249_t_1[p249_kc][p249_ch] = {2'b0, p249_p_1};
          p249_add_temp_0 = p249_t_1[p249_kc][p249_ch] + 7'b0110110;
          p249_weights[$signed({1'b0, p249_add_temp_0}) - 32'sd1] = filter2[p249_kr][p249_kc][p249_ch];
          p249_t_2[p249_kc][p249_ch] = {3'b0, p249_p_1};
          p249_add_temp_1 = p249_t_2[p249_kc][p249_ch] + 8'b01010001;
          p249_weights[$signed({1'b0, p249_add_temp_1}) - 32'sd1] = filter3[p249_kr][p249_kc][p249_ch];
          p249_p_1 = p249_p_1 + 5'b00001;
        end

        p249_p_0 = p249_p_1;
      end

      p249_p = p249_p_0;
    end

    weights_1 = p249_weights;
  end

  assign tmp_71 = (s == 1'b0 ? weights :
              weights_1);

  assign tmp_72 = (s_3 == 1'b0 ? weights :
              tmp_71);

  assign tmp_73 = (reset_1 == 1'b0 ? tmp_72 :
              tmp_70);

  always_ff @(posedge clk or posedge reset)
    begin : weights_reg_process
      if (reset == 1'b1) begin
        weights <= '{108{3'sb000}};
      end
      else begin
        if (enb) begin
          weights <= tmp_73;
        end
      end
    end

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_41_process
      if (reset == 1'b1) begin
        delayMatch_reg_35 <= '{216{3'sb000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_35[32'sd0:32'sd107] <= weights[32'sd0:32'sd107];
          delayMatch_reg_35[32'sd108:32'sd215] <= delayMatch_reg_35[32'sd0:32'sd107];
        end
      end
    end

  assign weights_2[32'sd0:32'sd107] = delayMatch_reg_35[32'sd108:32'sd215];

  assign tmp_74 = (s_7 == 1'b0 ? pe_acc :
              tmp_18);

  assign tmp_75 = (s_5 == 1'b0 ? next_acc :
              tmp_74);

  assign tmp_76 = (reset_2 == 1'b0 ? tmp_75 :
              tmp_19);

  always_ff @(posedge clk or posedge reset)
    begin : pe_acc_reg_process
      if (reset == 1'b1) begin
        pe_acc <= '{16{13'sb0000000000000}};
      end
      else begin
        if (enb_gated) begin
          pe_acc <= tmp_76;
        end
      end
    end

  always_comb begin
    p250_add_temp = 6'b000000;
    p250_add_temp_0 = 7'b0000000;
    p250_add_temp_1 = 7'b0000000;
    p250_add_temp_2 = 8'b00000000;
    p250_add_temp_3 = 8'b00000000;
    p250_f = 2'b00;
    p250_lane = 2'b00;
    p250_add_cast = 5'b00000;
    p250_pe = 5'b00000;
    p250_add_cast_0 = 6'b000000;
    p250_index = 5'b00000;
    p250_add_cast_1 = 11'sb00000000000;
    p250_next_acc = pe_acc;

    for(p250_f_iter = 32'sd0; p250_f_iter <= 32'sd3; p250_f_iter = p250_f_iter + 32'sd1) begin
      p250_f = p250_f_iter[1:0];

      for(p250_lane_iter = 32'sd0; p250_lane_iter <= 32'sd3; p250_lane_iter = p250_lane_iter + 32'sd1) begin
        p250_lane = p250_lane_iter[1:0];
        p250_add_cast = {1'b0, {p250_f, 2'b00}};
        p250_t_0[p250_f_iter][p250_lane_iter] = {1'b0, p250_add_cast};
        p250_t_1[p250_f_iter][p250_lane_iter] = {4'b0, p250_lane};
        p250_add_temp = p250_t_0[p250_f_iter][p250_lane_iter] + p250_t_1[p250_f_iter][p250_lane_iter];
        p250_t_2[p250_f_iter][p250_lane_iter] = {1'b0, p250_add_temp};
        p250_add_temp_0 = p250_t_2[p250_f_iter][p250_lane_iter] + 7'b0000001;
        p250_pe = p250_add_temp_0[4:0];
        p250_add_cast_0 = {1'b0, {cycle_4, 2'b00}};
        p250_t_3[p250_f_iter][p250_lane_iter] = {1'b0, p250_add_cast_0};
        p250_t_4[p250_f_iter][p250_lane_iter] = {5'b0, p250_lane};
        p250_add_temp_1 = p250_t_3[p250_f_iter][p250_lane_iter] + p250_t_4[p250_f_iter][p250_lane_iter];
        p250_t_5[p250_f_iter][p250_lane_iter] = {1'b0, p250_add_temp_1};
        p250_add_temp_2 = p250_t_5[p250_f_iter][p250_lane_iter] + 8'b00000001;
        p250_index = p250_add_temp_2[4:0];
        if (p250_index <= 5'b11011) begin
          p250_mul_temp[p250_f_iter][p250_lane_iter] = p250_f * 5'b11011;
          p250_t_6[p250_f_iter][p250_lane_iter] = {1'b0, p250_mul_temp[p250_f_iter][p250_lane_iter]};
          p250_t_7[p250_f_iter][p250_lane_iter] = {3'b0, p250_index};
          p250_add_temp_3 = p250_t_6[p250_f_iter][p250_lane_iter] + p250_t_7[p250_f_iter][p250_lane_iter];
          p250_t_8[p250_f_iter][p250_lane_iter] = {1'b0, window[$signed({1'b0, p250_index}) - 32'sd1]};
          p250_mul_temp_0[p250_f_iter][p250_lane_iter] = p250_t_8[p250_f_iter][p250_lane_iter] * weights_2[$signed({1'b0, p250_add_temp_3}) - 32'sd1];
          p250_add_cast_1 = p250_mul_temp_0[p250_f_iter][p250_lane_iter][10:0];
          p250_t_9[p250_f_iter][p250_lane_iter] = {{2{p250_add_cast_1[10]}}, p250_add_cast_1};
          p250_next_acc[$signed({1'b0, p250_pe}) - 32'sd1] = pe_acc[$signed({1'b0, p250_pe}) - 32'sd1] + p250_t_9[p250_f_iter][p250_lane_iter];
        end
      end

    end

    next_acc = p250_next_acc;
  end

  assign next_acc_1 = next_acc[0];

  assign next_acc_2 = next_acc[1];

  assign next_acc_3 = next_acc[2];

  assign next_acc_4 = next_acc[3];

  assign p353tmp_1 = {next_acc_1[12], next_acc_1};
  assign p353tmp_2 = {next_acc_2[12], next_acc_2};
  assign p353tmp_add_temp = p353tmp_1 + p353tmp_2;
  assign p353tmp_3 = {p353tmp_add_temp[13], p353tmp_add_temp};
  assign p353tmp_4 = {{2{next_acc_3[12]}}, next_acc_3};
  assign p353tmp_add_temp_1 = p353tmp_3 + p353tmp_4;
  assign p353tmp_5 = {p353tmp_add_temp_1[14], p353tmp_add_temp_1};
  assign p353tmp_6 = {{3{next_acc_4[12]}}, next_acc_4};
  assign p353tmp_add_temp_2 = p353tmp_5 + p353tmp_6;
  assign tmp_77 = p353tmp_add_temp_2[12:0];

  assign sel_59 = 1'b0;

  assign s_44 = 1'b1;

  assign sel_2_86 = (s_4 == 1'b0 ? sel_59 :
              s_44);

  assign sel_60 = 1'b0;

  assign sel_2_87 = (s_3 == 1'b0 ? sel_2_86 :
              sel_60);

  assign sel_61 = 1'b0;

  assign sel_2_88 = (reset_1 == 1'b0 ? sel_2_87 :
              sel_61);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_42_process
      if (reset == 1'b1) begin
        delayMatch_reg_36 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_36[0] <= sel_2_88;
          delayMatch_reg_36[1] <= delayMatch_reg_36[0];
        end
      end
    end

  assign sel_2_89 = delayMatch_reg_36[1];

  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //                                                                          %
  //          Generated by MATLAB 25.1 and Fixed-Point Designer 25.1          %
  //                                                                          %
  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  always_comb begin
    output_rsvd_1 = '{4{13'sb0000000000000}};
    if (sel_2_89) begin
      output_rsvd_1[0] = tmp_77;
    end
  end

  assign next_acc_5 = next_acc[4];

  assign next_acc_6 = next_acc[5];

  assign next_acc_7 = next_acc[6];

  assign next_acc_8 = next_acc[7];

  assign p351tmp_1 = {next_acc_5[12], next_acc_5};
  assign p351tmp_2 = {next_acc_6[12], next_acc_6};
  assign p351tmp_add_temp = p351tmp_1 + p351tmp_2;
  assign p351tmp_3 = {p351tmp_add_temp[13], p351tmp_add_temp};
  assign p351tmp_4 = {{2{next_acc_7[12]}}, next_acc_7};
  assign p351tmp_add_temp_1 = p351tmp_3 + p351tmp_4;
  assign p351tmp_5 = {p351tmp_add_temp_1[14], p351tmp_add_temp_1};
  assign p351tmp_6 = {{3{next_acc_8[12]}}, next_acc_8};
  assign p351tmp_add_temp_2 = p351tmp_5 + p351tmp_6;
  assign tmp_78 = p351tmp_add_temp_2[12:0];

  assign sel_62 = 1'b0;

  assign s_45 = 1'b1;

  assign sel_2_90 = (s_4 == 1'b0 ? sel_62 :
              s_45);

  assign sel_63 = 1'b0;

  assign sel_2_91 = (s_3 == 1'b0 ? sel_2_90 :
              sel_63);

  assign sel_64 = 1'b0;

  assign sel_2_92 = (reset_1 == 1'b0 ? sel_2_91 :
              sel_64);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_43_process
      if (reset == 1'b1) begin
        delayMatch_reg_37 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_37[0] <= sel_2_92;
          delayMatch_reg_37[1] <= delayMatch_reg_37[0];
        end
      end
    end

  assign sel_2_93 = delayMatch_reg_37[1];

  assign next_acc_9 = next_acc[8];

  assign next_acc_10 = next_acc[9];

  assign next_acc_11 = next_acc[10];

  always_comb begin
    output_rsvd_2 = output_rsvd_1;
    if (sel_2_93) begin
      output_rsvd_2[1] = tmp_78;
    end
  end

  assign next_acc_12 = next_acc[11];

  assign p352tmp_1 = {next_acc_9[12], next_acc_9};
  assign p352tmp_2 = {next_acc_10[12], next_acc_10};
  assign p352tmp_add_temp = p352tmp_1 + p352tmp_2;
  assign p352tmp_3 = {p352tmp_add_temp[13], p352tmp_add_temp};
  assign p352tmp_4 = {{2{next_acc_11[12]}}, next_acc_11};
  assign p352tmp_add_temp_1 = p352tmp_3 + p352tmp_4;
  assign p352tmp_5 = {p352tmp_add_temp_1[14], p352tmp_add_temp_1};
  assign p352tmp_6 = {{3{next_acc_12[12]}}, next_acc_12};
  assign p352tmp_add_temp_2 = p352tmp_5 + p352tmp_6;
  assign tmp_79 = p352tmp_add_temp_2[12:0];

  assign sel_65 = 1'b0;

  assign s_46 = 1'b1;

  assign sel_2_94 = (s_4 == 1'b0 ? sel_65 :
              s_46);

  assign sel_66 = 1'b0;

  assign sel_2_95 = (s_3 == 1'b0 ? sel_2_94 :
              sel_66);

  assign sel_67 = 1'b0;

  assign sel_2_96 = (reset_1 == 1'b0 ? sel_2_95 :
              sel_67);

  assign next_acc_13 = next_acc[12];

  assign next_acc_14 = next_acc[13];

  assign next_acc_15 = next_acc[14];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_44_process
      if (reset == 1'b1) begin
        delayMatch_reg_38 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_38[0] <= sel_2_96;
          delayMatch_reg_38[1] <= delayMatch_reg_38[0];
        end
      end
    end

  assign sel_2_97 = delayMatch_reg_38[1];

  always_comb begin
    output_rsvd_3 = output_rsvd_2;
    if (sel_2_97) begin
      output_rsvd_3[2] = tmp_79;
    end
  end

  assign next_acc_16 = next_acc[15];

  assign p350tmp_1 = {next_acc_13[12], next_acc_13};
  assign p350tmp_2 = {next_acc_14[12], next_acc_14};
  assign p350tmp_add_temp = p350tmp_1 + p350tmp_2;
  assign p350tmp_3 = {p350tmp_add_temp[13], p350tmp_add_temp};
  assign p350tmp_4 = {{2{next_acc_15[12]}}, next_acc_15};
  assign p350tmp_add_temp_1 = p350tmp_3 + p350tmp_4;
  assign p350tmp_5 = {p350tmp_add_temp_1[14], p350tmp_add_temp_1};
  assign p350tmp_6 = {{3{next_acc_16[12]}}, next_acc_16};
  assign p350tmp_add_temp_2 = p350tmp_5 + p350tmp_6;
  assign tmp_80 = p350tmp_add_temp_2[12:0];

  assign sel_68 = 1'b0;

  assign s_47 = 1'b1;

  assign sel_2_98 = (s_4 == 1'b0 ? sel_68 :
              s_47);

  assign sel_69 = 1'b0;

  assign sel_2_99 = (s_3 == 1'b0 ? sel_2_98 :
              sel_69);

  assign sel_70 = 1'b0;

  assign sel_2_100 = (reset_1 == 1'b0 ? sel_2_99 :
              sel_70);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_45_process
      if (reset == 1'b1) begin
        delayMatch_reg_39 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_39[0] <= sel_2_100;
          delayMatch_reg_39[1] <= delayMatch_reg_39[0];
        end
      end
    end

  assign sel_2_101 = delayMatch_reg_39[1];

  always_comb begin
    output_rsvd_4 = output_rsvd_3;
    if (sel_2_101) begin
      output_rsvd_4[3] = tmp_80;
    end
  end

  assign tmp_81 = (s_6 == 1'b0 ? output_rsvd_1 :
              output_rsvd_4);

  assign tmp_82 = (s_5 == 1'b0 ? tmp_81 :
              output_rsvd_1);

  assign tmp_83 = (reset_2 == 1'b0 ? tmp_82 :
              output_rsvd_1);

  assign output_rsvd = tmp_83;

  assign valid_1 = 1'b0;

  assign valid_2 = 1'b1;

  assign tmp_84 = (s_4 == 1'b0 ? valid_1 :
              valid_2);

  assign tmp_85 = (s_3 == 1'b0 ? tmp_84 :
              valid_1);

  assign tmp_86 = (reset_1 == 1'b0 ? tmp_85 :
              valid_1);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_46_process
      if (reset == 1'b1) begin
        delayMatch_reg_40 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_40[0] <= tmp_86;
          delayMatch_reg_40[1] <= delayMatch_reg_40[0];
        end
      end
    end

  assign tmp_87 = delayMatch_reg_40[1];

  assign valid = tmp_87;

  assign ready_1 = 1'b0;

  assign ready_2 = 1'b1;

  assign tmp_88 = (s_3 == 1'b0 ? ready_1 :
              ready_2);

  assign ready_3 = 1'b0;

  assign tmp_89 = (reset_1 == 1'b0 ? tmp_88 :
              ready_3);

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_47_process
      if (reset == 1'b1) begin
        delayMatch_reg_41 <= '{2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_41[0] <= tmp_89;
          delayMatch_reg_41[1] <= delayMatch_reg_41[0];
        end
      end
    end

  assign tmp_90 = delayMatch_reg_41[1];

  assign ready = tmp_90;

  assign ce_out = clk_enable;

endmodule  // systolic_4x4_fixpt

