// -------------------------------------------------------------
// 
// File Name: C:\Users\user\Desktop\SHREYASHREE\files\systolic_cnn\matlab\codegen\systolic_4x4\hdlsrc\systolic_4x4_fixpt_pkg.sv
// Created: 2026-09-18 22:33:26
// 
// Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
// 
// 
// -------------------------------------------------------------



package systolic_4x4_fixpt_pkg;
  typedef  logic  [7:0] vector_of_unsigned_logic_8;
  typedef  logic signed [2:0] vector_of_signed_logic_3;
  typedef  logic signed [12:0] vector_of_signed_logic_13;
  typedef  logic  [2:0] vector_of_unsigned_logic_3;
  typedef  logic  [5:0] vector_of_unsigned_logic_6;
  typedef  logic  [6:0] vector_of_unsigned_logic_7;
  typedef  logic signed [8:0] vector_of_signed_logic_9;
  typedef  logic signed [11:0] vector_of_signed_logic_12;
endpackage: systolic_4x4_fixpt_pkg

