// -------------------------------------------------------------
// 
// File Name: C:\Users\user\Desktop\SHREYASHREE\files\systolic_cnn\matlab\codegen\conv3x3x3_pixel\hdlsrc\conv3x3x3_pixel_fixpt_pkg.sv
// Created: 2026-09-15 23:23:09
// 
// Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
// 
// 
// -------------------------------------------------------------



package conv3x3x3_pixel_fixpt_pkg;
  typedef  logic  [7:0] vector_of_unsigned_logic_8;
  typedef  logic signed [2:0] vector_of_signed_logic_3;
  typedef  logic signed [8:0] vector_of_signed_logic_9;
  typedef  logic signed [11:0] vector_of_signed_logic_12;
  typedef  logic signed [13:0] vector_of_signed_logic_14;
endpackage: conv3x3x3_pixel_fixpt_pkg

