-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\user\Desktop\SHREYASHREE\files\cnn_fpga\matlab\codegen\conv3x3x3_pixel\hdlsrc\conv3x3x3_pixel_fixpt.vhd
-- Created: 2026-09-15 12:09:58
-- 
-- Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: conv3x3x3_pixel_fixpt
-- Source Path: conv3x3x3_pixel_fixpt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.conv3x3x3_pixel_fixpt_pkg.ALL;

ENTITY conv3x3x3_pixel_fixpt IS
  PORT( image_window                      :   IN    matrix3d_of_std_logic_vector6(0 TO 2, 0 TO 2, 0 TO 2);  -- ufix6 [3x3x3]
        filter                            :   IN    matrix3d_of_std_logic_vector3(0 TO 2, 0 TO 2, 0 TO 2);  -- sfix3 [3x3x3]
        output                            :   OUT   std_logic_vector(7 DOWNTO 0)  -- ufix8
        );
END conv3x3x3_pixel_fixpt;


ARCHITECTURE rtl OF conv3x3x3_pixel_fixpt IS

  -- Signals
  SIGNAL image_window_unsigned            : matrix3d_of_unsigned6(0 TO 2, 0 TO 2, 0 TO 2);  -- ufix6 [3x3x3]
  SIGNAL filter_signed                    : matrix3d_of_signed3(0 TO 2, 0 TO 2, 0 TO 2);  -- sfix3 [3x3x3]
  SIGNAL output_tmp                       : unsigned(7 DOWNTO 0);  -- ufix8

BEGIN
  outputgen3: FOR k IN 0 TO 2 GENERATE
    outputgen4: FOR k1 IN 0 TO 2 GENERATE
      outputgen5: FOR k2 IN 0 TO 2 GENERATE
        image_window_unsigned(k, k1, k2) <= unsigned(image_window(k, k1, k2));
      END GENERATE;
    END GENERATE;
  END GENERATE;

  outputgen: FOR k IN 0 TO 2 GENERATE
    outputgen1: FOR k1 IN 0 TO 2 GENERATE
      outputgen2: FOR k2 IN 0 TO 2 GENERATE
        filter_signed(k, k1, k2) <= signed(filter(k, k1, k2));
      END GENERATE;
    END GENERATE;
  END GENERATE;

  conv3x3x3_pixel_fixpt_1_output : PROCESS (filter_signed, image_window_unsigned)
    VARIABLE acc : unsigned(8 DOWNTO 0);
    VARIABLE add_cast : signed(10 DOWNTO 0);
    VARIABLE cast : signed(6 DOWNTO 0);
    VARIABLE mul_temp : signed(9 DOWNTO 0);
    VARIABLE add_cast_0 : signed(8 DOWNTO 0);
    VARIABLE add_temp : signed(10 DOWNTO 0);
  BEGIN
    mul_temp := to_signed(16#000#, 10);
    add_temp := to_signed(16#000#, 11);
    add_cast := to_signed(16#000#, 11);
    cast := to_signed(16#00#, 7);
    add_cast_0 := to_signed(16#000#, 9);
    --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    --                                                                          %
    --          Generated by MATLAB 25.1 and Fixed-Point Designer 25.1          %
    --                                                                          %
    --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    acc := to_unsigned(16#000#, 9);

    FOR kr IN 0 TO 2 LOOP
      FOR kc IN 0 TO 2 LOOP
        FOR ch IN 0 TO 2 LOOP
          add_cast := signed(resize(acc, 11));
          cast := signed(resize(image_window_unsigned(kr, kc, ch), 7));
          mul_temp := cast * filter_signed(kr, kc, ch);
          add_cast_0 := mul_temp(8 DOWNTO 0);
          add_temp := add_cast + resize(add_cast_0, 11);
          acc := unsigned(add_temp(8 DOWNTO 0));
        END LOOP;
      END LOOP;
    END LOOP;

    output_tmp <= acc(7 DOWNTO 0);
  END PROCESS conv3x3x3_pixel_fixpt_1_output;


  output <= std_logic_vector(output_tmp);

END rtl;

