// -------------------------------------------------------------
// 
// File Name: C:\Users\user\Desktop\SHREYASHREE\files\cnn_fpga\matlab\codegen\conv3x3x3_pixel\hdlsrc\conv3x3x3_pixel_fixpt.sv
// Created: 2026-09-15 18:36:04
// 
// Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// -------------------------------------------------------------


import conv3x3x3_pixel_fixpt_pkg::* ;

// -------------------------------------------------------------
// 
// Module: conv3x3x3_pixel_fixpt
// Source Path: conv3x3x3_pixel_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module conv3x3x3_pixel_fixpt
          (  input vector_of_unsigned_logic_6 image_window[0:2] [0:2] [0:2]  /* ufix6 [3x3x3] */,
             input vector_of_signed_logic_3 filter[0:2] [0:2] [0:2]  /* sfix3 [3x3x3] */,
             output logic [7:0] output_rsvd  /* ufix8 */);


  logic [7:0] output_rsvd_1;  /* ufix8 */
  logic signed [31:0] conv3x3x3_pixel_fixpt_kr;  /* int32 */
  logic signed [31:0] conv3x3x3_pixel_fixpt_kc;  /* int32 */
  logic signed [31:0] conv3x3x3_pixel_fixpt_ch;  /* int32 */
  logic [8:0] conv3x3x3_pixel_fixpt_acc;  /* ufix9 */
  logic signed [8:0] conv3x3x3_pixel_fixpt_add_cast;  /* sfix9 */
  logic signed [10:0] conv3x3x3_pixel_fixpt_add_temp;  /* sfix11 */
  vector_of_signed_logic_7 conv3x3x3_pixel_fixpt_t_0 [0:2] [0:2];  /* sfix7 [3x3] */
  vector_of_signed_logic_10 conv3x3x3_pixel_fixpt_mul_temp [0:2] [0:2];  /* sfix10 [3x3] */
  vector_of_signed_logic_11 conv3x3x3_pixel_fixpt_t_1 [0:2] [0:2];  /* sfix11 [3x3] */
  vector_of_signed_logic_11 conv3x3x3_pixel_fixpt_t_2 [0:2] [0:2];  /* sfix11 [3x3] */


  always_comb begin
    conv3x3x3_pixel_fixpt_add_temp = 11'sb00000000000;
    conv3x3x3_pixel_fixpt_add_cast = 9'sb000000000;
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    //                                                                          %
    //          Generated by MATLAB 25.1 and Fixed-Point Designer 25.1          %
    //                                                                          %
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    conv3x3x3_pixel_fixpt_acc = 9'b000000000;

    for(conv3x3x3_pixel_fixpt_kr = 32'sd0; conv3x3x3_pixel_fixpt_kr <= 32'sd2; conv3x3x3_pixel_fixpt_kr = conv3x3x3_pixel_fixpt_kr + 32'sd1) begin
      for(conv3x3x3_pixel_fixpt_kc = 32'sd0; conv3x3x3_pixel_fixpt_kc <= 32'sd2; conv3x3x3_pixel_fixpt_kc = conv3x3x3_pixel_fixpt_kc + 32'sd1) begin
        for(conv3x3x3_pixel_fixpt_ch = 32'sd0; conv3x3x3_pixel_fixpt_ch <= 32'sd2; conv3x3x3_pixel_fixpt_ch = conv3x3x3_pixel_fixpt_ch + 32'sd1) begin
          conv3x3x3_pixel_fixpt_t_0[conv3x3x3_pixel_fixpt_kc][conv3x3x3_pixel_fixpt_ch] = {1'b0, image_window[conv3x3x3_pixel_fixpt_kr][conv3x3x3_pixel_fixpt_kc][conv3x3x3_pixel_fixpt_ch]};
          conv3x3x3_pixel_fixpt_mul_temp[conv3x3x3_pixel_fixpt_kc][conv3x3x3_pixel_fixpt_ch] = conv3x3x3_pixel_fixpt_t_0[conv3x3x3_pixel_fixpt_kc][conv3x3x3_pixel_fixpt_ch] * filter[conv3x3x3_pixel_fixpt_kr][conv3x3x3_pixel_fixpt_kc][conv3x3x3_pixel_fixpt_ch];
          conv3x3x3_pixel_fixpt_add_cast = conv3x3x3_pixel_fixpt_mul_temp[conv3x3x3_pixel_fixpt_kc][conv3x3x3_pixel_fixpt_ch][8:0];
          conv3x3x3_pixel_fixpt_t_1[conv3x3x3_pixel_fixpt_kc][conv3x3x3_pixel_fixpt_ch] = {2'b0, conv3x3x3_pixel_fixpt_acc};
          conv3x3x3_pixel_fixpt_t_2[conv3x3x3_pixel_fixpt_kc][conv3x3x3_pixel_fixpt_ch] = {{2{conv3x3x3_pixel_fixpt_add_cast[8]}}, conv3x3x3_pixel_fixpt_add_cast};
          conv3x3x3_pixel_fixpt_add_temp = conv3x3x3_pixel_fixpt_t_1[conv3x3x3_pixel_fixpt_kc][conv3x3x3_pixel_fixpt_ch] + conv3x3x3_pixel_fixpt_t_2[conv3x3x3_pixel_fixpt_kc][conv3x3x3_pixel_fixpt_ch];
          conv3x3x3_pixel_fixpt_acc = conv3x3x3_pixel_fixpt_add_temp[8:0];
        end
      end
    end

    output_rsvd_1 = conv3x3x3_pixel_fixpt_acc[7:0];
  end

  assign output_rsvd = output_rsvd_1;

endmodule  // conv3x3x3_pixel_fixpt

