// -------------------------------------------------------------
// 
// File Name: C:\Users\user\Desktop\SHREYASHREE\files\cnn_fpga\matlab\codegen\conv3x3x3_pixel\hdlsrc\conv3x3x3_pixel_fixpt_pkg.sv
// Created: 2026-09-15 18:36:04
// 
// Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
// 
// 
// -------------------------------------------------------------



package conv3x3x3_pixel_fixpt_pkg;
  typedef  logic  [5:0] vector_of_unsigned_logic_6;
  typedef  logic signed [2:0] vector_of_signed_logic_3;
  typedef  logic signed [6:0] vector_of_signed_logic_7;
  typedef  logic signed [9:0] vector_of_signed_logic_10;
  typedef  logic signed [10:0] vector_of_signed_logic_11;
endpackage: conv3x3x3_pixel_fixpt_pkg

