%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 25.1 and Fixed-Point Designer 25.1          %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function output = conv3x3x3_pixel_fixpt(image_window, filter)

fm = get_fimath();

acc = fi(int32(0), 0, 9, 0, fm);

for kr = 1:3
        for kc = 1:3
                for ch = 1:3
                        pixel = fi(int32(image_window(kr, kc, ch)), 0, 6, 0, fm);
                        weight = fi(int32(filter(kr, kc, ch)), 1, 3, 0, fm);
                        acc(:) = acc + pixel * weight;
                end
        end
end

output = fi(acc, 0, 8, 0, fm);

end


function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
